### ISSUE TITLE
surge 不能正常使用

### ISSUE THREAD

**Issue by yanzongzhen** [glzjin/ss-panel-v3-mod#100]
the configuration require an external module  surge

**Comment by glzjin** [comment]
请提供具体是哪种配置文件错误，同时附上站点地址，以便查验底部版权信息。

**Comment by yanzongzhen** [comment]
http:// shadowsocks. ealine.cn
生必定 surge 链接可以下载导入当手机中但是提示要求下载扩展时候点击 download会出现 could  not connect  the server

**Comment by glzjin** [comment]
请发一个具体的例子链接

**Comment by yanzongzhen** [comment]
http://shadowsocks.ealine.cn/link/IM1gV5kG

**Comment by glzjin** [comment]
把baseurl里的https改成http 那里要填写正确

**Comment by yanzongzhen** [comment]
ok 我试试

**Comment by yanzongzhen** [comment]
好了  谢谢
