### ISSUE TITLE
邀请码已经被使用并注册成功，但该邀请码还能继续使用，麻烦看看

### ISSUE THREAD

**Issue by jienai** [glzjin/ss-panel-v3-mod#101]

**Comment by glzjin** [comment]
请提供站点地址以及详细描述错误情况，否则在一天之后此issue会被关闭。

**Comment by jienai** [comment]
http://www.glider.online/ 
我用管理员生成一个邀请码，被邀请者已经使用该邀请码注册成功了，但是这个邀请码还能继续注册使用，邀请码的状态依然是可用状态

**Comment by glzjin** [comment]
注册时500错误，请自行检查相关数据库信息是否填写正确。
glzjin
2016年5月29日 上午10:46，jienai <notifications@github.com>写道：http://www.glider.online/ 
我用管理员生成一个邀请码，被邀请者已经使用该邀请码注册成功了，但是这个邀请码还能继续注册使用，邀请码的状态依然是可用状态

**Comment by jienai** [comment]
[http://a2.qpic.cn/psb?/V12YPO7u3Me7cA/2E00.G1d2HxvP9U0DNAeciQXiHL7s8UF*viUSVfnbs0!/b/dAwBAAAAAAAA&bo=YQWAAgAAAAADB8Q!&rf=viewer_4](url)
[http://a2.qpic.cn/psb?/V12YPO7u3Me7cA/2rk6aBVdIFpa1Npz9V8Ql6U.1K9fDcFq6Cjg9dx1Tc8!/b/dG8BAAAAAAAA&bo=9AQxAAAAAAADAOQ!&rf=viewer_4](url)
可以注册了，麻烦再帮我看下，谢谢

**Comment by glzjin** [comment]
说了 你 radius或者wecenter的数据库信息没填对
glzjin
2016年5月29日 上午11:09，jienai <notifications@github.com>写道：http://a2.qpic.cn/psb?/V12YPO7u3Me7cA/2E00.G1d2HxvP9U0DNAeciQXiHL7s8UF*viUSVfnbs0!/b/dAwBAAAAAAAA&bo=YQWAAgAAAAADB8Q!&rf=viewer_4
http://a2.qpic.cn/psb?/V12YPO7u3Me7cA/2rk6aBVdIFpa1Npz9V8Ql6U.1K9fDcFq6Cjg9dx1Tc8!/b/dG8BAAAAAAAA&bo=9AQxAAAAAAADAOQ!&rf=viewer_4
可以注册了，麻烦再帮我看下，谢谢

**Comment by jienai** [comment]
$System_Config['radius_db_host']='localhost';
$System_Config['radius_db_database']='radius';
$System_Config['radius_db_user']='ss-panel-radius';
$System_Config['radius_db_password']='';

#Radius连接密钥
$System_Config['radius_secret']='';
wecenter数据库我没填，radius這样填对吗，麻烦了

**Comment by jienai** [comment]
radius 	localhost 	是 	USAGE 	否 	编辑权限 编辑权限	导出 导出
	root 	% 	是 	ALL PRIVILEGES 	是 	编辑权限 编辑权限	导出 导出
	root 	127.0.0.1 	是 	ALL PRIVILEGES 	是 	编辑权限 编辑权限	导出 导出
	root 	::1 	是 	ALL PRIVILEGES 	是 	编辑权限 编辑权限	导出 导出
	root 	localhost 	是 	ALL PRIVILEGES 	是 	编辑权限 编辑权限	导出 导出
	root 	whmcs 	是 	ALL PRIVILEGES 	是 	编辑权限 编辑权限	导出 导出
	ss-panel-radius 	localhost 	是 	USAGE 	否 	编辑权限 编辑权限	导出 导出
	ss_panel 	127.0.0.1 	是 	USAGE 	否 	编辑权限 编辑权限	导出 导出
	ss_panel 	localhost 	是 	USAGE 	否 	编辑权限 编辑权限	导出 导出
	sspanel 	localhost 	是 	USAGE 	否 	编辑权限 编辑权限	导出 导出
这个是数据库里的用户

**Comment by glzjin** [comment]
你自己打开debug看看返回吧。。看看哪里错了吧
glzjin
2016年5月29日 上午11:20，jienai <notifications@github.com>写道：$System_Config['radius_db_host']='localhost';
$System_Config['radius_db_database']='radius';
$System_Config['radius_db_user']='ss-panel-radius';
$System_Config['radius_db_password']='';

#Radius连接密钥
$System_Config['radius_secret']='';
wecenter数据库我没填，radius這样填对吗，麻烦了

**Comment by jienai** [comment]
好的，谢啦哈
