### ISSUE TITLE
关闭自定义加密依然能够自定义加密？

### ISSUE THREAD

**Issue by tsingfeng** [glzjin/ss-panel-v3-mod#102]
添加节点时关闭了自定义加密，但是在修改资料处修改加密方式后，节点的加密方式依然被修改。
网址：**ve.red

**Comment by glzjin** [comment]
请提供完整的站点地址。
glzjin
2016年5月29日 上午11:27，tsingfeng <notifications@github.com>写道：添加节点时关闭了自定义加密，但是在修改资料处修改加密方式后，节点的加密方式依然被修改。
网址：**ve.red

**Comment by tsingfeng** [comment]
naive.red

**Comment by glzjin** [comment]
经测试并没有发现你说的问题，请提供更详细的例子并且确认自己操作都正确并且成功。
glzjin
2016年5月29日 上午11:41，glzjin <glzjin@zhaojin97.cn>写道：请提供完整的站点地址。
glzjin
2016年5月29日 上午11:27，tsingfeng <notifications@github.com>写道：添加节点时关闭了自定义加密，但是在修改资料处修改加密方式后，节点的加密方式依然被修改。
网址：**ve.red

**Comment by tsingfeng** [comment]
1.节点关闭了自定义加密
![111](https://cloud.githubusercontent.com/assets/19178724/15631282/133a61d2-2594-11e6-8fc1-02d5771259dd.png)
2.修改加密方式
![112](https://cloud.githubusercontent.com/assets/19178724/15631285/1452f944-2594-11e6-90ac-65a6ee63b2e8.png)
3.修改之后（没有问题）
![113](https://cloud.githubusercontent.com/assets/19178724/15631284/143c7f34-2594-11e6-86fc-b8ac779ae65a.png)
4.显示也没有问题
![114](https://cloud.githubusercontent.com/assets/19178724/15631286/1477472c-2594-11e6-8ade-1f7e9d2b1bf6.png)
5.但是节点服务器的配置信息加密方式却改变了。
![115](https://cloud.githubusercontent.com/assets/19178724/15631283/13b055d6-2594-11e6-8062-7a4bc993dd28.png)
不知道我的操作是不是有问题。  是同一个节点

**Comment by glzjin** [comment]
哪个配置文件？
glzjin
2016年5月29日 上午11:57，tsingfeng <notifications@github.com>写道：1.节点关闭了自定义加密

2.修改加密方式

3.修改之后（没有问题）

4.显示也没有问题

5.但是节点服务器的配置信息加密方式却改变了。

不知道我的操作是不是有问题。  是同一个节点

**Comment by tsingfeng** [comment]
节点服务器上的/tmp/ssshell    不知道这个有没有用。  不过修改加密方式之后用原来的加密方式是不能上网的

**Comment by glzjin** [comment]
是的，ssshell是强制打开自定义加密的。
glzjin
2016年5月29日 下午12:10，tsingfeng <notifications@github.com>写道：节点服务器上的/tmp/ssshell    不知道这个有没有用。  不过修改加密方式之后用原来的加密方式是不能上网的

**Comment by tsingfeng** [comment]
原来如此  谢了
