### ISSUE TITLE
能否在商品中增加群组的设置，实现类似VIP节点的功能

### ISSUE THREAD

**Issue by ouyangmland** [glzjin/ss-panel-v3-mod#103]
因为我看到在节点管理添加节点里面有节点群组的设置，而商品中没有，只是有账号到期和流量一类的设置没有与之对应的群组设置，因为默认用户群组都是0，购买后账号的群组依旧是0，如果加上这个功能，就可以实现不同商品对应不同需求的人

**Comment by ouyangmland** [comment]
其实我想问如何实现高级节点和免费节点，我看了下应该只要简单的在商品里面加一个购买了自动设置用户群组到相应群组的设置就可以实现，而且也没明白这个级数有什么用？
在节点管理添加节点里面只有：节点群组（分组为数字，不分组请填0），在用户管理里面同时显示了两个：用户群组（用户只能访问到组别等于这个数字或0的节点）；用户级别（用户只能访问到等级小于等于这个数字的节点），而添加商品里面只有：等级和等级有效天数。虽然可以通过手动调用户群组的组别，略显麻烦，能否实现自动化呢？希望作者看到能耐心回答下。
我刚刚建的www.speeds.vip
@glzjin

**Comment by glzjin** [comment]
高级节点设置为等级1 免费节点设置为等级0 你就知道了 最近没空 当然你修改了的话欢迎提交pull request
glzjin
2016年5月29日 下午6:04，ouyangmland <notifications@github.com>写道：其实我想问如何实现高级节点和免费节点，我看了下应该只要简单的在商品里面加一个购买了自动设置用户群组到相应群组的设置就可以实现，而且也没明白这个级数有什么用？
在节点管理添加节点里面只有：节点群组（分组为数字，不分组请填0），在用户管理里面同时显示了两个：用户群组（用户只能访问到组别等于这个数字或0的节点）；用户级别（用户只能访问到等级小于等于这个数字的节点），而添加商品里面只有：等级和等级有效天数。虽然可以通过手动调用户群组的组别，略显麻烦，能否实现自动化呢？希望作者看到能耐心回答下。
我刚刚建的www.speeds.vip
@glzjin
