### ISSUE TITLE
关于封IP的疑问

### ISSUE THREAD

**Issue by tsingfeng** [glzjin/ss-panel-v3-mod#105]
不知道ssshell的云安全是怎样判断的，目前我只要连接就会被封（正常使用，其实还没开始用），解封之后再连还是被封。或者是我的操作有问题？
![qq 20160530224010](https://cloud.githubusercontent.com/assets/19178724/15653811/dd9e18be-26c1-11e6-9e06-1455bbe5f645.png)
![qq 20160530223940](https://cloud.githubusercontent.com/assets/19178724/15653818/ef038274-26c1-11e6-99ab-f4c099467573.png)
网址：**e.red(之前发过)

**Comment by glzjin** [comment]
只要是密码错误，加密方式错误，或者扫描端口就会被封，关于ssshell的问题请发到对应的issue区。
