### ISSUE TITLE
请问wecenter关闭注册以后影响同步用户吗？

### ISSUE THREAD

**Issue by pcskys** [glzjin/ss-panel-v3-mod#11]
请问wecenter关闭注册以后影响同步用户吗？
我只看到安装好以后一个自己的帐号，现存的70多个帐号没有同步进去
在xcat里也没看到同步的命令

请问之前的文章哪里有单独说明吗。。。我只看了安装wiki没提到这部分

**Comment by pcskys** [comment]
哦对了wecenter的mysql帐号也是单独的，需要与sspanel使用同一个mysql帐号吗

**Comment by glzjin** [comment]
用户在登录sspanel 时会自动同步到wecenter的用户表并且登录。
glzjin
2016年5月3日 下午9:19，pcskys <notifications@github.com>写道：请问wecenter关闭注册以后影响同步用户吗？
我只看到安装好以后一个自己的帐号，现存的70多个帐号没有同步进去
在xcat里也没看到同步的命令

请问之前的文章哪里有单独说明吗。。。我只看了安装wiki没提到这部分

**Comment by glzjin** [comment]
不需要，单独设置一个账号，只需要给wecenter的权限。
glzjin
2016年5月3日 下午9:24，glzjin <glzjin@zhaojin97.cn>写道：用户在登录sspanel 时会自动同步到wecenter的用户表并且登录。
glzjin
2016年5月3日 下午9:19，pcskys <notifications@github.com>写道：请问wecenter关闭注册以后影响同步用户吗？
我只看到安装好以后一个自己的帐号，现存的70多个帐号没有同步进去
在xcat里也没看到同步的命令

请问之前的文章哪里有单独说明吗。。。我只看了安装wiki没提到这部分

**Comment by pcskys** [comment]
好吧，我在自己看看。。但目前还是不知道为什么并没有同步

打开调试工具看了 登录正常没提示什么错误wecenter dbname-user-passwd都设置正常

另外如果我打开debug true会提示如下

app/Controllers/UserController.php

Whoops \ Exception \ ErrorException (E_NOTICE)
Trying to get property of non-object

$node->server=$smt->domain_prefix.".".Config::get("cloudxns_prefix").".".Config::get("cloudxns_domain");

我想问其中cloudxns_prefix是不是就自己填的？还要在cloudxns里设置什么呢？

但是！！如果关闭debug又不影响节点使用

**Comment by glzjin** [comment]
是你smart line里没东西。wecenter是用户登录sspanel才会同步。
glzjin
2016年5月3日 下午10:02，pcskys <notifications@github.com>写道：好吧，我在自己看看。。但目前还是不知道为什么并没有同步

打开调试工具看了 登录正常没提示什么错误wecenter dbname-user-passwd都设置正常

另外如果我打开debug true会提示如下

app/Controllers/UserController.php

Whoops \ Exception \ ErrorException (E_NOTICE)
Trying to get property of non-object

$node->server=$smt->domain_prefix.".".Config::get("cloudxns_prefix").".".Config::get("cloudxns_domain");

我想问其中cloudxns_prefix是不是就自己填的？还要在cloudxns里设置什么呢？

但是！！如果关闭debug又不影响节点使用
