### ISSUE TITLE
vpn的流量统计

### ISSUE THREAD

**Issue by FuaerCN** [glzjin/ss-panel-v3-mod#110]
![66](https://cloud.githubusercontent.com/assets/13153883/15740121/09ba2552-28e6-11e6-866a-19bd4839e64e.png)
VPN 统一流量结算的流量一直为0，哪里出现了问题呢？

**Comment by glzjin** [comment]
没动流量比例？试http://www.yishanhome.com/archives/307

**Comment by FuaerCN** [comment]
按照你的步骤来的
流量比例需要改嘛？

**Comment by glzjin** [comment]
不需要改，
