### ISSUE TITLE
这两天开始后台无法修改用户数据

### ISSUE THREAD

**Issue by nyancat1** [glzjin/ss-panel-v3-mod#112]
必须得跑到数据库后台  user里改

但是其他东西不影响  只有用户数据改不了  其他数据库的数据依然可以网站后台改

求破

报错是一个空白

**Comment by nyancat1** [comment]
原来都好好的 不知道为什么

**Comment by glzjin** [comment]
检查一下radius数据库和wecenter数据库信息填对了没，要先开debug才能看到错误信息，不使用那两个的话就要把数据库连接信息都清除。还有请提供站点地址。
