### ISSUE TITLE
启动radius失败

### ISSUE THREAD

**Issue by bearjuice** [glzjin/ss-panel-v3-mod#115]
centos7 64 vultr

运行service radiusd start && chkconfig radiusd on

出现错误 
Redirecting to /bin/systemctl start  radiusd.service
Job for radiusd.service failed because the control process exited with error code. See "systemctl status radiusd.service" and "journalctl -xe" for details.

配置radius的时候sql.conf里面是空的，后面我配置了相关参数还是没启动成功

http://fim.space

**Comment by glzjin** [comment]
自己上网搜吧，这个我解决不了。
