### ISSUE TITLE
管理面板的流量使用记录中的结算流量显示都是整数型

### ISSUE THREAD

**Issue by lion1991** [glzjin/ss-panel-v3-mod#118]
![qq 20160610143101](https://cloud.githubusercontent.com/assets/18396082/15956035/421fc068-2f18-11e6-848c-0197fda3c163.png)

这个是就是这么设定的吗 还是需要改什么

网站xxbow.win 之前提交过

**Comment by glzjin** [comment]
要改ssshell，懒得改了
