### ISSUE TITLE
一个关于同步到radius的建议

### ISSUE THREAD

**Issue by frankwei98** [glzjin/ss-panel-v3-mod#119]
我刚刚安装好ss-panel
运行了 php xcat syncusers后
系统发了一封邮件 内容是
> 您好，为了保证密码系统的统一，刚刚系统已经将您 vpn 等连接方式的用户名已经重置为：xxxxx98gmailcom

我觉得这样不利于用户体验(对于邮箱太长的人来说)
不如把radius的用户名的生成从用户邮箱改为系统分配的Shadowsocks端口?

**Comment by glzjin** [comment]
自己改吧
------------------------------------------------------------------发件人：Frank Wei <notifications@github.com>发送时间：2016年6月11日(星期六) 11:40收件人：glzjin/ss-panel-v3-mod <ss-panel-v3-mod@noreply.github.com>主　题：[glzjin/ss-panel-v3-mod] 一个关于同步到radius的建议 (#119)
我刚刚安装好ss-panel

运行了 php xcat syncusers后

系统发了一封邮件 内容是您好，为了保证密码系统的统一，刚刚系统已经将您 vpn 等连接方式的用户名已经重置为：xxxxx98gmailcom我觉得这样不利于用户体验(对于邮箱太长的人来说)

不如把radius的用户名的生成从用户邮箱改为系统分配的Shadowsocks端口?—
