### ISSUE TITLE
新安装的，打开界面正常，登陆用户后，就提示Unable to load template file 'user/index.tpl'

### ISSUE THREAD

**Issue by j0hnnie** [glzjin/ss-panel-v3-mod#120]
Unable to load template file 'user/index.tpl'

首页都正常，nginx的配置重写也正常啊

**Comment by glzjin** [comment]
文件不正确= =你主题设置正确了吗？看看数据库里这个用户的theme

**Comment by glzjin** [comment]
请提供你的站点地址，此issue暂时关闭.
