### ISSUE TITLE
所有的操作 要不没有返回提示 要不返回200错误

### ISSUE THREAD

**Issue by imzmy** [glzjin/ss-panel-v3-mod#121]
比如说商店充值 200错误

登陆的时候 不提示 登陆成功 什么反应都没有  过一会 刷新一下就进去了

注册的时候不提示 是否成功

都是提示200错误 要不是就是 蹦出来一个框 上面什么都没有

网址 87ss.cc

**Comment by imzmy** [comment]
首页修改过了 用户界面保留了STAFF

**Comment by glzjin** [comment]
目测你数据库没配置正确，wecenter等的。

**Comment by imzmy** [comment]
具体要怎么操作呢 我留一下 联系方式QQ99887481 能加我一下吗？
