### ISSUE TITLE
续费时自动重置流量不能开启

### ISSUE THREAD

**Issue by lz2xg** [glzjin/ss-panel-v3-mod#124]

**Comment by glzjin** [comment]
是不能自动重置流量值吗

**Comment by lz2xg** [comment]
添加商品选中续费时自动重置用户流量为上面这个流量值，保存后仍然是未选中状态

**Comment by glzjin** [comment]
请看issue提出规则，请提供你的站点地址，此issue暂时关闭。

**Comment by lz2xg** [comment]
站点s3.mae5.com，后台编辑商品启用续费自动重置保存后无效，仍然显示“不自动重置”。在数据库里将shop表auto_reset_bandwidth设为1，商品列表显示“自动重置”，但编辑此商品，自动重置按钮仍为灰色，不知道在数据库直接设置是否有效
