### ISSUE TITLE
smtp发信乱码

### ISSUE THREAD

**Issue by lz2xg** [glzjin/ss-panel-v3-mod#126]
用QQ邮箱代收gmail邮件。在QQ邮箱里标题乱码，正文正常；在gmail里打开标题正常，正文乱码。

**Comment by glzjin** [comment]
请提供站点地址
------------------------------------------------------------------发件人：lz2xg <notifications@github.com>发送时间：2016年6月16日(星期四) 10:44收件人：glzjin/ss-panel-v3-mod <ss-panel-v3-mod@noreply.github.com>主　题：[glzjin/ss-panel-v3-mod] smtp发信乱码 (#126)
用QQ邮箱代收gmail邮件。在QQ邮箱里标题乱码，正文正常；在gmail里打开标题正常，正文乱码。—

**Comment by lz2xg** [comment]
s3.mae5.com
