### ISSUE TITLE
用户中心全是这样的

### ISSUE THREAD

**Issue by lz2xg** [glzjin/ss-panel-v3-mod#128]
站点：s3.mae5.com
![image](https://cloud.githubusercontent.com/assets/13827746/16108476/ea1bf78e-33d5-11e6-9667-b2af9423782e.png)

wecenter false

**Comment by glzjin** [comment]
https://github.com/glzjin/ss-panel-v3-mod/commit/846f2acc553ec2ccba521bed0a7e88dea705afd5 请更新到最新版

**Comment by lz2xg** [comment]
全新安装的，最新版

**Comment by lz2xg** [comment]
关闭debug正常了，但问题依然存在

**Comment by glzjin** [comment]
把PHP的报错等级改改咯= =
