### ISSUE TITLE
php xcat createAdmin 出错

### ISSUE THREAD

**Issue by lkddi** [glzjin/ss-panel-v3-mod#129]
[root@niaoyun46278 l.ay.lc]# php xcat createAdmin
PHP Fatal error:  Uncaught exception 'Dotenv\Exception\InvalidPathException' with message 'Unable to read the environment file at /home/wwwroot/l.ay.lc/.env.' in /home/wwwroot/l.ay.lc/vendor/vlucas/phpdotenv/src/Loader.php:75
Stack trace:
#0 /home/wwwroot/l.ay.lc/vendor/vlucas/phpdotenv/src/Loader.php(52): Dotenv\Loader->ensureFileIsReadable()
#1 /home/wwwroot/l.ay.lc/vendor/vlucas/phpdotenv/src/Dotenv.php(50): Dotenv\Loader->load()
#2 /home/wwwroot/l.ay.lc/app/Services/Boot.php(13): Dotenv\Dotenv->load()
#3 /home/wwwroot/l.ay.lc/bootstrap.php(19): App\Services\Boot::loadEnv()
#4 /home/wwwroot/l.ay.lc/xcat(4): require('/home/wwwroot/l...')
#5 {main}
  thrown in /home/wwwroot/l.ay.lc/vendor/vlucas/phpdotenv/src/Loader.php on line 75
求助，这是什么问题？

**Comment by monokoo** [comment]
PHP版本太新了

**Comment by lkddi** [comment]
安装的php5.6 呀

**Comment by lkddi** [comment]
PHP Version 5.6.22

**Comment by lkddi** [comment]
那需要什么版本

**Comment by monokoo** [comment]
安装PHP 5.6.9

**Comment by glzjin** [comment]
文件无法读取，检查权限还有这个是否存在，还有是否开了selinux,提问请提供站点地址。
