### ISSUE TITLE
app/LinkController.php有一处错误

### ISSUE THREAD

**Issue by lion1991** [glzjin/ss-panel-v3-mod#13]
[Proxy Group]
 -Proxy = select,DIRECT'.$proxy_name.'
 +Proxy = select,DIRECT,'.$proxy_name.'

测试了一下.修改前的DIRECT后不加"," 格式是正确的.

**Comment by glzjin** [comment]
感谢，我待会改过来，不过接下来的版本加了商店系统，可能晚点发。
glzjin
2016年5月4日 下午7:18，lion1991 <notifications@github.com>写道：[Proxy Group]
 -Proxy = select,DIRECT'.$proxy_name.'
 +Proxy = select,DIRECT,'.$proxy_name.'

测试了一下.修改前的DIRECT后不加"," 格式是正确的.

**Comment by lion1991** [comment]
收到.
