### ISSUE TITLE
一直提示设置多说域名

### ISSUE THREAD

**Issue by yanzongzhen** [glzjin/ss-panel-v3-mod#132]
设置多说域名   一直跳出来关不了

**Comment by glzjin** [comment]
请提供站点地址

**Comment by yanzongzhen** [comment]
shadowsocks.ealine.cn

**Comment by glzjin** [comment]
请截图以及提交详细截图

**Comment by yanzongzhen** [comment]
好的

**Comment by SnowInJuly** [comment]
在config/.config.php 找到$System_Config['enable_duoshuo']='true';修改成$System_Config['enable_duoshuo']='false'即可！注意权限修改！

**Comment by chenlinchet** [comment]
同。我没有设置多说
