### ISSUE TITLE
centos7的问题

### ISSUE THREAD

**Issue by Penton** [glzjin/ss-panel-v3-mod#136]
centos7安装没有/etc/raddb/sql.conf

**Comment by monokoo** [comment]
因centos7默认安装的radius是3.0的版本，配置文件都不一样

**Comment by glzjin** [comment]
请提交站点地址，此issue暂时关闭。

**Comment by nqzhang** [comment]
同centos7 另外没搭建成功哪来的站点

**Comment by mikaoras** [comment]
centos 7默认的是3.x，可以官网下个2.26编译
