### ISSUE TITLE
lnmp 下，邮件重置密码一直都没有成功过。

### ISSUE THREAD

**Issue by j0hnnie** [glzjin/ss-panel-v3-mod#137]
016/06/27 22:36:57 [error] 9260#0: *322 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 117.25.239.44, server: acv.org, request: "POST /password/reset HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "acv.org", referrer: "http://acv.org/password/reset"

**Comment by glzjin** [comment]
请提交站点地址，此issue暂时关闭。
