### ISSUE TITLE
用户登录没有自动跳转

### ISSUE THREAD

**Issue by chenlinchet** [glzjin/ss-panel-v3-mod#139]
点击登录之后，仍然保持在登录界面。必须点一下其他东西才能跳转到其他页面。站点：www.chet.pub

**Comment by glzjin** [comment]
站点无法访问

**Comment by chenlinchet** [comment]
大神，不好意思，昨天域名更换了dns服务器。你等明天再打开，或者把电脑dns改成119.97.137.185试试
