### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by hemla** [glzjin/ss-panel-v3-mod#14]
![1](https://cloud.githubusercontent.com/assets/18051159/15013379/d91fc0de-1231-11e6-946f-083bd3d1928e.png)
![2](https://cloud.githubusercontent.com/assets/18051159/15013378/d7e81824-1231-11e6-9dbc-0d9dd7e0f9dd.png)

还一个就是，在没有设置mail或者mail参数错误的情况下，是不是无法执行sendDailyMail，也就是不能得到last_day_t，进而在个人中心里的“今日使用流量”显示的”总已用流量“。
原因是否是sendDailyMail默认值设置的是1？

**Comment by glzjin** [comment]
是的，这并不是bug。你喜欢的话可以自己把默认值改成0。
glzjin
2016年5月4日 下午7:57，hemla <notifications@github.com>写道：


还一个就是，在没有设置mail或者mail参数错误的情况下，是不是无法执行sendDailyMail，也就是不能得到last_day_t，进而在个人中心里的“今日使用流量”显示的”总已用流量“。
原因是否是sendDailyMail默认值设置的是1？

**Comment by hemla** [comment]
上边两个图，如果填入之前有人注册过的qq或者g+的号时， qq和g+都提示微信号已注册。

**Comment by glzjin** [comment]
提个pr帮我改下吧，谢谢。
glzjin
2016年5月4日 下午8:19，hemla <notifications@github.com>写道：上边两个图，如果填入之前有人注册过的qq或者g+的号时， qq和g+都提示微信号已注册。

**Comment by hemla** [comment]
额，实话说我不会。。。崭新的新手
