### ISSUE TITLE
更新完后无法添加节点

### ISSUE THREAD

**Issue by mxihan** [glzjin/ss-panel-v3-mod#143]
更新完成后点击添加节点后直接跳转页面，无法添加
返回信息如下
HTML1300: 进行了导航。
`HTML1300: 进行了导航。
create
SCRIPT5007: Unable to get property 'toLowerCase' of undefined or null reference
jquery.min.js (4,2643)
HTML1402: 字符引用缺少结束分号 “;”。
create (286,133)
HTML1508: 不匹配的结束标记。
create (399,4)
HTML1506: 标记不符合要求。
create (433,1)
`
网站地址mxihan.xyz

**Comment by glzjin** [comment]
你有东西没填上？能截个图吗

**Comment by mxihan** [comment]
![2016-07-09 7](https://cloud.githubusercontent.com/assets/20372033/16708779/203f1158-4631-11e6-964d-ca24976693e6.png)

**Comment by mxihan** [comment]
后面还有好多return不对

**Comment by mxihan** [comment]
![2016-07-10](https://cloud.githubusercontent.com/assets/20372033/16708810/310f9be6-4632-11e6-99f3-58e7250c4be5.png)
![2016-07-10 1](https://cloud.githubusercontent.com/assets/20372033/16708811/3126f386-4632-11e6-80d8-579835ffcb86.png)

**Comment by glzjin** [comment]
因为你没按照节点命名规范来，修改节点名称为规范的名字，或者关掉debug
