### ISSUE TITLE
更新完后无法添加节点

### ISSUE THREAD

**Issue by mxihan** [glzjin/ss-panel-v3-mod#144]
改了命名规则依旧无法添加节点
点完添加后出现下图
![2016-07-10 2](https://cloud.githubusercontent.com/assets/20372033/16708918/989a0cd6-4634-11e6-85ce-e91c01479aa6.png)
站点mxihan.xyz

**Comment by glzjin** [comment]
好 开下debug 然后看看返回。。。edge里我不知道这个叫啥了。。反正就是debug的结果

**Comment by mxihan** [comment]
开着debug的，没弹出debug界面

**Comment by glzjin** [comment]
就是像你这样看看返回 只不过是debug开了之后的

**Comment by glzjin** [comment]
应该点开网络那个选项卡

**Comment by mxihan** [comment]
我传不上github，传微云了
http://share.weiyun.com/b0b91b6724b417e8054448ed473fc94c

**Comment by glzjin** [comment]
你点开看看这个错误的请求的详细内容，好吗？。。。要不然我真的不知道问题在哪。。我自己测试都是没问题的。。。。

**Comment by mxihan** [comment]
`{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'custom_rss' cannot be null (SQL: insert into `ss_node` (`name`, `server`, `method`, `custom_method`, `custom_rss`, `traffic_rate`, `info`, `type`, `node_group`, `node_speedlimit`, `status`, `sort`, `node_ip`, `node_class`, `node_bandwidth_limit`, `bandwidthlimit_resetday`) values (vultr\u65e5\u672c - Shadowsocks, 45.32.249.240, aes-256-cfb, 1, , 1, vultr\u65e5\u672c\u673a\u623f, 1, 0, 0, \u4e0d\u53ef\u7528, 0, 45.32.249.240, 0, 0, 0))","file":"\/home\/wwwroot\/ss.panel\/vendor\/illuminate\/database\/Connection.php","line":673}}`

**Comment by mxihan** [comment]
报的这个

**Comment by glzjin** [comment]
还有你是哪时候更新的呢

**Comment by mxihan** [comment]
7月9号更新的

**Comment by glzjin** [comment]
好的 请问你是怎么更新的呢

**Comment by mxihan** [comment]
git pull

**Comment by mxihan** [comment]
找到了，我是9点30是前更新的

**Comment by mxihan** [comment]
我在更一下试试

**Comment by glzjin** [comment]
你这个是有文件没被覆盖 app/controllers/admin/user controller.php 这个文件没被更新 请自行检查

**Comment by mxihan** [comment]
0709 21:30更新
1.修复无法添加节点的bug。
2.修复一个不太恰当的地方。

**Comment by mxihan** [comment]
这版我没更

**Comment by mxihan** [comment]
问题解决了，谢啦

**Comment by glzjin** [comment]
好的。
