### ISSUE TITLE
登录不自动跳转和删除用户返回空白对话框

### ISSUE THREAD

**Issue by DyckSir** [glzjin/ss-panel-v3-mod#145]
![screen shot 2016-07-10 at 21 59 07](https://cloud.githubusercontent.com/assets/11970938/16714002/9df9cd82-46e9-11e6-80a8-2d48571c0543.png)
![screen shot 2016-07-10 at 21 35 02](https://cloud.githubusercontent.com/assets/11970938/16714004/a7d7dba0-46e9-11e6-826d-eefb3cc9beb3.png)
![screen shot 2016-07-10 at 21 45 47](https://cloud.githubusercontent.com/assets/11970938/16714618/bc53783e-46fb-11e6-8a45-4d3ba982b930.png)

站点是....  已经执行过php fix_bom.php(好像无效 ) 管理员账户密码已发送至您的邮箱

**Comment by glzjin** [comment]
你没开debug 不过就你这种情况来看一般是radius和wecenter数据库没配置好还没把功能开关关掉

**Comment by DyckSir** [comment]
谢谢 的确是radius没配置好 现在ok了
