### ISSUE TITLE
节点列表中情况报告没内容

### ISSUE THREAD

**Issue by rfcc1001** [glzjin/ss-panel-v3-mod#146]
延时和速度报告都是空的没东西 数据库当中ss_node_online_log和ss_node_info都有内容 其他的都正常 什么原因?

**Comment by rfcc1001** [comment]
开启debug后控制台中显示
NS_ERROR_FAILURE: 
d()
 /:15
<匿名>
 /:15
<匿名>
 /:15
 /:15:0
JQMIGRATE: Migrate is installed, version 1.4.0

不懂什么意思

**Comment by glzjin** [comment]
数据错误。截下图？

**Comment by rfcc1001** [comment]
发现是没装speedtest导致不显示 装上之后好了 虽然控制台还显示一样的内容 不过无所谓了
