### ISSUE TITLE
你好，关于对接ssr

### ISSUE THREAD

**Issue by moqiaoduo** [glzjin/ss-panel-v3-mod#147]
userapiconfig.py文件中需要修改API_INTERFACE，这个变量可以赋值的内容为mudbjson, sspanelv2, sspanelv3, sspanelv3ssr, muapiv2(not support)
那么我该选择哪个呢？
以及，对接过程中我还需要注意哪些呢？

**Comment by glzjin** [comment]
请等待我修改的ssr

**Comment by glzjin** [comment]
https://github.com/glzjin/shadowsocks/wiki/说明以及安装方法
