### ISSUE TITLE
开启wecenter后登录无法跳转,debug response报错

### ISSUE THREAD

**Issue by lion1991** [glzjin/ss-panel-v3-mod#15]
现象是点击登录后无反应,刷新页面可以进入到用户中心.wecenter的配置信息在.config.php中已经配置好.当登录用户中心后用户信息会写入到wecenter的数据库中.但是不会自动登录.

response错误:
{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Undefined variable: hash_string","file":"\/home\/wwwroot\/website\/app\/Utils\/Wecenter.php","line":119}}

具体内容:

 113     if (!$hash_data)
 114		{
 115			return false;
 116		}
 117		foreach ($hash_data as $key => $value)
 118		{
 119			$hash_string .= $key . "^]+" . $value . "!;-";
 120		}
 121		$hash_string = substr($hash_string, 0, - 3);
 122		// 加密干扰码，加密解密时需要用到的 key
 123		if (! $hash_key)
 124		{
 125			$hash_key = G_COOKIE_HASH_KEY;
 126		}

PreView:

error: {type:Whoops\Exception\ErrorException, message:Undefined variable: hash_string,…}
file: "/home/wwwroot/website/app/Utils/Wecenter.php"
line: 119
message: "Undefined variable: hash_string"
type: "Whoops\Exception\ErrorException"

**Comment by glzjin** [comment]
你先自己加个初始值吧=、=奇怪我这里没这个问题
glzjin
2016年5月4日 下午9:24，lion1991 <notifications@github.com>写道：现象是点击登录后无反应,刷新页面可以进入到用户中心.wecenter的配置信息在.config.php中已经配置好.当登录用户中心后用户信息会写入到wecenter的数据库中.

response错误:
{"error":{"type":"Whoops\Exception\ErrorException","message":"Undefined variable: hash_string","file":"\/home\/wwwroot\/website\/app\/Utils\/Wecenter.php","line":119}}

具体内容:

113     if (!$hash_data)
 114        {
 115            return false;
 116        }
 117        foreach ($hash_data as $key => $value)
 118        {
** 119          $hash_string .= $key . "^]+" . $value . "!;-";**
 120        }
 121        $hash_string = substr($hash_string, 0, - 3);
 122        // 加密干扰码，加密解密时需要用到的 key
 123        if (! $hash_key)
 124        {
 125            $hash_key = G_COOKIE_HASH_KEY;
 126        }

**Comment by glzjin** [comment]
你的php版本是？
glzjin
2016年5月4日 下午9:58，glzjin <glzjin@zhaojin97.cn>写道：你先自己加个初始值吧=、=奇怪我这里没这个问题
glzjin
2016年5月4日 下午9:24，lion1991 <notifications@github.com>写道：现象是点击登录后无反应,刷新页面可以进入到用户中心.wecenter的配置信息在.config.php中已经配置好.当登录用户中心后用户信息会写入到wecenter的数据库中.

response错误:
{"error":{"type":"Whoops\Exception\ErrorException","message":"Undefined variable: hash_string","file":"\/home\/wwwroot\/website\/app\/Utils\/Wecenter.php","line":119}}

具体内容:

113     if (!$hash_data)
 114        {
 115            return false;
 116        }
 117        foreach ($hash_data as $key => $value)
 118        {
** 119          $hash_string .= $key . "^]+" . $value . "!;-";**
 120        }
 121        $hash_string = substr($hash_string, 0, - 3);
 122        // 加密干扰码，加密解密时需要用到的 key
 123        if (! $hash_key)
 124        {
 125            $hash_key = G_COOKIE_HASH_KEY;
 126        }

**Comment by lion1991** [comment]
5.6.9

**Comment by lion1991** [comment]
@glzjin 把$hash_key和$tmp_str 的连接符的"."去掉可以正常跳转了...这两个变量之前有值?
但是还是无法实现登录sspanel面板后自动登录wecenter.

**Comment by glzjin** [comment]
你动了加密出来就不一样了，试试新版本吧。
