### ISSUE TITLE
主页跳转到500

### ISSUE THREAD

**Issue by liusanp** [glzjin/ss-panel-v3-mod#167]
请问，安装配置完后，打开网址(假设网址是xxxx.ml)就跳转到xxxx.ml/500，网页上显示重定向次数过多。
这是什么问题？
ERR_TOO_MANY_REDIRECTS

**Comment by jimorsm** [comment]
@liusanp 你好，我遇到了同样的问题，网上找不到资料，请问你是怎么解决的？

**Comment by liusanp** [comment]
@jimorsm 没有解决

**Comment by jimorsm** [comment]
表示原版没有这个问题，换成魔改版就不行了

**Comment by glzjin** [comment]
请提供站点地址，并打开 debug
