### ISSUE TITLE
Job.php文件有错误？

### ISSUE THREAD

**Issue by sgwyhwt** [glzjin/ss-panel-v3-mod#17]
执行checkjob任务时，出现
php xcat checkjob
PHP Notice:  Undefined variable: Group in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 181
PHP Notice:  Undefined variable: Group in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 181
PHP Notice:  Undefined variable: Group in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 181
PHP Notice:  Undefined variable: Group in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 181
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 236
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 255
PHP Notice:  Undefined index: record_id in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 256
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 270
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 290
PHP Notice:  Undefined index: record_id in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 291
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 303
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 322
PHP Notice:  Undefined index: record_id in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 323
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 346
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 347
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 348
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 't_id' cannot be null' in /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php:408
Stack trace:
#0 /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php(408): PDOStatement->execute(Array)
#1 /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php(666): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `sm...', Array)
#2 /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('insert into `sm...', Array, Object(Closure))
#3 /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php(409): Illuminate\Database\Connection->run('insert into `sm...', Array, Object(Closure))
#4 /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php(365): Illuminate\Database\Connection->statement('insert into `sm...', A in /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php on line 673

**Comment by glzjin** [comment]
最新版？导入了之前更新的SQL文件吗，主要是node_group 要有
glzjin
2016年5月5日 下午12:53，Kevin <notifications@github.com>写道：执行checkjob任务时，出现
php xcat checkjob
PHP Notice:  Undefined variable: Group in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 181
PHP Notice:  Undefined variable: Group in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 181
PHP Notice:  Undefined variable: Group in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 181
PHP Notice:  Undefined variable: Group in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 181
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 236
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 255
PHP Notice:  Undefined index: record_id in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 256
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 270
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 290
PHP Notice:  Undefined index: record_id in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 291
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 303
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 322
PHP Notice:  Undefined index: record_id in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 323
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 346
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 347
PHP Notice:  Trying to get property of non-object in /home/wwwroot/cat.XXX.com/app/Command/Job.php on line 348
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 't_id' cannot be null' in /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php:408
Stack trace:
#0 /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php(408): PDOStatement->execute(Array)
#1 /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php(666): Illuminate\Database\Connection->Illuminate\Database{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into sm...', Array)
#2 /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('insert intosm...', Array, Object(Closure))
#3 /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php(409): Illuminate\Database\Connection->run('insert into sm...', Array, Object(Closure))
#4 /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php(365): Illuminate\Database\Connection->statement('insert intosm...', A in /home/wwwroot/cat.XXX.com/vendor/illuminate/database/Connection.php on line 673

**Comment by sgwyhwt** [comment]
我检查了，有node_group

**Comment by glzjin** [comment]
里面有东西吗
glzjin
2016年5月5日 下午1:36，Kevin <notifications@github.com>写道：我检查了，有node_group

**Comment by glzjin** [comment]
是哪个版本
glzjin
2016年5月5日 下午1:36，Kevin <notifications@github.com>写道：我检查了，有node_group

**Comment by sgwyhwt** [comment]
有值为0，最新版本的job.php

**Comment by sgwyhwt** [comment]
ALTER TABLE `user` ADD `node_group` INT NOT NULL DEFAULT '0' AFTER `remark`;
ALTER TABLE `ss_node` ADD `node_group` INT NOT NULL DEFAULT '0' AFTER `node_ip`;
ALTER TABLE `smartline` ADD `node_group` INT NOT NULL DEFAULT '0' AFTER `c_id`;

这3个表里都有node_group

**Comment by glzjin** [comment]
行数对不上，你是自己修改过了？

**Comment by sgwyhwt** [comment]
是的，这个文件我里面添加了一小部分我自己的东西。。。

**Comment by glzjin** [comment]
speedtest 里 有数据没？

**Comment by sgwyhwt** [comment]
speedtest表里有数据

**Comment by glzjin** [comment]
= =那不知道了= =你是不是删了我加的东西

**Comment by sgwyhwt** [comment]
没有呀- -
你说的加的东西是指？
job.php这个文件我是直接下载你的，然后加入我自己的一小部分东西
智能线路一开始能正常使用的，后面突然就不行了

**Comment by glzjin** [comment]
因为加了节点组了

**Comment by glzjin** [comment]
所以有一些不同

**Comment by sgwyhwt** [comment]
我知道你加了节点组。
