### ISSUE TITLE
php xcat syncusers 在把账号同步回去的时候报错

### ISSUE THREAD

**Issue by zhangyubushiyu** [glzjin/ss-panel-v3-mod#171]
[root@localhost ss.caowb.tk]# php xcat syncusers
Send sync mail to user: 1PHP Fatal error:  Uncaught exception 'Mailgun\Connection\Exceptions\MissingEndpoint' with message 'The endpoint you've tried to access does not exist. Check your URL.' in /home/wwwroot/ss.caowb.tk/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:134
Stack trace:
#0 /home/wwwroot/ss.caowb.tk/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /home/wwwroot/ss.caowb.tk/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\Connection\RestClient->post('/messages', Array, Array)
#2 /home/wwwroot/ss.caowb.tk/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\Mailgun->post('/messages', Array, Array)
#3 /home/wwwroot/ss.caowb.tk/app/Services/Mail/Mailgun.php(41): Mailgun\Mailgun->sendMessage('', Array, Array)
#4 /home/wwwroot/ss.caowb.tk/app/Services/Mail.php(66): App\Services\Mail\Mailgun->send('751231221@qq.co...', 'SS-\xE5\xAF\x86\xE7\xA0\x81\xE6\x9B\xB4\xE6\x96\xB0...', '<!DOCTYPE html .. in /home/wwwroot/ss.caowb.tk/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 134

用的 服务是使用lnmp1.3搭建的。麻烦问一下是什么原因啊。

**Comment by zhangyubushiyu** [comment]
已经解决。原因是没有设置邮箱。

**Comment by BlingRabbit** [comment]
你好 请问怎么解决的？
我也是报这个错误？
>]# php xcat syncusers
Send sync mail to user: 1PHP Fatal error:  Uncaught exception 'Mailgun\Connection\Exceptions\MissingEndpoint' with message 'The endpoint you've tried to access does not exist. Check your URL.' in /home/wwwroot/Rabbit/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:133
Stack trace:
#0 /home/wwwroot/Rabbit/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /home/wwwroot/Rabbit/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\Connection\RestClient->post('/messages', Array, Array)
#2 /home/wwwroot/Rabbit/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\Mailgun->post('/messages', Array, Array)
#3 /home/wwwroot/Rabbit/app/Services/Mail/Mailgun.php(44): Mailgun\Mailgun->sendMessage('', Array, Array)
#4 /home/wwwroot/Rabbit/app/Services/Mail.php(68): App\Services\Mail\Mailgun->send('1032483246@qq.c...', 'Rabbit-\xE5\xAF\x86\xE7\xA0\x81\xE6\x9B...', '<!DOCTYPE html ...', Array)
#5 /home/wwwroot/Rabbit/app/Com in /home/wwwroot/Rabbit/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 133

我的php版本是 5.6.22
