### ISSUE TITLE
流量倍数统计错误

### ISSUE THREAD

**Issue by mythcry** [glzjin/ss-panel-v3-mod#173]
网站节点ID与SSR后端ID设置一致，节点流量倍数设置无效。
问题如下：如果你设置A节点为N倍，使用100MB流量时，
管理面板显示结算流量为实际使用 100/N 结算100MB，
前台流量记录 点图 显示为使用100/N  MB，
首页流量剩余只扣除100MB。
网站环境为 LNMP1.2+php5.6  Debian 7 x64

**Comment by nqzhang** [comment]
我也发现了 用了流量没统计

**Comment by nqzhang** [comment]
部分节点没有统计 有的统计了 日志没有任何报错

**Comment by mythcry** [comment]
我也出过一段 没统计  重启 又有了 点图断了2个小时

**Comment by mythcry** [comment]
应该是计算错误经过改动之后正常了

原版db_transfer.py

cur.execute("INSERT INTO `user_traffic_log` (`id`, `user_id`, `u`, `d`, `Node_ID`, `rate`, `traffic`, `log_time`) VALUES (NULL, '" + str(self.port_uid_table[id]) + "', '" + str(dt_transfer[id][0] / self.traffic_rate) +"', '" + str(dt_transfer[id][1] / self.traffic_rate) + "', '" + str(get_config().NODE_ID) + "', '" + str(self.traffic_rate) + "', '" + self.trafficShow(dt_transfer[id][0]+dt_transfer[id][1]) + "', unix_timestamp()); ")

改动db_transfer.py

cur.execute("INSERT INTO `user_traffic_log` (`id`, `user_id`, `u`, `d`, `Node_ID`, `rate`, `traffic`, `log_time`) VALUES (NULL, '" + str(self.port_uid_table[id]) + "', '" + str(dt_transfer[id][0] ) +"', '" + str(dt_transfer[id][1] ) + "', '" + str(get_config().NODE_ID) + "', '" + str(self.traffic_rate) + "', '" + self.trafficShow(dt_transfer[id][0] * self.traffic_rate + dt_transfer[id][1] * self.traffic_rate) + "', unix_timestamp()); ")
