### ISSUE TITLE
流量回传问题

### ISSUE THREAD

**Issue by guiduan** [glzjin/ss-panel-v3-mod#175]
我面板用的ss-panel-v3-mod，后端用的glzin推荐的那个ss后端，搭建好之后，其他基本正常，就是当我在ss-panel中的user表中修改用户的信息（比如密码，限速等）之后，节点的流量信息就不回传到mysql了，有没有人跟我情况一样？

**Comment by glzjin** [comment]
暂时无解=、=会回传的 能详细描述下吗

请在提问时带上站点地址。

**Comment by glzjin** [comment]
由于你没有带上站点地址 此issue 暂时关闭。
