### ISSUE TITLE
打开网站提示500

### ISSUE THREAD

**Issue by wyc19960321** [glzjin/ss-panel-v3-mod#177]
![2](https://cloud.githubusercontent.com/assets/17736372/17582952/058b389a-5fe1-11e6-8c24-5a3ea8e6f173.PNG)
如上图，请问如何解决

**Comment by wyc19960321** [comment]
RuntimeException thrown with message "Unexpected data in output buffer. Maybe you have characters before an opening <?php tag?"

Stacktrace:
#4 RuntimeException in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/App.php:552
#3 Slim\App:finalize in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/App.php:344
#2 Slim\App:process in /home/wwwroot/ss.panel/vendor/slim/slim/Slim/App.php:298
#1 Slim\App:run in /home/wwwroot/ss.panel/config/routes.php:265
#0 require in /home/wwwroot/ss.panel/public/index.php:11

**Comment by glzjin** [comment]
你加了什么东西去你编辑的那些文件。。。
