### ISSUE TITLE
测试新版出现的几个错误.

### ISSUE THREAD

**Issue by lion1991** [glzjin/ss-panel-v3-mod#18]
运行环境: mysql  5.5.42   php 5.6.9  linux版本 centos6.5

首先是导入新的数据库和全新导入all都提示:
CREATE TABLE `glzjin_ss2`.`bought` ( `id` BIGINT NOT NULL AUTO_INCREMENT , `userid` BIGINT NOT NULL , `shopid` BIGINT NOT NULL , `datetime` BIGINT NOT NULL , `renew` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

MySQL 返回： 文档

#1049 - Unknown database 'glzjin_ss2' 
----------------------------------------------------------------------------------------------------
可以正常打开网站,登录到后台.然后测试商店系统,添加充值码正常,,充值系统正常,
点击购买记录菜单报错:
Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sspanel.bought' doesn't exist (SQL: select count(*) as aggregate from `bought` where `userid` = 1)

open:/vendor/illuminate/database/Connection.php

672  catch (Exception $e) {
673            throw new QueryException(
674                $query, $this->prepareBindings($bindings), $e

----------------------------------------------------------------------------------------------------
添加商品信息的如下分类后成功跳转报错:
有效期天数(测试填入之为1):
Whoops \ Exception \ ErrorException (E_NOTICE)
Use of undefined constant i - assumed 'i' line32
32			if(i<count($content)&&$key!="class_expire")
33			{
34				$content_text .= ",";
35			}

shop数据表中已写入,其中centent字段值为{"expire":"1"}
----------------------------------------------------------------------------------------------------
流量(测试填入值为1):

同上错误
			
shop数据表中已写入,其中content字段值为{"bandwidth":"1"}
----------------------------------------------------------------------------------------------------
等级(测试填入值1):

同上错误

shop数据表中已写入,其中content字段值为{"class":"1"}
----------------------------------------------------------------------------------------------------
等级有效期天数(测试填入值为100):

同上的错误

shop数据表中已写入,其中content字段值为{"class_expire":"100"}
----------------------------------------------------------------------------------------------------

升级今天的版本后,之前的wecenter继续报错 同样的现象,但是只有这一处了 将. 去掉后成功跳转,无法自动登录wecenter

message":"Undefined variable: tmp_str","file":"\/home\/wwwroot\/ssbow.win\/app\/Utils\/Wecenter.php","line":144}}

139   for ($i = 1; $i <= strlen($hash_string); $i ++)
140		{
141			$char = substr($hash_string, $i - 1, 1);
142			$keychar = substr($hash_key, ($i % strlen($hash_key)) - 2, 1);
143			$char = chr(ord($char) + ord($keychar));
144			$tmp_str .= $char;

**Comment by glzjin** [comment]
还有你的php怎么那么奇葩。。。就在那种地方报错。。
glzjin
2016年5月5日 下午7:50，glzjin <glzjin@zhaojin97.cn>写道：已经修复数据库导入的问题，请下载新的 SQL逐条导入，发现错了也没关系，关键是数据要全。因为之前没删前缀，到那就没导入了。
glzjin
2016年5月5日 下午7:38，lion1991 <notifications@github.com>写道：运行环境: mysql  5.5.42   php 5.6.9  linux版本 centos6.5

首先是导入新的数据库和全新导入all都提示:
CREATE TABLE glzjin_ss2.bought ( id BIGINT NOT NULL AUTO_INCREMENT , userid BIGINT NOT NULL , shopid BIGINT NOT NULL , datetime BIGINT NOT NULL , renew INT NOT NULL , PRIMARY KEY (id)) ENGINE = InnoDB;

MySQL 返回： 文档

#1049 - Unknown database 'glzjin_ss2' 

可以正常打开网站,登录到后台.然后测试商店系统,添加充值码正常,,充值系统正常,
点击购买记录菜单报错:
Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sspanel.bought' doesn't exist (SQL: select count(*) as aggregate from bought where userid = 1)

open:/vendor/illuminate/database/Connection.php

672  catch (Exception $e) {
673            throw new QueryException(
674                $query, $this->prepareBindings($bindings), $e



添加商品信息的如下分类后成功跳转报错:
有效期天数(测试填入之为1):
Whoops \ Exception \ ErrorException (E_NOTICE)
Use of undefined constant i - assumed 'i' line32
32          if(i<count($content)&&$key!="class_expire")
33          {
34              $content_text .= ",";
35          }

shop数据表中已写入,其中centent字段值为{"expire":"1"}

流量(测试填入值为1):

同上错误

shop数据表中已写入,其中content字段值为{"bandwidth":"1"}

等级(测试填入值1):

同上错误

shop数据表中已写入,其中content字段值为{"class":"1"}

等级有效期天数(测试填入值为100):

同上的错误

shop数据表中已写入,其中content字段值为{"class_expire":"100"}

升级今天的版本后,之前的wecenter继续报错 同样的现象,但是只有这一处了 将. 去掉后成功跳转,无法自动登录wecenter

message":"Undefined variable: tmp_str","file":"\/home\/wwwroot\/ssbow.win\/app\/Utils\/Wecenter.php","line":144}}

139   for ($i = 1; $i <= strlen($hash_string); $i ++)
140     {
141         $char = substr($hash_string, $i - 1, 1);
142         $keychar = substr($hash_key, ($i % strlen($hash_key)) - 2, 1);
143         $char = chr(ord($char) + ord($keychar));
144         $tmp_str .= $char;

**Comment by glzjin** [comment]
已经修复数据库导入的问题，请下载新的 SQL逐条导入，发现错了也没关系，关键是数据要全。因为之前没删前缀，到那就没导入了。
glzjin
2016年5月5日 下午7:38，lion1991 <notifications@github.com>写道：运行环境: mysql  5.5.42   php 5.6.9  linux版本 centos6.5

首先是导入新的数据库和全新导入all都提示:
CREATE TABLE glzjin_ss2.bought ( id BIGINT NOT NULL AUTO_INCREMENT , userid BIGINT NOT NULL , shopid BIGINT NOT NULL , datetime BIGINT NOT NULL , renew INT NOT NULL , PRIMARY KEY (id)) ENGINE = InnoDB;

MySQL 返回： 文档

#1049 - Unknown database 'glzjin_ss2' 

可以正常打开网站,登录到后台.然后测试商店系统,添加充值码正常,,充值系统正常,
点击购买记录菜单报错:
Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sspanel.bought' doesn't exist (SQL: select count(*) as aggregate from bought where userid = 1)

open:/vendor/illuminate/database/Connection.php

672  catch (Exception $e) {
673            throw new QueryException(
674                $query, $this->prepareBindings($bindings), $e



添加商品信息的如下分类后成功跳转报错:
有效期天数(测试填入之为1):
Whoops \ Exception \ ErrorException (E_NOTICE)
Use of undefined constant i - assumed 'i' line32
32          if(i<count($content)&&$key!="class_expire")
33          {
34              $content_text .= ",";
35          }

shop数据表中已写入,其中centent字段值为{"expire":"1"}

流量(测试填入值为1):

同上错误

shop数据表中已写入,其中content字段值为{"bandwidth":"1"}

等级(测试填入值1):

同上错误

shop数据表中已写入,其中content字段值为{"class":"1"}

等级有效期天数(测试填入值为100):

同上的错误

shop数据表中已写入,其中content字段值为{"class_expire":"100"}

升级今天的版本后,之前的wecenter继续报错 同样的现象,但是只有这一处了 将. 去掉后成功跳转,无法自动登录wecenter

message":"Undefined variable: tmp_str","file":"\/home\/wwwroot\/ssbow.win\/app\/Utils\/Wecenter.php","line":144}}

139   for ($i = 1; $i <= strlen($hash_string); $i ++)
140     {
141         $char = substr($hash_string, $i - 1, 1);
142         $keychar = substr($hash_key, ($i % strlen($hash_key)) - 2, 1);
143         $char = chr(ord($char) + ord($keychar));
144         $tmp_str .= $char;

**Comment by lion1991** [comment]
导入新的13无报错,继续导入14数据库报:

ALTER TABLE `announcement` ADD `markdown` LONGTEXT NOT NULL AFTER `content`;
MySQL 返回： 文档

#1060 - Duplicate column name 'markdown'

**Comment by lion1991** [comment]
已经可以正常使用商店系统. 还有一处小错误没修复.
app/Controllers/LinkController.php  的273行的DIRECT后 , 要去掉...

[Proxy Group]
Proxy = select,DIRECT'.$proxy_name.'

**Comment by lion1991** [comment]
令问一下作者开发调试用的是哪个php的版本,干脆我也搞成一样得了.这奇葩的php...

**Comment by glzjin** [comment]
那个没让你倒入呀。。。
glzjin
2016年5月5日 下午8:06，lion1991 <notifications@github.com>写道：导入新的13无报错,继续导入14数据库报:

ALTER TABLE announcement ADD markdown LONGTEXT NOT NULL AFTER content;
MySQL 返回： 文档

#1060 - Duplicate column name 'markdown'

**Comment by glzjin** [comment]
去掉什么？
glzjin
2016年5月5日 下午8:09，lion1991 <notifications@github.com>写道：已经可以正常使用商店系统. 还有一处小错误没修复.
app/Controllers/LinkController.php  的273行的DIRECT后 , 要去掉...

[Proxy Group]
Proxy = select,DIRECT'.$proxy_name.'

**Comment by lion1991** [comment]
DIRECT后面的逗号","

**Comment by glzjin** [comment]
不是去掉了吗？
glzjin
2016年5月5日 下午8:21，lion1991 <notifications@github.com>写道：DIRECT后面的逗号","

**Comment by lion1991** [comment]
我看code里面还有呀

**Comment by glzjin** [comment]
哦 没提交上去 晚点弄完其他的东西先吧
glzjin
2016年5月5日 下午9:00，lion1991 <notifications@github.com>写道：我看code里面还有呀

**Comment by glzjin** [comment]
遇到这种问题麻烦直接提个pr帮我修修吧 谢谢
glzjin
2016年5月5日 下午9:05，glzjin <glzjin@zhaojin97.cn>写道：哦 没提交上去 晚点弄完其他的东西先吧
glzjin
2016年5月5日 下午9:00，lion1991 <notifications@github.com>写道：我看code里面还有呀

**Comment by lion1991** [comment]
刚同步完发现你改完了,close~
