### ISSUE TITLE
命令行倒入sql出错

### ISSUE THREAD

**Issue by LOVEChen** [glzjin/ss-panel-v3-mod#180]
ERROR 1064 (42000) at line 245: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ADD PRIMARY KEY `id` int(11) NOT NULL,
  `user_name` varchar(128) CHARACTER SET ' at line 2

**Comment by LOVEChen** [comment]
导入的是glzjin_all.sql

**Comment by LOVEChen** [comment]
mysql -u xxx -p xxx sspanel < glzjin_all.sql

**Comment by glzjin** [comment]
我在 MySQL 5.5 下测试用同样的方法导入完全没有问题在请问你的 MySQL 版本是？

**Comment by LOVEChen** [comment]
您好打扰了，我是在mysql-server-5.6上测的，docker环境中，原版本ss-panel直接替换的mod版做sql导入， 这两天空下来再做更多测试，我测mod生成大概20次 都是sql导入过不了。

**Comment by glzjin** [comment]
开了mysql的严格模式？
