### ISSUE TITLE
后端运行出错

### ISSUE THREAD

**Issue by coolgxt** [glzjin/ss-panel-v3-mod#182]
后端运行后提示表不存在 
`2016-08-18 10:34:51 INFO     auto_block.py:62 Read hosts.deny from line 87`
`2016-08-18 10:35:54 INFO     auto_block.py:62 Read hosts.deny from line 89`
`2016-08-18 10:36:00 ERROR    db_transfer.py:468 Traceback (most recent call last):`
` File "/root/shadowsocks/db_transfer.py", line 462, in thread_db`
`   rows = db_instance.pull_db_all_user()`
` File "/root/shadowsocks/db_transfer.py", line 264, in pull_db_all_user`
`    cur.execute("SELECT " + ','.join(keys_detect) + " FROM detect_list where `type` = 1")`
`  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 133, in execute`
`    self.errorhandler(exc, value)`
`  File "/usr/lib/python2.6/site-packages/cymysql/cursors.py", line 35, in errorhandler`
`    self.connection.errorhandler(self, errorclass, errorvalue)`
`  File "/usr/lib/python2.6/site-packages/cymysql/connections.py", line 118, in errorhandler`
`    raise errorvalue`
`ProgrammingError: (1146, u"Table 'sspanel.detect_list' doesn't exist")`

**Comment by sunnoy** [comment]
解决了么，我也出现这个问题了

**Comment by glzjin** [comment]
请升级前端

**Comment by sunnoy** [comment]
升级过后出现这样  是因为添加节点出现问题么


2016-08-22 10:48:10 INFO     db_transfer.py:411 db start server at port [1026] pass [gr3jZO] protocol [origin] obfs [plain]
2016-08-22 10:48:10 INFO     server_pool.py:137 starting server at [::]:1026
2016-08-22 10:48:10 INFO     server_pool.py:163 starting server at 0.0.0.0:1026
2016-08-22 10:49:10 INFO     auto_block.py:62 Read hosts.deny from line 33

**Comment by sunnoy** [comment]
已解决，这属于正常日志，防火墙的锅
