### ISSUE TITLE
在php xcat createAdmin时提示aws错误

### ISSUE THREAD

**Issue by FeulerLoup** [glzjin/ss-panel-v3-mod#184]
PHP Parse error:  syntax error, unexpected '$value' (T_VARIABLE) in /home/wwwroot/feuler.cn/vendor/aws/aws-sdk-php/src/functions.php on line 36
我好像没碰过这个文件额,.config.php里面的aws id和key都填上了

**Comment by glzjin** [comment]
以后提问请带上站点地址。

PHP版本问题。

**Comment by FeulerLoup** [comment]
我也发现了,升级php就好了.站点在文件夹路径里有的哈.感谢大神的项目:)

**Comment by lithromantic** [comment]
php 5.4  行不行？

**Comment by glzjin** [comment]
@lithromantic 5.6+
