### ISSUE TITLE
按照安装说明来的，为啥redius启动不了

### ISSUE THREAD

**Issue by istrwei** [glzjin/ss-panel-v3-mod#19]
错误日志
Thu May  5 22:36:22 2016 : Error: Could not link driver rlm_sql_mysql: file not found
Thu May  5 22:36:22 2016 : Error: Make sure it (and all its dependent libraries!) are in the search path of your system's ld.
Thu May  5 22:36:22 2016 : Error: /etc/raddb/sql.conf[22]: Instantiation failed for module "sql"
Thu May  5 22:36:22 2016 : Error: /etc/raddb/sites-enabled/default[177]: Failed to find "sql" in the "modules" section.
Thu May  5 22:36:22 2016 : Error: /etc/raddb/sites-enabled/default[69]: Errors parsing authorize section. 
Thu May  5 22:36:22 2016 : Error: Failed to load virtual server <default>

**Comment by glzjin** [comment]
请自己Google 这个我解答不了
glzjin
2016年5月5日 下午10:43，strwei <notifications@github.com>写道：错误日志
Thu May  5 22:36:22 2016 : Error: Could not link driver rlm_sql_mysql: file not found
Thu May  5 22:36:22 2016 : Error: Make sure it (and all its dependent libraries!) are in the search path of your system's ld.
Thu May  5 22:36:22 2016 : Error: /etc/raddb/sql.conf[22]: Instantiation failed for module "sql"
Thu May  5 22:36:22 2016 : Error: /etc/raddb/sites-enabled/default[177]: Failed to find "sql" in the "modules" section.
Thu May  5 22:36:22 2016 : Error: /etc/raddb/sites-enabled/default[69]: Errors parsing authorize section. 
Thu May  5 22:36:22 2016 : Error: Failed to load virtual server

**Comment by istrwei** [comment]
好吧，谢谢了

**Comment by j0hnnie** [comment]
你好，请问一下如何配置节点流量监控。首页readme里的连接点击进去无法显示页面。请问有具体的教程吗

**Comment by glzjin** [comment]
wiki
glzjin
2016年5月6日 上午12:10，j0hnnie <notifications@github.com>写道：你好，请问一下如何配置节点流量监控。首页readme里的连接点击进去无法显示页面。请问有具体的教程吗

**Comment by j0hnnie** [comment]
你好，反馈一个小bug，后台设置了节点，节点的加密方式写了aes-256-cfb，用户那显示的是rc4-md5

**Comment by j0hnnie** [comment]
你好，反馈一个小bug：开启debug时，后台管理点击商店和购买记录都出现：
Whoops \ Exception \ ErrorException (E_NOTICE)
Use of undefined constant i - assumed 'i'

**Comment by glzjin** [comment]
请新开一个issue 附上详细截图
glzjin
2016年5月6日 下午10:54，j0hnnie <notifications@github.com>写道：你好，反馈一个小bug：开启debug时，后台管理点击商店和购买记录都出现：
Whoops \ Exception \ ErrorException (E_NOTICE)
Use of undefined constant i - assumed 'i'

**Comment by glzjin** [comment]
请新开一个issue
glzjin
2016年5月6日 下午10:52，j0hnnie <notifications@github.com>写道：你好，反馈一个小bug，后台设置了节点，节点的加密方式写了aes-256-cfb，用户那显示的是rc4-md5

**Comment by j0hnnie** [comment]
2.你好，反馈一个小bug：开启debug时，后台用户中心内的管理点击商店和购买记录、管理中心内的商品管理、购买记录都出现：
Whoops \ Exception \ ErrorException (E_NOTICE)
Use of undefined constant i - assumed 'i'

都是如下错误：

![image](https://cloud.githubusercontent.com/assets/1672901/15076975/d16c14c4-13de-11e6-950c-fd1ed80c347b.png)

**Comment by j0hnnie** [comment]
1.你好，反馈一个小bug，后台设置了节点，节点的加密方式写了aes-256-cfb，用户那显示的是rc4-md5

![Uploading image.png…]()

**Comment by glzjin** [comment]
这个是开了节点用户自定义加密吧
glzjin
2016年5月6日 下午10:52，j0hnnie <notifications@github.com>写道：你好，反馈一个小bug，后台设置了节点，节点的加密方式写了aes-256-cfb，用户那显示的是rc4-md5

**Comment by mikaoras** [comment]
卤煮找到解决办法了吗@istrwei
谷歌了半天没找到解决方法....

**Comment by istrwei** [comment]
@mikaoras 先配置启动好了redius，然后再对接ss-panel-v3-mod

**Comment by mikaoras** [comment]
radius不是启动不了吗@istrwei
