### ISSUE TITLE
关于重置流量的疑问

### ISSUE THREAD

**Issue by sunnoy** [glzjin/ss-panel-v3-mod#192]
#注册时的流量重置日以及需要重置的流量,0不重置
$System_Config['reg_auto_reset_day']='0';
$System_Config['reg_auto_reset_bandwidth']='100';
  
这样设置的意思是  我在八月六号注册一个账号到九月六号的时候流量不会重置 

$System_Config['reg_auto_reset_day']='1';
$System_Config['reg_auto_reset_bandwidth']='100';

这样就是到九月六号时流量会重置，而且重置流量为100g

我这样理解合适么？

**Comment by glzjin** [comment]
以后提问请带上站点地址。
