### ISSUE TITLE
报错   作者大大

### ISSUE THREAD

**Issue by sunweike** [glzjin/ss-panel-v3-mod#195]
提示这个错误     熬夜到现在也没解决      希望作者在百忙之中 可以给与帮助      多谢哦  

yige一个图片是 jijion貌似装不了     那个安装lnmp后直接安装的后端    前端无安装         

另外一个可以连接数据库    但是无上传也无下载       协议什么的和数据库都对的上     3306端口也开发了的            skip-external-locking   这个命令是不是如果一个网站增加多条线路就需要把他给注释掉呢     

作者一生平安                  希望可以看到                         www.yaohuo.tk       这是我的网站      
![qq 20160827034014](https://cloud.githubusercontent.com/assets/21160314/18018370/0b711be2-6c09-11e6-8c74-d193e1107f84.png)
![qq 20160827034250](https://cloud.githubusercontent.com/assets/21160314/18018369/0b4a2da2-6c09-11e6-96ec-b74410b26bf9.png)
![qq 20160827034642](https://cloud.githubusercontent.com/assets/21160314/18018371/0c08c1f4-6c09-11e6-89c8-f601e6fa3db8.png)

**Comment by sunweike** [comment]
![image](https://cloud.githubusercontent.com/assets/21160314/18018518/0f2be9dc-6c0a-11e6-88f8-952d21389f81.png)
这个线路网站都可以检测到  bao包括延迟什么的   都可以       就是连接手机的时候    无法联网      求作者解答下疑惑     谢谢哦

**Comment by sunweike** [comment]
![image](https://cloud.githubusercontent.com/assets/21160314/18018635/9459ae64-6c0a-11e6-9d17-f6fc316c9ee8.png)
也可以用              就是手机无法l联网                    无奈啊

**Comment by glzjin** [comment]
请开防火墙端口

**Comment by sunweike** [comment]
第一个图片的报错怎么解决呢？开放端口。。。。直接关闭防火墙也不可以耶

**Comment by sunweike** [comment]
求助啊         用的centos7          防火墙都直接关闭了的     还是无法联网
