### ISSUE TITLE
搭建成功之后总提示500错误

### ISSUE THREAD

**Issue by miaoyanginfo** [glzjin/ss-panel-v3-mod#197]
搭建成功之后，过一段时间访问，提示500.清除cookie之后就可以访问了，过一段时间又出现500了。请问是哪里的问题？

**Comment by glzjin** [comment]
请提供站点地址，并打开 debug。

**Comment by miaoyanginfo** [comment]
http://v2.sshome.win/

**Comment by miaoyanginfo** [comment]
已开启debug。麻烦看一下，谢谢

**Comment by miaoyanginfo** [comment]
还有奇怪的是，数据库也登陆不上去了，phpmyadmin提示无法登录 MySQL 服务器

**Comment by WhoRUa** [comment]
是不是phpmyadmin没有lin 到根目录下？ 或者配置文件天的数据不准确，或者挂着代理访问受限？我也出现过，当时用的linode的美西节点，现在换阿里云学生机，这些问题就没有了
