### ISSUE TITLE
处女纠结症  报告作者大大

### ISSUE THREAD

**Issue by zh6223820** [glzjin/ss-panel-v3-mod#198]
作者大大可不可以把用户管理那个界面做成无边框的，因为信息太多了 ，
另外可以在浏览器下面加一个左右拖动的条条，这样不用非得拉倒最底层才能左右来回移动
还有一个非常重要的，是可不可让用户管理里面的每个列可以移动，这样就可以把最重要的信息显示在一个页面里了，比如一大家最关心的是 用了多少流量，最后在线时间，账户到期时间，账户状态 快速禁用和开启

大大觉得呢，如果更新的话我可以和官方同步，但是要是我自己改的话，以后每次同步就会变得很麻烦

**Comment by WhoRUa** [comment]
请问一下，如何设置支付宝支付？

**Comment by glzjin** [comment]
提问请带上站点地址。
