### ISSUE TITLE
执行 php xcat setTelegram错误

### ISSUE THREAD

**Issue by ycg31** [glzjin/ss-panel-v3-mod#201]
root@vultr:/home/wwwroot/ss.panel# php xcat setTelegram
PHP Fatal error:  Uncaught exception 'TelegramBot\Api\HttpException' with message 'Bad Request' in /home/wwwroot/ss.panel/vendor/telegram-bot/api/src/BotApi.php:253
Stack trace:
#0 /home/wwwroot/ss.panel/vendor/telegram-bot/api/src/BotApi.php(236): TelegramBot\Api\BotApi::curlValidate(Resource id #65)
#1 /home/wwwroot/ss.panel/vendor/telegram-bot/api/src/BotApi.php(205): TelegramBot\Api\BotApi->executeCurl(Array)
#2 /home/wwwroot/ss.panel/vendor/telegram-bot/api/src/BotApi.php(370): TelegramBot\Api\BotApi->call('setWebhook', Array)
#3 /home/wwwroot/ss.panel/app/Command/XCat.php(156): TelegramBot\Api\BotApi->setWebhook('https://www.ycg3...')
#4 /home/wwwroot/ss.panel/app/Command/XCat.php(34): App\Command\XCat->setTelegram()
#5 /home/wwwroot/ss.panel/xcat(11): App\Command\XCat->boot()
#6 {main}
  thrown in /home/wwwroot/ss.panel/vendor/telegram-bot/api/src/BotApi.php on line 253

token设置了，baseurl也设置了   不知道如何出错了 麻烦帮看看

http://www.ycg31.ml

**Comment by ctrlbbj** [comment]
你的站并没有启用https

**Comment by glzjin** [comment]
楼上正解。
