### ISSUE TITLE
单端口多用户All-in-One bug

### ISSUE THREAD

**Issue by echoowall** [glzjin/ss-panel-v3-mod#202]
假设设置了单端口多用户的节点的等级，可以正常生效，低等级的用户无法看到单端口多用户节点，但是All-in-One依旧会添加单端口多用户节点。

**Comment by YandexStudio** [comment]
求单端口多用户的详细配置教程

**Comment by echoowall** [comment]
实测单用户多端口的等级控制失效，不到等级的用户依旧可以连接。

**Comment by wxliuxh** [comment]
修改switchrule.py增加判断撒

**Comment by glzjin** [comment]
提问请带上站点地址。
