### ISSUE TITLE
部分站点用手机Chrome登录会卡住

### ISSUE THREAD

**Issue by YandexStudio** [glzjin/ss-panel-v3-mod#205]
只要不开隐身模式都卡住，点击登录后提示欢迎回来，然后自动跳转到登录页面，再点击登录按钮就点不动了，隐身模式没有问题，但是卸载再安装Chrome不用隐身模式还是有问题，应该不是本地Cookie的问题。
自己搭建的有这个情况，试了一下别人的站部分也有这个情况，但不是全都有，比如shadows.adosnan.cf，和ss.abuxiaoxi.com

**Comment by ya0guang** [comment]
也有这个情况

**Comment by glzjin** [comment]
提问请带上站点地址。

**Comment by YandexStudio** [comment]
怎么没给地址？

**Comment by glzjin** [comment]
你自己的站点

**Comment by YandexStudio** [comment]
well，自己的地址enlss.ml，不过都说了和前面发的那几个遇到的是完全相同的情况

**Comment by YandexStudio** [comment]
然后要完地址就不解决了？
