### ISSUE TITLE
单端口多用户流量控制失效

### ISSUE THREAD

**Issue by duguhong** [glzjin/ss-panel-v3-mod#209]
1.实测用户用完流量后连接不上正常的端口，但是单端口仍然能连接上并且有网
2.节点设置流量比例失效，只会应用当前节点设置的流量比例（如单端口设置流量比例1:2，服务器设置1:1，用户连接单端口仍然会以1:1来算）

**Comment by sunyh87** [comment]
干嘛搞单端口多用户啊？

**Comment by duguhong** [comment]
有些vps开不来很多端口

**Comment by duguhong** [comment]
而且既然正好有了，就用用看

**Comment by riverhj** [comment]
需要把单端口的用户开启单端口多用户承载后流量控制就正常了

**Comment by duguhong** [comment]
把要用的用户开启承载后，直接所用流量都不记了，之前还记录流量但是可以超流量连接上单端口

**Comment by glzjin** [comment]
提问请带上站点地址。
