### ISSUE TITLE
智能线路节点信息不一致

### ISSUE THREAD

**Issue by tsingfeng** [glzjin/ss-panel-v3-mod#21]
在节点列表中显示的地址和点进去之后显示地址不一致
![31](https://cloud.githubusercontent.com/assets/19178724/15064449/ea271b92-1386-11e6-8b5c-cb5d4db5e5a2.png)

![32](https://cloud.githubusercontent.com/assets/19178724/15064455/f62e6abc-1386-11e6-8603-56f836bb9ad9.png)

**Comment by glzjin** [comment]
https://github.com/glzjin/ss-panel-v3-mod/commit/b609c617f5bff8e572a2d07e15737be18cc03b68
