### ISSUE TITLE
单端口多用户的服务器地址问题

### ISSUE THREAD

**Issue by PengRui2016** [glzjin/ss-panel-v3-mod#211]
既然服务器地址写的是端口，那么远端服务器的ip之类的该如何设置？？

**Comment by riverhj** [comment]
请教下, 单端口多用户节点服务器添加后不显示.要如何添加

**Comment by vaynenet1** [comment]
添加了 不显示
好像我在什么地方看到说要修改用户数据库

**Comment by langhun** [comment]
要先添加一个正常节点。
在继续添加节点，节点地址填你要的端口，节点类型选 单端口多用户，其他随便。就行了。
然后去用户界面随便点开一个节点就能看到。。

**Comment by riverhj** [comment]
单端口混淆参数系统自动生成,用户无法设置免流混淆参数,要如何解?

**Comment by glzjin** [comment]
提问请带上站点地址。
