### ISSUE TITLE
如果签到流量设置为负数，后台显示有问题，如何修改

### ISSUE THREAD

**Issue by liuchao0130** [glzjin/ss-panel-v3-mod#214]
你好，如果签到流量设置为负数。
点签到后，弹框显示有问题，显示了一大串数字，请问这个要去哪里改代码？
流量应该是减少了，这个好像没问题
不要问我为什么要设负数， 任性~
我严重需要解决这个问题 ，请支援一下

**Comment by liuchao0130** [comment]
![qq 20160908132254](https://cloud.githubusercontent.com/assets/13215589/18337950/a3617d08-75c7-11e6-8e5b-4c468f314024.jpg)
你好，如果签到流量获取的是负数， 弹框显示成这样了，

**Comment by glzjin** [comment]
为什么要放弃治疗
