### ISSUE TITLE
单端口多用户不能统计在线和流量~

### ISSUE THREAD

**Issue by langhun** [glzjin/ss-panel-v3-mod#216]
单端口多用户不能统计在线和流量，然而不是单端口多用户没有這方面问题/ [`是什么原因呢？```]

**Comment by afeng1991** [comment]
是因为你改了默认的混淆，请不要改即可计算流量

**Comment by langhun** [comment]
真心没有改默认的混淆。。

afeng1991 <notifications@github.com>于2016年9月12日周一 15:05写道：

**Comment by langhun** [comment]
发现问题。。是自己搞错了。。不好意思～

**Comment by wuchang233** [comment]
@langhun 可以麻烦说下你怎么解决的可以嘛 我也一样情况

**Comment by dnsml** [comment]
@wuchang233 +1

**Comment by wuchang233** [comment]
@dnsml 我找到个解决的  你试试换加密换成chacha20   混淆协议 origin 参数 http_simple 如果行  回来报声

**Comment by dnsml** [comment]
@wuchang233 我就是这样 不行

**Comment by wuchang233** [comment]
@dnsml 加下qq 我们讨论下

**Comment by dnsml** [comment]
@wuchang233 1784366

**Comment by langhun** [comment]
说实在的我也不知道怎么弄着弄着就好了…

dnsml <notifications@github.com>于2016年10月2日周日 13:43写道：
