### ISSUE TITLE
求救，已经处在崩溃边缘了qwq

### ISSUE THREAD

**Issue by SchraderZhang** [glzjin/ss-panel-v3-mod#217]
SS搭建好了，可以正常使用。
然后问题来了，装这个实在智商不够，装了两天没有装成功。
求好心人来详细的教我QAQ
谢谢。好人一生平安。

**Comment by langhun** [comment]
不知道怎么和你说。。

**Comment by SchraderZhang** [comment]
哎，死活安装不上。我这种小白没救了qwq

**Comment by SchraderZhang** [comment]
@langhun 大佬你能拯救我么

**Comment by langhun** [comment]
我可不是什么大佬，我也是来求解答的～

SchraderZhang <notifications@github.com>于2016年9月12日周一 15:24写道：

**Comment by SchraderZhang** [comment]
@langhun 我连装都装不上，弄了好几天了。刚气得把我服务器删了。

**Comment by langhun** [comment]
有没有其他联系方式？

SchraderZhang <notifications@github.com>于2016年9月12日周一 15:36写道：

**Comment by SchraderZhang** [comment]
@langhun QQ：594972837
