### ISSUE TITLE
节点统计在线和流量有问题，只统计部分节点

### ISSUE THREAD

**Issue by afeng1991** [glzjin/ss-panel-v3-mod#219]
比如VU DO这种，还有部分美国的都不会统计，但是可以用，就是不计算流量，对接是成功的，不知道是什么情况，麻烦赵老板帮忙解答一下 ``

**Comment by afeng1991** [comment]
看日记是完全正常的，但是就很奇怪不会上传在线数和流量，节点也是绿色的

**Comment by afeng1991** [comment]
之前是完全正常的，只从更新了最新的版本就出现问题了，不是单端口，是正常的用户端口

**Comment by glzjin** [comment]
提问请带上站点地址。
