### ISSUE TITLE
后端不更新混淆参数

### ISSUE THREAD

**Issue by Jouaoo** [glzjin/ss-panel-v3-mod#220]
当用户修改连接密码后，前端可以看到单端口的http_simple混淆参数改变，但是后端不会更新这个参数，一直延用旧的参数，重启后端才会重新读取…
改密码后面板的参数
![image](https://cloud.githubusercontent.com/assets/22139792/18458127/14d6f4aa-7991-11e6-83eb-cbc16edd9c8c.png)
SSR旧参数依然可用
![image](https://cloud.githubusercontent.com/assets/22139792/18458163/78991766-7991-11e6-8516-34e63701c44b.png)
反而新的参数不行
![image](https://cloud.githubusercontent.com/assets/22139792/18458192/b8be942e-7991-11e6-8268-8cba694dbffd.png)

**Comment by glzjin** [comment]
提问请带上站点地址。
