### ISSUE TITLE
radius数据库导入时timestamp错误

### ISSUE THREAD

**Issue by wudimenghuan** [glzjin/ss-panel-v3-mod#225]
mysql 5.7已经将timestamp的最小值改为`1970-01-01 00:00:01.000000`
所以这里应该为
```
`lastaccounting` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01.000000'
```

**Comment by glzjin** [comment]
提问请带上站点地址。

**Comment by wudimenghuan** [comment]
为啥要站点地址？我也是程序员，这和站点地址一点关系都没有。
直接用Mysql 5.7试试不就复现了？
而且我这不是提问，而是指出bug

**Comment by wudimenghuan** [comment]
都直接给你解决方案了，只是我没有时间发pull request，我的站点地址设置了用户名密码才能访问，就算给你地址也是看不到页面的。

而且发站点地址是多么愚蠢的做法，大家都是合租的，非公共网站，你怎么不尊重我们的隐私呢

那种能发出地址的，都是不能长久的公共网站

**Comment by glzjin** [comment]
对于你提出的问题以及解决方案，我首先表示感谢。不过不好意思，你来到我这里，就必须遵守我的规则。谢谢合作。
