### ISSUE TITLE
直接给你解决方案

### ISSUE THREAD

**Issue by wudimenghuan** [glzjin/ss-panel-v3-mod#228]
没时间发pull request
这个是你的Bug，不需要带站点地址
详情看
https://github.com/glzjin/ss-panel-v3-mod/issues/225

**Comment by glzjin** [comment]
对于你提出的问题以及解决方案，我首先表示感谢。不过不好意思，你来到我这里，就必须遵守我的规则。谢谢合作。

**Comment by wudimenghuan** [comment]
开源项目还要遵守商业规则？大家共同完善才对。
我们就是不到10人的合租，绝对不能公开地址

我自己改了你的Bug，自己用行了吧
你要是想检查这些，在后端弄个统计不流行了

开个下游你觉得怎么样，把你的bug改掉，但不给你提pull request
