### ISSUE TITLE
节点不统计流量和在线数，日记什么的都正常

### ISSUE THREAD

**Issue by ahuangsen** [glzjin/ss-panel-v3-mod#234]
节点就是不算流量和在线数，但是还是能用，
<img src='http://i1.piimg.com/1949/f8bbea97ae90b39d.png'>
<img src='http://i1.piimg.com/1949/78780b284e6db7c0.png'>
上面是图

**Comment by ahuangsen** [comment]
测试都正常，就是不统计流量和在线数，然后还有时不时的链接不上问题

**Comment by ahuangsen** [comment]
不是单端口，我检测了好长时间，和数据库通讯没有任何问题，看日记也算是正常的，但是不知道为什么就是不显示在线数和计算流量。。 站点地址www.feng666.cc

**Comment by rt9rt9** [comment]
我也遇到同样的问题.....

**Comment by ahuangsen** [comment]
作者，我知道你忙，但是你不解决，就不要让人家发网站，从昨天发到这里，一直在被攻击，醉

**Comment by glzjin** [comment]
你可以选择提交表单 你不想公开站点地址的话

**Comment by ahuangsen** [comment]
我已经把你需要的信息都提供了，这样可以了吗？

**Comment by lkddi** [comment]
怎么提交表单呢 @glzjin

**Comment by wabcwell** [comment]
我遇的是在线人数不正确、。。。。。。。

**Comment by glzjin** [comment]
请发送更完整的日志文件。
