### ISSUE TITLE
工单系统，无法回复及关闭。

### ISSUE THREAD

**Issue by lkddi** [glzjin/ss-panel-v3-mod#236]
新建工单正常。就是回复
一直显示提交中。。。然后就没反应，重新进入状态依旧 

没问题了

**Comment by AENeuro** [comment]
你好你好，我遇到了和你一样的问题，可以问一下你是怎么解决的吗？

**Comment by dxhebei** [comment]
我也遇到这个问题了，创建虽然正在提交，但是是正常的。
回复和回复并关闭无效，一直显示正在提交。不知道问题出在哪里。

**Comment by glzjin** [comment]
@dxhebei 请检查你邮件系统是否配置正确

**Comment by dxhebei** [comment]
谢谢，确实是邮件系统那里没有配置好。
另外注意下，邮件那里需要配置两个地方，默认收发邮件使用mailgun，如果使用自己的smtp进行收发邮件，需要自己修改下$System_Config['mailDriver'] = 'smtp';   // mailgun or smtp
