### ISSUE TITLE
第6部结束后通过浏览器访问ip提示HTTP ERROR 500，新人小白求教

### ISSUE THREAD

**Issue by fandychan** [glzjin/ss-panel-v3-mod#237]
Request URL:http://104.236.132.20/
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:104.236.132.20:80
Response Headers
view source
Connection:keep-alive
Content-Type:text/html; charset=UTF-8
Date:Sun, 25 Sep 2016 05:29:08 GMT
Server:nginx
Transfer-Encoding:chunked
X-Powered-By:PHP/5.6.9
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Host:104.236.132.20
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

GET http://104.236.132.20/ 500 (Internal Server Error)
Navigated to http://104.236.132.20/

只能看到这些了，新人小白求教

**Comment by lithromantic** [comment]
问题解决了没有》
