### ISSUE TITLE
建议:希望用户邀请码生成可以选择数量

### ISSUE THREAD

**Issue by wxliuxh** [glzjin/ss-panel-v3-mod#238]
现在是一次性生成所有.能加个根据数量生成吗.

**Comment by xthujianbo** [comment]
我也这么想的，希望能增加这个功能

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
你是指用户自己选择生成的数量?

**Comment by xthujianbo** [comment]
没错，比如用户可以生成10个邀请码，希望在生成时可以选择生成数量，而不是10个一次性全部生成，应该不难实现，只是看赵大神有没有空，对他来说应该是分分钟的事，不然我自己弄估计要研究一两天，毕竟没学过PHP，只能生搬硬套😂

**Comment by xthujianbo** [comment]
弄了一上午，勉强把这个功能弄出来了
https://github.com/xthujianbo/ss-panel-v3-mod/tree/0926
`但是有个BUG，原先作者的版本里面就有，在用户生成邀请码的页面所有提示信息都没有了，只是简单的刷新了下页面
`                success: function (data) {
                    window.location.reload();
                },`
管理员的界面生产是会有提示的
`                success: function (data) {
                    if (data.ret) {
                        $("#result").modal();
                        $("#msg").html(data.msg);
                        window.setTimeout("location.href='/admin/invite'", {$config['jump_delay']});
					}
                    else
					{
						$("#result").modal();
                        $("#msg").html(data.msg+"。");
					}
					
                    // window.location.reload();
                },`

这个还希望作者能修复一下
