### ISSUE TITLE
使用模改版推荐后端，显示正常但客户端无法连接服务端提示.......

### ISSUE THREAD

**Issue by wxhnizy** [glzjin/ss-panel-v3-mod#239]
使用模改版推荐的后端程序glzjin，搭建完成以后无法正常连接服务器
运行 python service.py 以后显示
> root@ubuntu:/home/wwwroot/1.1.1.7/shadowsocks# python server.py
loaded collections.OrderedDict
IPv6 support
INFO: loading config from user-config.json
2016-09-26 11:29:00 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
Shadowsocks
2016-09-26 11:29:00 INFO     asyncdns.py:324 dns server: [('202.102.152.3', 53), ('202.102.154.3', 53)]

PC客户端扫描二维码后成功添加服务器但是日志显示无法连接 

> [2016-09-26 11:33:45] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.SocketUtil.EndConnectTcp(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

请教大家，有知道怎么解决的吗？

**Comment by glzjin** [comment]
@wxhnizy 你的用户没有被正确加载

**Comment by wxhnizy** [comment]
@glzjin 感谢你的及时回复，但是我不知道是哪里出的问题 ~数据库吗？数据库中 前段是通的 但是在教程中没有提到过 后端 数据库的问题啊？我只修改来 配置文件中的 用户名库名以及访问密码 ~可以告诉我 是哪里的问题吗？

**Comment by glzjin** [comment]
@wxhnizy 请检查一下你数据库中的用户表里有符合这个节点条件的用户

**Comment by wxhnizy** [comment]
@glzjin 数据库中用户名 端口号 密码等 相关值都有。

**Comment by glzjin** [comment]
@wxhnizy 节点有设置节点等级或者群组？

**Comment by wxhnizy** [comment]
@glzjin 添加节点中 群组 等级 流量上限 限速 均为0 节点类型为2.6.8 节点描述为123 开启自定加密以及自定混淆  加密方式 AES-256-CFB 节点名称 测试-shadowsocks 节点地址（局域网）1.1.1.7

**Comment by glzjin** [comment]
@wxhnizy 你用户是不是过期了还是流量超了之类的？截图下 users表 和 ssnode 表 发出来看看？

**Comment by wxhnizy** [comment]
@glzjin 
![Uploading ss_node.png…]()
![Uploading user.png…]()

**Comment by wxhnizy** [comment]
![user](https://cloud.githubusercontent.com/assets/21986327/18822172/b86130f6-83df-11e6-8a2f-2a6cc67a526c.png)
![ss_node](https://cloud.githubusercontent.com/assets/21986327/18822175/bdcacb9c-83df-11e6-96cb-1ed03cc8f63b.png)

@glzjin

**Comment by wxhnizy** [comment]
@glzjin ？看不到图吗？我在传图文件的时候 失败了两次 是不是 看不图片？

**Comment by glzjin** [comment]
@wxhnizy 你节点日志的完整截图发下

**Comment by lkddi** [comment]
@glzjin 先查看ss后端日志，利用工具查看服务器端口是否开放，然后再进行防火墙设置。

**Comment by wxhnizy** [comment]
@lkddi @glzjin 节点的日志 ？我使用了 ./logrun.sh 后台运行 但是我在查看 ssserver.log的时候 里面确实是没有什么内容啊？
![20160926121837](https://cloud.githubusercontent.com/assets/21986327/18822548/a151b6ca-83e3-11e6-9ebc-323d5fb953eb.png)

**Comment by glzjin** [comment]
@wxhnizy I will check the pic you sent later.....

**Comment by wxhnizy** [comment]
@glzjin 你好感谢你的回复，开始我也是认为是防火墙的问题 但是 我设置防火墙无果后 我把它直接给卸载了 ，但是问题 似乎还是没有解决？

**Comment by wxhnizy** [comment]
@lkddi 你好感谢你的回复，开始我也是认为是防火墙的问题 但是 我设置防火墙无果后 我把它直接给卸载了 ，但是问题 似乎还是没有解决？

**Comment by glzjin** [comment]
@wxhnizy No,It's none of business.

**Comment by wxhnizy** [comment]
@glzjin 你好，我想知道 是不是我在虚拟机里 部署的原因呢？我尝试过 SSPANEL+ＳＳＲ　但那时候是可以正常使用的呀～　后来看到魔改感觉挺好的　想尝试下，但没想到　卡在了　后端上～

**Comment by glzjin** [comment]
@wxhnizy Can not pull user info from database.

**Comment by wxhnizy** [comment]
@glzjin　真心不想去上班，但是为了糊口，．．．．．． 晚些我会在线来补充我的问题，还希望 @glzjin 可以帮助我解决，我的英文水平不怎么好，得靠翻译软件，@glzjin方便使用中文与我交流吗？感谢

**Comment by glzjin** [comment]
@wxhnizy Oh,sorry,my device can't input chinese at telegram.I will use my mobile phone later.

**Comment by wxhnizy** [comment]
@glzjin 你好 ~请问还在吗？

**Comment by glzjin** [comment]
@wxhnizy 不在

**Comment by wxhnizy** [comment]
@glzjin 可以帮我 分析下我的症状吗？我被这个问题困恼了2天了 ~ 可否帮忙解决呢？

**Comment by JohnFreeman9** [comment]
@wxhnizy try to fix it yourself, it's all of your own business, but not a issue

**Comment by wxhnizy** [comment]
@JohnFreeman9 感谢回复，我自己尝试着解决过 但是我不找不到问题的所在，无法连接用户数据 ，我的数据库配置都是正常的 ~ 没发现什么不合适的地方，自己才疏学浅 才过来询问还希望得到大家的帮助？

**Comment by JohnFreeman9** [comment]
@wxhnizy check your user rights setting first

**Comment by wxhnizy** [comment]
@JohnFreeman9 我重新分配权限很多次了，我在试试吧~也许是我遗漏了什么~！感谢指教~！

**Comment by wxhnizy** [comment]
@JohnFreeman9 我实在是看不出我的权限设置有什么问题，可以帮我看下吗》？执行权限ROOT 
![Uploading QQ截图20160926184102.png…]()

**Comment by wxhnizy** [comment]
@JohnFreeman9 权限均为root ，执行权限也是root？

**Comment by glzjin** [comment]
@wxhnizy 你后端的node id填的是几？

**Comment by wxhnizy** [comment]
@glzjin  

NODE_ID = 1

**Comment by glzjin** [comment]
@wxhnizy 你填错了，你添加这个节点id是几就是几

**Comment by wxhnizy** [comment]
@glzjin ？那我以后添加节点的时候 也需要修改这里吗？

**Comment by wxhnizy** [comment]
@glzjin 我的节点 ID为3 那以后我在添加节点的时候 4，5，6，7，8，那还需要去修改这里的ID数值？

**Comment by glzjin** [comment]
@wxhnizy 废话

**Comment by wxhnizy** [comment]
@glzjin 但是我的节点显示是正常啊？但是客户端日志里依然显示 错误信息 
[2016-09-26 18:57:08] System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.SocketUtil.EndConnectTcp(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

![l _l4vs 3 ak7 b8o 42n4](https://cloud.githubusercontent.com/assets/21986327/18831954/46ef5d6c-841b-11e6-9ffc-e62c445af939.png)

**Comment by Jouaoo** [comment]
来来来3000包精通

**Comment by xiao201261** [comment]
@wxhnizy 你可以去Google下 tcping 这个东西呢 看看端口通不通再来说话 谢谢 :)

**Comment by wxhnizy** [comment]
@Jouaoo 我承认我的技术欠缺很多，感谢你的提醒，费用的话 我宁愿赞助到本站。感谢你的好意

**Comment by hmachine1999** [comment]
@wxhnizy test

**Comment by xiecuyu** [comment]
后端服务器防火墙关了吗？
