### ISSUE TITLE
全新安装出现的问题

### ISSUE THREAD

**Issue by muaty** [glzjin/ss-panel-v3-mod#24]
其他页面都正常，不过注册不了， 也登录不了，邀请码页面错误、

![111](https://cloud.githubusercontent.com/assets/16643478/15080622/b07bddb8-13f1-11e6-8dca-dd6e780e906b.png)

**Comment by glzjin** [comment]
请在 config/.config.php debug 设置为 true，将错误信息贴上来

**Comment by glzjin** [comment]
目测你是没给 storage权限

**Comment by 619096932** [comment]
对哦 ！你这问题我上次遇到了！  重新安装就没问题了 漏了一步吧

**Comment by glzjin** [comment]
chown -R www:www storage
chmod -R 600 storage
glzjin
2016年5月7日 上午1:32，619096932 <notifications@github.com>写道：对哦 ！你这问题我上次遇到了！  重新安装就没问题了 漏了一步吧

**Comment by muaty** [comment]
问题解决 并不是权限的问题 是因为数据库信息没写正确。
邀请码怎么获取呢？页面可以打开了。

**Comment by glzjin** [comment]
后台 邀请

**Comment by muaty** [comment]
昨晚到现在你还没睡呢？  怎么进入后台的- -  不是说要注册账号吗！

**Comment by glzjin** [comment]
你好好看看说明吧。。。
glzjin
2016年5月7日 上午9:24，muaty <notifications@github.com>写道：昨晚到现在你还没睡呢？  怎么进入后台的- -  不是说要注册账号吗！

**Comment by muaty** [comment]
坚决不当睁眼瞎 这种弱智问题- -
我成功安装好了，但是工单系统可能是新添加的吧？建议提交工单的时候加一个验证码，不然不知不觉就添加了好多条工单了，或者是最好是前一个工单在客服未关闭之前用户不能提交第二个工单。
管理员最好可以在后台选择删除工单。

不知道现在设置邮箱之后，用户发送过来的新工单会不会邮件提醒。

**Comment by glzjin** [comment]
欢迎你添加了来提交一个pull request
glzjin
2016年5月7日 上午9:43，muaty <notifications@github.com>写道：坚决不当睁眼瞎 这种弱智问题- -
我成功安装好了，但是工单系统可能是新添加的吧？建议提交工单的时候加一个验证码，不然不知不觉就添加了好多条工单了，或者是最好是前一个工单在客服未关闭之前用户不能提交第二个工单。
管理员最好可以在后台选择删除工单。

不知道现在设置邮箱之后，用户发送过来的新工单会不会邮件提醒。

**Comment by muaty** [comment]
中转套件的教程搬来了吗？

**Comment by glzjin** [comment]
没
glzjin
2016年5月7日 上午11:07，muaty <notifications@github.com>写道：中转套件的教程搬来了吗？

**Comment by muaty** [comment]
qwq  求中转套件教程

**Comment by glzjin** [comment]
请问您是捐赠用户吗？捐赠用户那一篇应该没删。
glzjin
2016年5月7日 上午11:10，muaty <notifications@github.com>写道：qwq  求中转套件教程

**Comment by muaty** [comment]
非常乐意捐赠

**Comment by muaty** [comment]
是在博客里吗？？

**Comment by glzjin** [comment]
是的
glzjin
2016年5月7日 上午11:37，muaty <notifications@github.com>写道：是在博客里吗？？

**Comment by lion1991** [comment]
最近捐赠的能否查看中转套件教程.在博客中没有找到相关说明呀
