### ISSUE TITLE
php xcat checkjob 不正常工作

### ISSUE THREAD

**Issue by hanbing151400** [glzjin/ss-panel-v3-mod#240]
计划任务添加了。保证路径正确。直接在网站根目录下执行 php xcat checkjob 后 没有任何提示 等级过期的用户依然维持在原等级。不知为何。求大佬予以帮助

**Comment by hanbing151400** [comment]
php禁用函数已经调整为
disable_functions = passthru,exec,chroot,chgrp,chown,shell_exec,proc_open,proc_get_status,popen,ini_alter,ini_restore,dl,openlog,syslog,readlink,symlink,popepassthru,stream_socket_server

经过测试 当已用流量超过总流量 后 用户是无法正常使用的  那应该能证明计划任务填写的是没问题的吧，而且节点出现断线的时候 节点列表也能显示红色叹号

**Comment by hanbing151400** [comment]
又经测试。手动修改账户到期日期为当前时间之前，用户将无法正常使用 
等级到期流量依然不重置，用户依然能正常使用，账户到期后流量也不重置，但用户无法正常使用 
.config.php 部分配置信息如下

#等级到期时是否重置流量
$System_Config['enable_class_expire_reset']='true';

#等级到期时重置为的流量值，GB
$System_Config['enable_class_expire_reset_traffic']='0';

#账户到期时是否重置流量
$System_Config['enable_account_expire_reset']='true';

#账户到期时重置为的流量值，GB
$System_Config['enable_account_expire_reset_traffic']='0';

#购买时是否重置流量
$System_Config['enable_bought_reset']='true';

#账户到期之后是否会删除账户
$System_Config['enable_account_expire_delete']='true';

#账户到期几天之后会删除账户
$System_Config['enable_account_expire_delete_days']='7';

#功能开关
$System_Config['enable_wecenter']='false';
$System_Config['enable_radius']='false';
$System_Config['enable_cloudxns']='false';
$System_Config['enable_duoshuo']='false';
$System_Config['enable_rss']='true';
$System_Config['enable_paymentwall']='false';

**Comment by wabcwell** [comment]
我的流量什么的也不重置

**Comment by dnsml** [comment]
断开vpn 重新练应该就不行了吧

**Comment by wabcwell** [comment]
30 22 * * * php /home/wwwroot/sss/xcat sendDiaryMail
*/1 * * * * php /home/wwwroot/sss/xcat synclogin
*/1 * * * * php /home/wwwroot/sss/xcat syncvpn
0 0 * * * php -n /home/wwwroot/sss/xcat dailyjob
*/1 * * * * php /home/wwwroot/sss/xcat checkjob    
*/1 * * * * php -n /home/wwwroot/sss/xcat syncnas

除了第一条命令，其他的命令我都手动执行了。但是好像没啥效果

**Comment by WhoRUa** [comment]
陷入了窘境

**Comment by glzjin** [comment]
@WhoRUa Zhao Jin | 更好的自己 | 微笑 | 过膝袜狂热爱好者 | 短发控:
已探明原因，感谢反馈，之后会进行修复。
