### ISSUE TITLE
mailgun有时候发不出去邮件

### ISSUE THREAD

**Issue by ctrlbbj** [glzjin/ss-panel-v3-mod#244]
用户注册时点击发送邮件，mailgun处日志没有显示邮件发送记录
以下是执行 dailyjob 发送备份邮件时显示的错误信息
Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 35:  [url] https://api.mailgun.net/v2/web.site/messages' in /home/wwwroot/website/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:359
Stack trace:
#0 /home/wwwroot/website/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /home/wwwroot/website/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /home/wwwroot/website/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 /home/wwwroot/website/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
#4 /home/wwwroot/website/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti in /home/wwwroot/website/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php on line 359

**Comment by glzjin** [comment]
那就是抽了= =
