### ISSUE TITLE
能否加入成长值系统?

### ISSUE THREAD

**Issue by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [glzjin/ss-panel-v3-mod#245]
类似QQVIP成长体系

**Comment by glzjin** [comment]
@mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls 等着全新的面板

**Comment by glzjin** [comment]
@mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls https://docs.google.com/forms/d/e/1FAIpQLSdQ1EJIcf12vru_RnkpYvxPgiLYWowZ-1vm3pr-t8_M-AHESw/viewform?c=0&w=1
