### ISSUE TITLE
关于用户级别过期的处理

### ISSUE THREAD

**Issue by sephrioth** [glzjin/ss-panel-v3-mod#246]
现在有这样一个需求.

用户A的当前级别是 1, 两个月后级别到期.  A现在购买了级别 2 的体验服务 3 天, 但是现在的问题是3天过后, 用户的级别会被重置为 0 , 而不是退回到之前的 1 . 
能否将级别过期后重置为用户之前的级别, 而不是全部重置为 0 ?

**Comment by Cnievana** [comment]
当前的数据库并没有剩余字段可以记录原先级别，无法重置为用户之前的级别
如果你有二次开发能力，可以尝试新增数据表(或字段)存储原先级别，并在用户购买商品时判断是否需要存储
如果没有二次开发能力，此问题适用范围不广，并可通过新开账户/待原账户等级过期后再购买 的方式解决，此功能加入到面板的等待时间可能会较长

**Comment by sephrioth** [comment]
其实主要是想让用户临时体验下级别2 , 新开账户或者等等级过期这个似乎不是特别好的办法... 但是看起来也没办法了.   还有一个方式就是添加的商品可以增加修改组别的属性.. 看起来也能达到类似的效果.

**Comment by sephrioth** [comment]
想了想还是不行, 不仅要记住用户之前的级别, 还得记住之前级别的过期日.... 哎....

**Comment by glzjin** [comment]
@sephrioth 等新面板吧

**Comment by sephrioth** [comment]
多谢老大回复..  不过现在的面板做了很多个性化的东西, 新面板估计有的调了...

**Comment by glzjin** [comment]
@sephrioth 新面板会更加方便你们定制的=、=设计目标

**Comment by sephrioth** [comment]
希望, 希望, 哈哈哈, 新面板大概什么时候可以出来呢?

**Comment by glzjin** [comment]
@sephrioth 无可奉告
