### ISSUE TITLE
新的节点ss后台显示这个问题，同时无法连接ss

### ISSUE THREAD

**Issue by terryops** [glzjin/ss-panel-v3-mod#251]
2016-09-29 18:59:59 INFO     server_pool.py:225 starting server at 0.0.0.0:10179
2016-09-29 18:59:59 WARNING  server_pool.py:237 IPV4 obfs plugin [tls1.0_session_auth_compatible] not supported

**Comment by JohnFreeman9** [comment]
@terryops TLS1.0早就不受支持了，你连得上才有鬼

**Comment by terryops** [comment]
@JohnFreeman9 但是旧的服务器可以连上。后端程序版本是一样的。

**Comment by JohnFreeman9** [comment]
@terryops 那你就用你的旧后端吧（微笑

**Comment by terryops** [comment]
不对啊，后端版本应该是一样的。我开了个新节点而已。
总之我希望能连上原版ss，请问有解决方案吗？

**Comment by JohnFreeman9** [comment]
@terryops 使用新协议，并选择兼容选项。但是原作者已经明确指出该方法存在被探测风险，并建议关闭兼容选项，如此操作请风险自负。

**Comment by terryops** [comment]
point is：同一个帐号和设置，两个节点，后端程序都是一样的。但是在A节点可以使用SS，但是在B就用不了，非常不解。
在后台看到的日志就是上面写的。

**Comment by ctrlbbj** [comment]
@terryops 肯定后端版本不一样，找旧的用吧

**Comment by glzjin** [comment]
这个已经不被支持，请更换其他为其他参数选项。
