### ISSUE TITLE
用户更改节点加密方式错误

### ISSUE THREAD

**Issue by e8732** [glzjin/ss-panel-v3-mod#253]
例如：网站默认加密为aes-256-cfb，用户登录后修改为chacha20。
但通过节点列表中看到的信息，加密方式仍为aes-256-cfb

**Comment by YancyLeeQAQ** [comment]
@e8732 因为你没开自定义加密

**Comment by e8732** [comment]
@YancyLeeQAQ 从哪里开呢？配置文件吗？
