### ISSUE TITLE
用戶資料頁更改混淆協議無效

### ISSUE THREAD

**Issue by A1exLiu** [glzjin/ss-panel-v3-mod#258]
有一個用戶用的是iOS，不支持混淆，我就讓他在用戶資料修改頁面更改了混淆協議為origin和plain，但是在log裡面仍然顯示的是auth_sha1_v2和tls1.2，請問如何解決

**Comment by A1exLiu** [comment]
追加，剛才在pma上看了一眼，用戶資料頁上面的更改根本沒有應用到數據庫當中

**Comment by glzjin** [comment]
你确定用户修改成功了吗？

**Comment by A1exLiu** [comment]
@glzjin 他跟我說是修改成功了，等我開個用戶試一下

**Comment by A1exLiu** [comment]
確定是用戶修改問題，自測修改有效，麻煩趙總了
