### ISSUE TITLE
用户群组的问题

### ISSUE THREAD

**Issue by fakehaoyang** [glzjin/ss-panel-v3-mod#26]
是不是现在如果用户群组设为8，用户看不到群组为0的节点。（我试了下😂

**Comment by glzjin** [comment]
此类问题以后请自行研究，不要在这里问了。
glzjin
2016年5月7日 下午3:14，fakehaoyang <notifications@github.com>写道：是不是现在如果用户群组设为8，用户看不到群组为0的节点。（我试了下😂

**Comment by fakehaoyang** [comment]
真的控制不了…群组为1的用户看不到群组为0的节点，也能访问群组为2的节点…也在别的vps上搭建魔改面板测试了

**Comment by glzjin** [comment]
你用的是Python的后端？还是mu的MySQL？
glzjin
2016年5月7日 下午10:58，fakehaoyang <notifications@github.com>写道：真的控制不了…群组为1的用户看不到群组为0的节点，也能访问群组为2的节点…也在别的vps上搭建魔改面板测试了

**Comment by glzjin** [comment]
还有你的版本号是？

**Comment by 1205405056** [comment]
是ssshell，用的被D之前的版本，我那段时间安得，新教程装不上，所以用的旧的。最近我再试试新的
