### ISSUE TITLE
已用流量一直都是0.其他都正常的.这是什么问题

### ISSUE THREAD

**Issue by rt9rt9** [glzjin/ss-panel-v3-mod#260]
已用流量一直都是0.其他都正常的.这是什么问题

**Comment by rt9rt9** [comment]
![33444](https://cloud.githubusercontent.com/assets/22344831/19015138/f3be85c2-8830-11e6-93c1-2a86ec0278b2.jpg)
安装环境lnmp1.3
php7.0.7
mysql5.5
crontab -e 任务正常
php.ini
disable_functions =passthru,exec,chroot,chgrp,chown,shell_exec,proc_open,proc_get_status,popen,ini_alter,ini_restore,dl,openlog,syslog,readlink,symlink,popepassthru,stream_socket_server

**Comment by glzjin** [comment]
crontab -l 输出结果发一下？

**Comment by rt9rt9** [comment]
![44555](https://cloud.githubusercontent.com/assets/22344831/19020447/baa4a1a8-88db-11e6-8849-1549600c1ff0.jpg)
这是crontab -l输出的结果截图....

**Comment by glzjin** [comment]
@rt9rt9 你运行checkjob那个结果呢

**Comment by rt9rt9** [comment]
@glzjin 不是很明白你说的运行checkjob如何操作.请赐教..

**Comment by glzjin** [comment]
@rt9rt9 php ...xcat checkjob

**Comment by rt9rt9** [comment]
![54555](https://cloud.githubusercontent.com/assets/22344831/19020501/1b1e102c-88dd-11e6-9cdc-2803395ca9ed.jpg)

**Comment by rt9rt9** [comment]
运行后已经可以显示已用流量了....

**Comment by glzjin** [comment]
@rt9rt9 那就得了=、=自己检查crontab在不在运行

**Comment by rt9rt9** [comment]
好的.3Q
