### ISSUE TITLE
mysql密码EROOR？

### ISSUE THREAD

**Issue by nch14** [glzjin/ss-panel-v3-mod#261]
超级尴尬。遇到的问题是在lnmp vhost add这一步中mysql密码显示错误。
我超级确信我使用了第一步设置的密码。然后退出以后、那个密码确实无法登入mysql。
于是我重置了密码。确认可以使用后再一次lnmp vhost add……再次密码错误。尴尬。
求解QAQ。

**Comment by YancyLeeQAQ** [comment]
@nch14 请把你设置的密码复制一份  需要密码的时候复制了用
