### ISSUE TITLE
每日流量报告怎么设置成默认关闭呢？

### ISSUE THREAD

**Issue by e8732** [glzjin/ss-panel-v3-mod#264]
使用的企业邮箱smtp，因为每天发送此类邮件，已经被很多邮箱系统加入黑名单了。
想用户注册时默认关闭这个功能，如何实现呢？

**Comment by Jouaoo** [comment]
自己改数据库，user表，哪个字段忘了…自己找找！

**Comment by e8732** [comment]
@Jouaoo 目前就是用的这种方法，每天都有用户注册，每天都在批量的改。

**Comment by Jouaoo** [comment]
把字段默认值从1改成0
