### ISSUE TITLE
用户等级有效期时间已过，用户等级没变

### ISSUE THREAD

**Issue by WhoRUa** [glzjin/ss-panel-v3-mod#265]
1
用户级别（用户只能访问到等级小于等于这个数字的节点）
4
用户等级过期时间(不过期就请不要动)
2016-09-29 20:25:23
用户账户过期时间(不过期就请不要动)

按说用户等级到期后用户等级会降吧？到今天用户等级都还是4，为什么？

**Comment by glzjin** [comment]
@WhoRUa 请尝试新版本。

**Comment by WhoRUa** [comment]
等级到期时是否重置流量
$System_Config['enable_class_expire_reset']='true';

#等级到期时重置为的流量值，GB
$System_Config['enable_class_expire_reset_traffic']='50';

#账户到期时是否重置流量
$System_Config['enable_account_expire_reset']='true';

#账户到期时重置为的流量值，GB
$System_Config['enable_account_expire_reset_traffic']='0';

#购买时是否重置流量
$System_Config['enable_bought_reset']='true';

#账户到期之后是否会删除账户
$System_Config['enable_account_expire_delete']='true';


这样设置不会有什么问题吧，我git安装，又git pull更新，而等级过期的用户仍然不降级

**Comment by glzjin** [comment]
@WhoRUa 检查你的计划任务运行情况—.—checkjob那个

**Comment by Jouaoo** [comment]
更新一下，新的很猛

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
更新到dev版本，打开job.php

找到
if($user->class!=0 && $user->transfer_enable != Tools::toGB(Config::get('enable_class_expire_reset_traffic')) && strtotime($user->class_expire)<time() && $user->class_expire > 1420041600)

替换成

if(strtotime($user->class_expire)<=time() && $user->transfer_enable != Tools::toGB(Config::get('enable_class_expire_reset_traffic')))

**Comment by glzjin** [comment]
@mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls 请问你真明白这个语句是什么意思吗？

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
@glzjin   不明白 不过至少可以等级会动了   不会像原来那样毫无反应了

**Comment by glzjin** [comment]
@mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls 你这样是害了别人。。。=、=本来就不应该处理那些不需要处理的东西

**Comment by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [comment]
@glzjin   好吧  那我删掉吧   我自己用着先  看看会有什么问题 -。-

**Comment by WhoRUa** [comment]
手动执行 php /data/wwwroot/www.utemp.top/xcat checkjob 可以，但是crond自动执行后没反应。以下是cron log --
Oct  4 16:43:01 iZ28if57pdiZ CROND[8464]: (root) CMD (php /data/wwwroot/www.utemp.top/xcat synclogin)
Oct  4 16:43:01 iZ28if57pdiZ CROND[8466]: (root) CMD (php -n /data/wwwroot/www.utemp.top/xcat syncnas)
Oct  4 16:43:01 iZ28if57pdiZ CROND[8465]: (root) CMD (php /data/wwwroot/www.utemp.top/xcat checkjob    )
Oct  4 16:43:01 iZ28if57pdiZ CROND[8467]: (root) CMD (php /data/wwwroot/www.utemp.top/xcat syncvpn)

**Comment by WhoRUa** [comment]
刚刚更新完，现在手动 php /data/wwwroot/www.utemp.top/xcat checkjob 也没反应了。。

**Comment by glzjin** [comment]
@WhoRUa 正常 没反应的

**Comment by WhoRUa** [comment]
哦，可是用户等级过期了，用户级别不自动降下来怎么办？

**Comment by glzjin** [comment]
@WhoRUa 比如？

**Comment by WhoRUa** [comment]
用户级别（用户只能访问到等级小于等于这个数字的节点）
4
用户等级过期时间(不过期就请不要动)
2016-10-04 16:37:36
用户账户过期时间(不过期就请不要动)

显然用户等级已经过期了，但是用户等级依然为4

**Comment by glzjin** [comment]
@WhoRUa 你手动运行的截图给我看看？checkjob
