### ISSUE TITLE
用户连接密码可修改为中文

### ISSUE THREAD

**Issue by FuaerCN** [glzjin/ss-panel-v3-mod#266]
![111](https://cloud.githubusercontent.com/assets/13153883/19019654/62e5996e-88c1-11e6-835a-b23d98d8dfc0.png)
ss的连接密码不支持非ascii字符，导致启动报错
![222](https://cloud.githubusercontent.com/assets/13153883/19019661/a4b822c6-88c1-11e6-9e5b-9d1433b0175e.png)

**Comment by glzjin** [comment]
下一个lts版本修吧=、、

**Comment by glzjin** [comment]
已更新。

**Comment by FuaerCN** [comment]
@glzjin 幸苦了
