### ISSUE TITLE
php xcat checkjob 相关问题

### ISSUE THREAD

**Issue by hanbing151400** [glzjin/ss-panel-v3-mod#268]
执行php xcat checkjob出现
PHP Notice:  Undefined variable: shop in /home/wwwroot/马赛克/app/Command/Job.php on line 374
PHP Notice:  Trying to get property of non-object in /home/wwwroot/马赛克/app/Command/Job.php on line 374
不太理解是什么导致的这个问题

**Comment by glzjin** [comment]
请不要尝试在数据库中删除商品。
