### ISSUE TITLE
更新后使用smtp无法发送邮件了。

### ISSUE THREAD

**Issue by halo1094** [glzjin/ss-panel-v3-mod#269]
如题。
另我config smtp是这样填写的。
$System_Config['smtp_host'] = 'smtp.mxhichina.com';
$System_Config['smtp_username'] = '发件邮箱';
$System_Config['smtp_port'] = '25';
$System_Config['smtp_name'] = '发件邮箱';
$System_Config['smtp_sender'] = '发件邮箱;
$System_Config['smtp_passsword'] = '密码';
$System_Config['smtp_ssl'] = 'flase';
更新之前可以发送的。更新后无法发送了。是哪里出错了吗。求指点

**Comment by glzjin** [comment]
@halo1094 无解 那部分没有动过，你自己想办法检查吧，

**Comment by mischief1** [comment]
解决了吗？我也是同样问题
