### ISSUE TITLE
更新后管理面板多项功能无法使用

### ISSUE THREAD

**Issue by salty1** [glzjin/ss-panel-v3-mod#272]
用户无法删除,用户无法编辑
商店无法下架/编辑

全新安装过(没换库),还是不行
可以注册新用户,应该排除数据库权限问题

**Comment by glzjin** [comment]
@salty1 请开debug之后对这几个错误操作f12抓包。

**Comment by salty1** [comment]
额,不太会,需要什么信息? 我是corme

**Comment by salty1** [comment]
解决了,破CDN的错,感谢
