### ISSUE TITLE
如何增加购买数量?

### ISSUE THREAD

**Issue by mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls** [glzjin/ss-panel-v3-mod#274]
比如按天计算, 可以让用户自定义购买多少天,  类似多少件商品数量,  顺便加个库存显示

**Comment by glzjin** [comment]
@mS0gxokXEsg5ysJ7J79kzWiqO1fHgFA6ZR8eEls 请等待新面板
