### ISSUE TITLE
用户连续购买商店同等级商品时有效期不会重新计算

### ISSUE THREAD

**Issue by 18664155883** [glzjin/ss-panel-v3-mod#278]
赵老师你好，经过一段时间的使用，发现当用户连续购买商店同一个等级商品时，有效期不会从当前时间重新计算，而是直接叠加有效期，但购买不同等级的商品会重新开始计算有效期，这问题可以修复吗？

**Comment by YancyLeeQAQ** [comment]
@18664155883 你想怎么修复

**Comment by glzjin** [comment]
@18664155883 你好，这个是资源叠加。并不是问题。

**Comment by 18664155883** [comment]
好的，谢谢解答疑问。
