### ISSUE TITLE
登录页面

### ISSUE THREAD

**Issue by leosejin** [glzjin/ss-panel-v3-mod#279]
登录后提示欢迎，然后马上又会跳转回登录页面。。。

**Comment by glzjin** [comment]
@leosejin 开了CDN 就把real IP模块配置好

**Comment by leosejin** [comment]
辅导员，那个在哪儿啊....找了半个小时了都没找到(>﹏<。)～呜呜呜……

**Comment by glzjin** [comment]
@leosejin .config.php
