### ISSUE TITLE
搭建好发现的问题

### ISSUE THREAD

**Issue by dnsml** [glzjin/ss-panel-v3-mod#282]
点登陆没有提示
![qq 20161005130343](https://cloud.githubusercontent.com/assets/22525919/19101609/4331e48c-8afc-11e6-9384-09147a903e27.png)
![qq 20161005130339](https://cloud.githubusercontent.com/assets/22525919/19101610/454cf20c-8afc-11e6-9df4-ded19e6a4ddf.png)

![qq 20161005130351](https://cloud.githubusercontent.com/assets/22525919/19101621/55b2f1f0-8afc-11e6-9dc6-8bc093e9664d.png)
@glzjin

**Comment by Jouaoo** [comment]
长相问题

**Comment by A1exLiu** [comment]
人品问题

**Comment by glzjin** [comment]
请开启 debug 后 f12 抓包。

**Comment by xiecuyu** [comment]
500错误就我的经验通常都是数据库的锅。。。

**Comment by xiecuyu** [comment]
检查下数据库设置是否正确。。以及3306端口开放没有。。
