### ISSUE TITLE
后端问题:Connection reset by peer

### ISSUE THREAD

**Issue by bluekk935** [glzjin/ss-panel-v3-mod#285]
不间断的 随机性 出现类似下面的错误
ERROR    tcprelay.py:969 [Errno 104] Connection reset by peer
ERROR    tcprelay.py:971 when connect to X.X.X.X:443 from ::ffffX.X.X.X:45873 via port 23333
同时挂着ss玩着游戏 打完boss了 分装备了 掉线了~~~~
端口是正常 非137这种
客户端为梅林小宝改版
加密为chacha20
协议为auth_sha1
混淆为tls1.2_ticket_auth
混淆参数为baidu.com
服务器参数为
加密为chacha20
协议为auth_sha1_compatible
混淆为tls1.2_ticket_auth_compatible
混淆参数没填

同时查看了后端机器
ulimit -n    提示为65535 
 cat /proc/sys/fs/file-max   提示为101474
求大佬解惑

**Comment by glzjin** [comment]
@bluekk935 这届服务器网络不行

**Comment by bluekk935** [comment]
阿里香港B的服务器已经烂到这个地步了?😂

**Comment by glzjin** [comment]
@bluekk935 你才知道=、=？

**Comment by bluekk935** [comment]
好吧 垃圾马云 骗我钱财 毁我青春
