### ISSUE TITLE
能不能把速度改成节点限速和端口限速的最低值

### ISSUE THREAD

**Issue by 85204** [glzjin/ss-panel-v3-mod#287]
看你之前的帖子说到速度是节点限速和端口限速的最高值
这样的话对某些低延迟小带宽节点非常不利
我的站点：duguletian.com

**Comment by 85204** [comment]
换言之如果对于此类节点不限速能否保证每个用户的使用质量？

**Comment by Woophp** [comment]
最低就不叫限速，叫保障…
我想问问你怎么保障？带宽就10M，11个人同时用你怎么保障？

**Comment by 85204** [comment]
限速值是取节点限速和端口限速的最低值
如果用户端口不限速，节点怎么限速都无效

**Comment by glzjin** [comment]
@85204 不是，你对节点设置节点限速即可。只要开了多线程。

**Comment by YancyLeeQAQ** [comment]
@85204 谁说无效的，节点限速多少所有用户就是多少

**Comment by Woophp** [comment]
@85204最高值说的是峰值，不是两个限速值对比你懂吗？你以为的只是你自己以为的而已，自己试试先…

**Comment by YancyLeeQAQ** [comment]
@Woophp 你看过源代码吗

**Comment by Woophp** [comment]
@YancyLeeQAQ 我错了？好吧我什么都没说

**Comment by Woophp** [comment]
@YancyLeeQAQ 难道节点限2M，用户限10M，你能在这个节点跑出10M?

**Comment by YancyLeeQAQ** [comment]
@Woophp 不能

**Comment by Woophp** [comment]
@YancyLeeQAQ 额…那我哪里说错了？

**Comment by 85204** [comment]
@glzjin https://github.com/glzjin/ss-panel-v3-mod/issues/92
你的原话在最后一楼，可能当时是笔误，最好修正一下以免引起误会。。。

**Comment by glzjin** [comment]
@85204 并没有错 那个是指的是你同时设置时是那样
