### ISSUE TITLE
从问答进入wecenter可以自动登陆但是手动登陆密码错误

### ISSUE THREAD

**Issue by xiadena** [glzjin/ss-panel-v3-mod#29]
看数据库是会修改掉密码的，而且不知道是什么密。这样的话管理员就无法登陆后台了啊，有没有解决办法

**Comment by glzjin** [comment]
sspanel的密码
glzjin
2016年5月8日 下午7:35，xiadena <notifications@github.com>写道：看数据库是会修改掉密码的，而且不知道是什么密。这样的话管理员就无法登陆后台了啊，有没有解决办法

**Comment by xiadena** [comment]
已解决，wecenter的salt只能到15位字符。而我sspanel的salt超过了15位。。。
