### ISSUE TITLE
计划任务执行失败，手动执行也是显示失败，赵老师能否指点一下？

### ISSUE THREAD

**Issue by 18664155883** [glzjin/ss-panel-v3-mod#292]
执行报错如下：
[root@vultr ss]# php xcat checkjob
PHP Fatal error:  Uncaught exception 'Mailgun\Connection\Exceptions\MissingEndpoint' with message 'The endpoint you've tried to access does not exist. Check your URL.' in /home/wwwroot/ss/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:134
Stack trace:
#0 /home/wwwroot/ss/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /home/wwwroot/ss/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\Connection\RestClient->post('/messages', Array, Array)
#2 /home/wwwroot/ss/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\Mailgun->post('/messages', Array, Array)
#3 /home/wwwroot/ss/app/Services/Mail/Mailgun.php(41): Mailgun\Mailgun->sendMessage('', Array, Array)
#4 /home/wwwroot/ss/app/Services/Mail.php(66): App\Services\Mail\Mailgun->send('891516981@qq.co...', '\xE4\xBA\x91\xE9\x9C\x84\xE9\x98\x81-\xE6\x82\xA8\xE7\x9A...', '<!DOCTYPE html ...', Array)
#5 /home/wwwroot/ss/app/Command/Job.p in /home/wwwroot/ss/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 134
[root@vultr ss]#

**Comment by 18664155883** [comment]
[root@vultr ss]# php xcat dailyjob
PHP Warning:  mkdir(): File exists in /home/wwwroot/ss/app/Command/Job.php on line 46
PHP Notice:  Undefined variable: ret in /home/wwwroot/ss/app/Command/Job.php on line 48
PHP Warning:  system() has been disabled for security reasons in /home/wwwroot/ss/app/Command/Job.php on line 48
PHP Notice:  Undefined variable: ret in /home/wwwroot/ss/app/Command/Job.php on line 51
PHP Warning:  system() has been disabled for security reasons in /home/wwwroot/ss/app/Command/Job.php on line 51
PHP Notice:  Undefined variable: ret in /home/wwwroot/ss/app/Command/Job.php on line 63
PHP Warning:  system() has been disabled for security reasons in /home/wwwroot/ss/app/Command/Job.php on line 63
PHP Notice:  Undefined variable: ret in /home/wwwroot/ss/app/Command/Job.php on line 64
PHP Warning:  system() has been disabled for security reasons in /home/wwwroot/ss/app/Command/Job.php on line 64
PHP Fatal error:  Uncaught exception 'Mailgun\Connection\Exceptions\MissingEndpoint' with message 'The endpoint you've tried to access does not exist. Check your URL.' in /home/wwwroot/ss/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:134
Stack trace:
#0 /home/wwwroot/ss/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /home/wwwroot/ss/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\Connection\RestClient->post('/messages', Array, Array)
#2 /home/wwwroot/ss/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\Mailgun->post('/messages', Array, Array)
#3 /home/wwwroot/ss/app/Services/Mail/Mailgun.php(41): Mailgun\Mailgun->sendMessage('', Array, Array)
#4 /home/wwwroot/ss/app/Services/Mail.php(66): App\Services\Mail\Mailgun->send('china.ntp@gmail...', '\xE4\xBA\x91\xE9\x9C\x84\xE9\x98\x81-\xE5\xA4\x87\xE4\xBB...', '<!DOCTYPE html ...', Array)
#5 /home/wwwroot/ss/app/Command/Job.p in /home/wwwroot/ss/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 134
[root@vultr ss]#

**Comment by lovingfrank** [comment]
@18664155883 提示什么就谷歌搜索什么啊

**Comment by ctrlbbj** [comment]
@18664155883 php有函数被禁用

**Comment by glzjin** [comment]
@18664155883 请解禁php函数

**Comment by 18664155883** [comment]
谢谢，确实是PHP函数被禁用。
目前遇到一个新问题，使用smtp方式发送邮件，却发不出邮件，config.php已按要求设置好了，发件邮箱用的是163邮箱，能帮忙解答一下吗

**Comment by ctrlbbj** [comment]
@18664155883 日志，配置开debug，慢慢调

**Comment by 18664155883** [comment]
谢谢，已找到问题所在，服务器运营商屏蔽25端口，使用SSL无问题
