### ISSUE TITLE
2.更新后用户等级还是无法自动过期

### ISSUE THREAD

**Issue by leosejin** [glzjin/ss-panel-v3-mod#294]
辅导员好，
面板是在本月4号中午左右安装的，您是在4号8点发布了更新的通知，内容是更新修复了用户等级无法自动更新的问题。
其实这个等级过期的问题 我在前面的好多次测试当中一直都是这样，4号安装好之后 在6号我进行了更新
我是git clone安装的
前端：cd /home/wwwroot/www. xx. xx
            git pull
提示了更新的信息。
后端：cd shadowsocks
            git pull
提示了更新的信息。
之后我重启后端，注册了一个新的账号，购买等级为1的商品为期一天，到第二天7号等级时间到期后，账号等级依然为1，数据库中等级也是1，节点也依旧可以用，流量也会正常记录，.config上设置的等级到期重置流量没有重置，每日使用流量显示不是每日的使用，而是从开始到现在一直在使用的记录量。
在手动修改等级后连接不可用。
打开debug后点击 用户信息 会报错，已经复制到上一个issue中。
crontab运行日志也在上一个issue中。
前端安装环境 LNMP

**Comment by ctrlbbj** [comment]
@leosejin 看cron日志，并没有执行计划任务，请检查crond服务运行状态services crond status 以及chkconfig信息

**Comment by leosejin** [comment]
哦 对的，crond确实没有在运行，我打开之后cron有日志记录了。
我再测试一下看能不能自动降下来。

**Comment by xiecuyu** [comment]
执行php xcat checkjob了吗？

**Comment by glzjin** [comment]
请确定你的crontab在正常运行，并且 checkjob 执行无错误。

**Comment by leosejin** [comment]
crond的锅。谢谢辅导员

**Comment by glzjin** [comment]
@leosejin 好的
