### ISSUE TITLE
我发誓我没动过 staff.tpl文件

### ISSUE THREAD

**Issue by wabcwell** [glzjin/ss-panel-v3-mod#296]
[root@IcyDarkmagenta-VM sss]# git checkout spay
error: You have local changes to 'resources/views/material/staff.tpl'; cannot switch branches.

**Comment by glzjin** [comment]
@wabcwell git reset --hard

**Comment by wabcwell** [comment]
git checkout spay 后还需要git pull么？

**Comment by wabcwell** [comment]
@glzjin git checkout spay 后还需要git pull么？我是萌新求带

**Comment by glzjin** [comment]
@wabcwell 不用
