### ISSUE TITLE
Spay点击充值之后500错误

### ISSUE THREAD

**Issue by wabcwell** [glzjin/ss-panel-v3-mod#297]
我看之前的朋友的问题，但是我换行了啊。
所以比较纠结。
alipay_id和alipay_key均已填写。

**Comment by glzjin** [comment]
@wabcwell 对此模块不提供任何支持。

**Comment by wxliuxh** [comment]
spay经常被打.付款的那个界面经常500.习惯就好.多刷新几次或者等一会再试
