### ISSUE TITLE
Interface 'JsonSerializable' not found

### ISSUE THREAD

**Issue by jimorsm** [glzjin/ss-panel-v3-mod#298]
大佬们，执行计划任务的时候报错，网上找了一圈说是json模组没装，可是装了还是一样啊。哪位大佬知道这个解决方案？

From root@*.localdomain  Sun Oct  9 07:31:01 2016
Return-Path: <root@*.localdomain>
X-Original-To: root
Delivered-To: root@*.localdomain
Received: by *.localdomain (Postfix, from userid 0)
	id CF8611CDA; Sun,  9 Oct 2016 07:31:01 +0800 (CST)
From: "(Cron Daemon)" <root@*.localdomain>
To: root@*.localdomain
Subject: Cron <root@*> php -n /var/www/*/xcat syncnas
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=463>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/bash>
X-Cron-Env: <PATH=/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <MAILTO=root>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Message-Id: <20161008233101.CF8611CDA@*.localdomain>
Date: Sun,  9 Oct 2016 07:31:01 +0800 (CST)
Fatal error: Interface 'JsonSerializable' not found in /var/www/*/vendor/illuminate/support/Fluent.php on line 11

`➜  ~ php -v
PHP 5.6.26 (cli) (built: Sep 15 2016 14:46:18) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
`

`➜  ~ php -m               
[PHP Modules]
apc
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
ldap
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
odbc
openssl
pcntl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_sqlite
Phar
posix
readline
recode
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xdebug
xhprof
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib
[Zend Modules]
Xdebug
Zend OPcache`

**Comment by glzjin** [comment]
请自己上网搜索解决方案。

**Comment by jimorsm** [comment]
大佬，我保证有找过资料，什么装json、phalcon或者降级升级，都试了，降级网站就挂了，面板好像要求php不能太低，试了5.7，7.0和7.1，都是一样，用的是centos7最新和remi的源。大佬们拜托，要是有知道解决方案的，请说一下

2016-10-10 10:07 GMT+03:00 glzjin <notifications@github.com>:

**Comment by jimorsm** [comment]
很奇怪的是，只有执行xcat syncnas才出错，其他都是正常的

**Comment by glzjin** [comment]
@jimorsm 请问你的服务器上还存在其他php版本吗

**Comment by jimorsm** [comment]
没有的，我尝试换不同版本php时都是卸载掉再安装的

~ rpm -qa | grep php |sort
php-5.6.26-1.el7.remi.x86_64
php-bcmath-5.6.26-1.el7.remi.x86_64
php-cli-5.6.26-1.el7.remi.x86_64
php-common-5.6.26-1.el7.remi.x86_64
php-devel-5.6.26-1.el7.remi.x86_64
php-doctrine-instantiator-1.0.5-1.el7.remi.noarch
php-fpm-5.6.26-1.el7.remi.x86_64
php-gd-5.6.26-1.el7.remi.x86_64
php-gmp-5.6.26-1.el7.remi.x86_64
php-ldap-5.6.26-1.el7.remi.x86_64
php-mbstring-5.6.26-1.el7.remi.x86_64
php-mcrypt-5.6.26-1.el7.remi.x86_64
phpMyAdmin-4.6.4-1.el7.remi.noarch
php-myclabs-deep-copy-1.5.4-1.el7.remi.noarch
php-mysqlnd-5.6.26-1.el7.remi.x86_64
php-odbc-5.6.26-1.el7.remi.x86_64
php-opcache-5.6.26-1.el7.remi.x86_64
php-pdo-5.6.26-1.el7.remi.x86_64
php-pear-1.10.1-7.el7.remi.noarch
php-pecl-apcu-4.0.11-2.el7.remi.5.6.x86_64
php-pecl-igbinary-1.2.1-1.el7.remi.5.6.x86_64
php-pecl-jsonc-1.3.10-1.el7.remi.5.6.x86_64
php-pecl-jsonc-devel-1.3.10-1.el7.remi.5.6.x86_64
php-pecl-xdebug-2.4.1-1.el7.remi.5.6.x86_64
php-pecl-xhprof-0.9.4-4.el7.remi.5.6.x86_64
php-pecl-zip-1.13.4-1.el7.remi.5.6.x86_64
php-phalcon-1.3.4-1.el7.remi.5.6.x86_64
php-phpdocumentor-reflection-docblock-2.0.4-1.el7.remi.noarch
php-php-gettext-1.0.11-12.el7.remi.noarch
php-phpseclib-2.0.4-1.el7.remi.noarch
php-phpspec-prophecy-1.6.1-1.el7.remi.noarch
php-phpunit-comparator-1.2.0-1.el7.remi.noarch
php-phpunit-diff-1.4.1-1.el7.remi.noarch
php-phpunit-environment-1.3.8-1.el7.remi.noarch
php-phpunit-exporter-1.2.2-1.el7.remi.noarch
php-phpunit-File-Iterator-1.4.1-1.el7.remi.noarch
php-phpunit-PHP-CodeCoverage-4.0.1-1.el7.remi.noarch
php-phpunit-PHP-Invoker-1.1.4-1.el7.remi.noarch
php-phpunit-PHP-Timer-1.0.8-1.el7.remi.noarch
php-phpunit-PHP-TokenStream-1.4.8-1.el7.remi.noarch
php-phpunit-PHPUnit-5.6.1-1.el7.remi.noarch
php-phpunit-PHPUnit-MockObject-3.3.1-1.el7.remi.noarch
php-phpunit-Text-Template-1.2.1-1.el7.remi.noarch
php-phpunit-Version-2.0.0-1.el7.remi.noarch
php-process-5.6.26-1.el7.remi.x86_64
php-recode-5.6.26-1.el7.remi.x86_64
php-sebastian-code-unit-reverse-lookup-1.0.0-1.el7.remi.noarch
php-sebastian-global-state-1.1.1-1.el7.remi.noarch
php-sebastian-object-enumerator-1.0.0-1.el7.remi.noarch
php-sebastian-recursion-context-1.0.2-1.el7.remi.noarch
php-sebastian-resource-operations-1.0.0-1.el7.remi.noarch
php-soap-5.6.26-1.el7.remi.x86_64
php-symfony-class-loader-2.8.12-1.el7.remi.noarch
php-symfony-common-2.8.12-1.el7.remi.noarch
php-symfony-yaml-2.8.12-1.el7.remi.noarch
php-tcpdf-6.2.12-1.el7.remi.noarch
php-tcpdf-dejavu-sans-fonts-6.2.12-1.el7.remi.noarch
php-tidy-5.6.26-1.el7.remi.x86_64
php-udan11-sql-parser-3.4.10-1.el7.remi.noarch
php-xml-5.6.26-1.el7.remi.x86_64
php-xmlrpc-5.6.26-1.el7.remi.x86_64

**Comment by jimorsm** [comment]
大佬，发现执行php的时候不带参数就正常了：
php xcat dailyjob 
  adding: tmp/ssmodbackup/mod.sql (deflated 72%)

带 -n 参数时：
php -n xcat dailyjob

Fatal error: Interface 'JsonSerializable' not found in /var/www/superpanel/vendor/illuminate/support/Fluent.php on line 11

**Comment by jimorsm** [comment]
disable function也设置了的

disable_functions = passthru,exec,chroot,chgrp,chown,shell_exec,proc_open,proc_get_status,popen,ini_alter,ini_restore,dl,openlog,syslog,readlink,symlink,popepassthru,stream_socket_server
