### ISSUE TITLE
新版的mu对接读取数据貌似出了问题，还有安装过的朋友遇到吗？

### ISSUE THREAD

**Issue by lion1991** [glzjin/ss-panel-v3-mod#3]
用这里的包，重新安装的前端的数据库。一切OK后，使用/mu/users?key=“key”报错，打开debug发现是：

    // User List
    public function index($request, $response, $args)
    {
		$node = Node::where("node_ip","=",$_SERVER["REMOTE_ADDR"])->where("sort","=","0")->first();
		$node->node_heartbeat=time();
		$node->save();
		
		
        $users = User::where("class",">=",$node->node_class)->where("expire_in",">",date("Y-m-d H:i:s"))->get();
		
		if($node->node_bandwidth_limit!=0)
		{
			if($node->node_bandwidth_limit<$node->node_bandwidth)
			{
				$users=null;
			}
			
		}
		

此时，数据ss_node表是默认的，无任何新加数据。之后怀疑是节点IP和域名问题，把智能线路删掉，依然报错，然后又把默认的radius两个表删掉。还一样。我新添加一个节点。在后台界面中节点IP地址都有被读取出来。然而MU读取还是报错。最后我把上述语句换为：
$users = User::all();
成功打开了. 获取到了相关信息。上面的语句对于GO版有实际作用吗

**Comment by glzjin** [comment]
倒是请发一下截图呀

**Comment by lion1991** [comment]
![2](https://cloud.githubusercontent.com/assets/18396082/14939735/6a978082-0f86-11e6-9ba6-32b313ab50f5.jpg)
![1](https://cloud.githubusercontent.com/assets/18396082/14939736/6ad2dcf4-0f86-11e6-90f6-1062fbd2bc1f.jpg)

**Comment by glzjin** [comment]
你数据库里 node_ip 正确获取到了IP吗=、=

**Comment by lion1991** [comment]
取到IP了.

**Comment by lion1991** [comment]
统一验证登陆和VPN 统一流量结算  这个数据库自带的没有.

**Comment by lion1991** [comment]
原版是访问api可以打开. 其他地址在数据库中都解析到node ip了。我是centos 6.5 64位

**Comment by glzjin** [comment]
sort 是 0吗
glzjin
2016年5月1日 下午2:44，lion1991 <notifications@github.com>写道：原版是访问api可以打开. 其他地址在数据库中都解析到node ip了。我是centos 6.5 64位

**Comment by lion1991** [comment]
对，除了那两个自带的999的其他的都是0

**Comment by glzjin** [comment]
并没有遇到你说的问题，自然也就无法解决，自己看看哪里设置出错了没吧=、=
glzjin
2016年5月1日 下午2:51，lion1991 <notifications@github.com>写道：对，除了那两个自带的999的其他的都是0

**Comment by lion1991** [comment]
好吧 如果不用这个public function呢 直接获取全部user的数据 会有什么影响吗？

**Comment by glzjin** [comment]
功能失效=、=不过你不用节点IP应该是打不开那个的=、=之前调试的时候不小心关掉了=、=现在应该打开了=、=刚刚更新了下，可以覆盖文件更新。
glzjin
2016年5月1日 下午3:17，lion1991 <notifications@github.com>写道：好吧 如果不用这个public function呢 直接获取全部user的数据 会有什么影响吗？

**Comment by lion1991** [comment]
-。-...更新后可以了，不过/app/Command/Job.php  这里的是不是也需要更新一下，因为之前的检测地址已经失效了。

**Comment by glzjin** [comment]
不要急=、=
glzjin
2016年5月1日 下午4:12，lion1991 <notifications@github.com>写道：-。-...更新后可以了，不过/app/Command/Job.php  这里的是不是也需要更新一下，因为之前的检测地址已经失效了。

**Comment by glzjin** [comment]
这个是节点IP没被录入面板 我这个版本对于安全特别重视

**Comment by lion1991** [comment]
试了无数次还是不行,看来可能出于未知原因我的服务端对于node的判断,一直返回的是null值.导致无法验证用户信息开启go失败.暂时先这样,关注一下其他用户有没有类似情况.

**Comment by glzjin** [comment]
你的面板是不是开了CDN？

**Comment by lion1991** [comment]
@glzjin !!!忽略了这个问题!  sspanel-mod面板的域名使用的cdn  CNAME解析,也就是说请求面板go api的时候解析到这个地址导致无法识别到后端地址.使得返回了null...
看来只能二选一了!

**Comment by glzjin** [comment]
别急，有办法的，用nginx的real ip模块，你用的是cloudflare的话 cf官方有一个文档可以看下。
glzjin
2016年5月2日 下午1:19，lion1991 <notifications@github.com>写道：@glzjin !!!忽略了这个问题!  sspanel-mod面板的域名使用的cdn  CNAME解析,也就是说请求面板go api的时候解析到这个地址导致无法识别到后端地址.使得返回了null...
看来只能二选一了!

**Comment by WangQiru** [comment]
@lion1991 最后解决了吗？
我开了cloudflare的DNS隐藏IP，但是貌似直接IP访问，mu/users?key=key，得到的也是DEBU[0000] {"ret":0,"msg":"source is invalid"}

sspanel原版的mu没这个问题，换到mod才出现的问题。
