### ISSUE TITLE
运行 php xcat syncusers 之后，出现错误提示

### ISSUE THREAD

**Issue by CyrixIII** [glzjin/ss-panel-v3-mod#30]
运行 **php xcat syncusers** 之后，出现下面的错误提示：

```
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'radius.userinfo' doesn't exist' in /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php:408
Stack trace:
#0 /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php(408): PDO->prepare('insert into `us...')
#1 /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php(666): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `us...', Array)
#2 /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#3 /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php(409): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#4 /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php(365): Illuminate\Database\Connection->statement('insert into `us...', Array)
#5 /home/wwwroot/ss-panel/vendor in /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php on line 673
```

**Comment by glzjin** [comment]
请自己看wiki
glzjin
2016年5月8日 下午10:25，CyrixIII <notifications@github.com>写道：运行 php xcat syncusers 之后，出现下面的错误提示：

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'radius.userinfo' doesn't exist' in /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php:408
Stack trace:
#0 /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php(408): PDO->prepare('insert into `us...')
#1 /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php(666): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `us...', Array)
#2 /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php(629): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#3 /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php(409): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#4 /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php(365): Illuminate\Database\Connection->statement('insert into `us...', Array)
#5 /home/wwwroot/ss-panel/vendor in /home/wwwroot/ss-panel/vendor/illuminate/database/Connection.php on line 673

**Comment by glzjin** [comment]
请看wiki的安装步骤，你没导入radius数据库结构。

**Comment by DearTanker** [comment]
不是说，不要VPN的话，就不需要看radius相关的安装吗？
