### ISSUE TITLE
zhao大你好，请问下用户等级的名称如何修改？

### ISSUE THREAD

**Issue by tsongneil** [glzjin/ss-panel-v3-mod#300]
如题~

**Comment by glzjin** [comment]
@tsongneil 不能修改

**Comment by tsongneil** [comment]
zhao大回的好快- - 那为啥我看dotunnel那边都改了

#3	套餐一（包月套餐、不限流量、使用期限1个月）	10.00 元	添加流量 999999 G ,,为账号升级为等级 VIP一星会员 ,有效期 30 天	不能自动续费	是
购买	#4	套餐二（包季套餐、不限流量、使用期限3个月）	25.00 元	添加流量 999999 G ,,为账号升级为等级 VIP一星会员 ,有效期 90 天	不能自动续费	是
购买	#5	套餐三（包半年套餐、不限流量、使用期限6个月）	50.00 元	添加流量 999999 G ,,为账号升级为等级 VIP一星会员 ,有效期 180 天	不能自动续费	是
购买	#7	套餐四（包年套餐、不限流量、使用期限12个月）	100.00 元	添加流量 999999 G ,,为账号升级为等级 VIP二星会员 ,有效期 365 天

**Comment by glzjin** [comment]
@tsongneil 哦，这个是商品名字。

**Comment by tsongneil** [comment]
额  但是不光商品名 他帐号等级名字也修改了 是通过改皮改的吗

帐号使用情况
账号等级 体验等级

**Comment by glzjin** [comment]
@tsongneil 那你自己去问他吧。

**Comment by tsongneil** [comment]
好吧 还是谢谢赵大了。。没事
