### ISSUE TITLE
从昨天开始 我的部分统计失效了 求助

### ISSUE THREAD

**Issue by srzdk** [glzjin/ss-panel-v3-mod#304]
用户中心 节点列表 内 
线路负载情况正常
**最近一天在线人数不正常** 始终是0
测速正常

管理面板 节点
**流量使用记录** 停止在昨晚7点了
**在线IP** 什么都没有

我实在忘记了我都做了哪些修改

我能想起来的就是
我曾经有改过 /home/wwwroot/default/
我曾经编辑过唯一一个节点的地址** 我把域名改成了IP地址
我还git pull了最近两个版本

**Comment by srzdk** [comment]
说明一下 我修改 /home/wwwroot/default/ 是因为LNMP 默认的那个探针页面建议修改phpadmin

我的魔改还是在 /home/wwwroot/域名 下的

**Comment by glzjin** [comment]
自己检查后端运行日志。

**Comment by srzdk** [comment]
大概明白是怎么回事了
账户内有个选项 单端口多用户承载端口
把这个打开该账户就不计入统计了。。。

**Comment by glzjin** [comment]
@srzdk 废话。。。记到普通用户上了

**Comment by srzdk** [comment]
我打算一个设备一个账号了
