### ISSUE TITLE
前端和数据库分离后备份数据库提示连接不上

### ISSUE THREAD

**Issue by rainlgtao** [glzjin/ss-panel-v3-mod#305]
![image](https://cloud.githubusercontent.com/assets/20722752/19226755/34ecd668-8ee2-11e6-92aa-6f9fec573356.png)

数据库为腾讯云，端口不是3306。网站可以正常访问，就是备份有问题。
请问赵老师这是什么原因？谢谢！

**Comment by glzjin** [comment]
https://github.com/glzjin/ss-panel-v3-mod/commit/ee7f1912227c1f5571070ca9a49355231395a777
