### ISSUE TITLE
avater地址能不能用原生的而不是国内反代

### ISSUE THREAD

**Issue by KazamaSion** [glzjin/ss-panel-v3-mod#306]
https://en.gravatar.com/avatar/3e370055fe676c59f0b95fa629e7f3c5
https://avatar.zhaojin97.cn/avatar/3e370055fe676c59f0b95fa629e7f3c5

缓存太大以至于更换了头像都刷不出来

**Comment by glzjin** [comment]
@KazamaSion 不能等等吗

**Comment by KazamaSion** [comment]
@glzjin 我等了3天了

**Comment by kaikaisd** [comment]
@glzjin 不等就自已改啊。。。。。

**Comment by glzjin** [comment]
@KazamaSion 你等三天 我等某个人都三年了 

缓存 七天有效期

**Comment by KazamaSion** [comment]
@kaikaisd 我确实自己改了
@glzjin 七天有效期……好吧

**Comment by kaikaisd** [comment]
@KazamaSion 那。。。發什麼issue啊。。。。改了就改了，不用在這里說，而且多少人會注意那里。。

**Comment by KazamaSion** [comment]
@kaikaisd 我就是想吐槽这个反代的缓存……未免有点过长了。
我个人认为还不如直接用原始地址而不是用反代植入代码内……

**Comment by kaikaisd** [comment]
@KazamaSion 那你想avater 更快在國內gfw 還是給avater續1s?

**Comment by KazamaSion** [comment]
@kaikaisd 开发者怎么想我确实管不着，我最多提出来希望能够注意到“缓存过长”这个问题。
这种问题虽说可有可无，自己改改确实没什么。

而且avater有啥被墙的必要吗……

**Comment by kaikaisd** [comment]
@KazamaSion 有。。頭像可以寫上"x中X"這種文字
