### ISSUE TITLE
升级到新版后出现故障

### ISSUE THREAD

**Issue by terryops** [glzjin/ss-panel-v3-mod#309]
注册有问题，点击注册没有反应，也不提示错误，第二次再点就提示验证码错误。

**Comment by glzjin** [comment]
@terryops 开debug 按f12 抓包—.—

**Comment by terryops** [comment]
http://www.*** .***/auth/register Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by glzjin** [comment]
@terryops 开debug

**Comment by terryops** [comment]
本来就是开着，没提示呢。

**Comment by YancyLeeQAQ** [comment]
@terryops f12。。。

**Comment by terryops** [comment]
fixed。config字段问题。
