### ISSUE TITLE
希望增加docker支持，简化部署

### ISSUE THREAD

**Issue by cbwang2016** [glzjin/ss-panel-v3-mod#310]
其实就是希望给前端后端都弄个官方的Dockerfile。。。

**Comment by terryops** [comment]
@cbwang2016 docker只支持有限端口，做了用出不大。

**Comment by cbwang2016** [comment]
那就只前端做个docker

**Comment by JohnFreeman9** [comment]
excuse me？敢问一句做docker意义何在？能给出一个让人信服的理由？

**Comment by cbwang2016** [comment]
@JohnFreeman9 简化部署

**Comment by kaikaisd** [comment]
@cbwang2016 然而菊花被開洞都不知道了

**Comment by JohnFreeman9** [comment]
@cbwang2016 啧啧，还是推荐一本教程吧，《简化部署——从使用一键包到被爆菊跑路》
