### ISSUE TITLE
php xcat checkjob 后出现警告

### ISSUE THREAD

**Issue by WhoRUa** [glzjin/ss-panel-v3-mod#312]
PHP Warning:  fopen(/data/wwwroot/www.utemp.info/storage/qqwry.dat): failed to open stream: No such file or directory in /data/wwwroot/www.utemp.info/app/Utils/QQWry.php on line 26

新建的小站，执行php xcat checkjob后出现出现这个

**Comment by WhoRUa** [comment]
是不是阿里云才会出现到期用户不降级的情况

**Comment by glzjin** [comment]
自己看安装说明，有没有严格执行。
