### ISSUE TITLE
关于注册用户接收不到每日流量提醒邮件的问题

### ISSUE THREAD

**Issue by lwq6783293** [glzjin/ss-panel-v3-mod#314]
注册验证码能收到，就是每日流量提醒收不到，这是什么原因呢？如果是发信原因的话，应该所有邮件都收不到啊

**Comment by glzjin** [comment]
请检查你的 crond 运行状况。

**Comment by lwq6783293** [comment]
你好，今天把crond重启了一下，我的邮箱马上就收到了一封更新的邮件，请问这样算是开启crond成功了吗？

**Comment by glzjin** [comment]
算
