### ISSUE TITLE
管理账户无法连接节点问题

### ISSUE THREAD

**Issue by fmask** [glzjin/ss-panel-v3-mod#315]
管理账户默认1025的连接端口 后来改成6666都能连接的 
不知道为啥 后来不能连接 
创建普通账户可以连接。这是什么问题。。请问一下。。

**Comment by glzjin** [comment]
@fmask 请检查你的账号是否存在过期 等级不匹配 群组不匹配等情况

**Comment by fmask** [comment]
非常感谢dalao的帮助！！！
