### ISSUE TITLE
git pull 更新出现这个提示。

### ISSUE THREAD

**Issue by halo1094** [glzjin/ss-panel-v3-mod#318]
Updating 4482832..c82548f
error: Your local changes to 'resources/views/material/auth/register.tpl' would be overwritten by merge.  Aborting.
Please, commit your changes or stash them before you can merge.
赵老师这个怎么回事？

**Comment by JohnFreeman9** [comment]
@halo1094 reset再来

**Comment by glzjin** [comment]
git reset --hard
