### ISSUE TITLE
PAC用到的squid使用25端口，邮件无法发送

### ISSUE THREAD

**Issue by xiadena** [glzjin/ss-panel-v3-mod#32]
如果想同时使用stmp和squid有什么好的解决的办法吗

**Comment by glzjin** [comment]
暂无办法
------------------------------------------------------------------发件人：xiadena <notifications@github.com>发送时间：2016年5月9日(星期一) 02:10收件人：glzjin/ss-panel-v3-mod <ss-panel-v3-mod@noreply.github.com>主　题：[glzjin/ss-panel-v3-mod] PAC用到的squid使用25端口，邮件无法发送 (#32)
如果想同时使用stmp和squid有什么好的解决的办法吗—
