### ISSUE TITLE
10月12号更新前端后，网站不能访问，或出现502Bad

### ISSUE THREAD

**Issue by zh6223820** [glzjin/ss-panel-v3-mod#322]
以下是nginx服务器日志 和top信息

 PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 2079 www       20   0  279152  40112  12772 R 23.6  4.0   0:40.54 php-fpm
 2043 www       20   0  287348  47344  12708 R 23.0  4.7   0:43.30 php-fpm
 2034 www       20   0  292976  53860  12704 R 21.4  5.3   0:44.50 php-fpm
 1818 www       20   0  293000  53864  12692 R 11.8  5.3   0:42.38 php-fpm
 1817 www       20   0  295028  54720  12692 R 10.5  5.4   0:40.71 php-fpm
    3 root      20   0       0      0      0 R  5.7  0.0   0:13.01 ksoftirqd/0
 1994 www       20   0  279352  40032  12696 R  3.2  4.0   0:48.18 php-fpm
 2119 www       20   0  298096  58048  12700 S  1.3  5.7   0:41.52 php-fpm
  145 root      39  19       0      0      0 S  0.3  0.0   0:00.11 khugepaged
    1 root      20   0   33244   3868   2712 S  0.0  0.4   0:03.10 init
    2 root      20   0       0      0      0 S  0.0  0.0   0:00.00 kthreadd
    5 root       0 -20       0      0      0 S  0.0  0.0   0:00.00 kworker/0:0H
    7 root      20   0       0      0      0 R  0.0  0.0   0:00.65 rcu_sched
    8 root      20   0       0      0      0 S  0.0  0.0   0:01.19 rcuos/0
    9 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuos/1
   10 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuos/2
   11 root      20   0       0      0      0 S  0.0  0.0   0:00.00 rcuos/3

top信息截图

2016/10/13 19:08:03 [crit] 4266#0: *3 connect() to unix:/tmp/php-cgi.sock failed (2: No such file or directory) while connecting to upstream, client: 191.96.249.80, server: talk.sufei.cc, request: "POST /xmlrpc.php HTTP/1.0", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "210.140.82.30"
2016/10/13 19:08:04 [crit] 4266#0: *5 connect() to unix:/tmp/php-cgi.sock failed (2: No such file or directory) while connecting to upstream, client: 191.96.249.80, server: talk.sufei.cc, request: "POST /xmlrpc.php HTTP/1.0", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "210.140.82.30"
2016/10/13 19:08:04 [crit] 4266#0: *7 connect() to unix:/tmp/php-cgi.sock failed (2: No such file or directory) while connecting to upstream, client: 191.96.249.80, server: talk.sufei.cc, request: "POST /xmlrpc.php HTTP/1.0", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "210.140.82.30"
2016/10/13 19:08:04 [crit] 4266#0: *9 connect() to unix:/tmp/php-cgi.sock failed (2: No such file or directory) while connecting to upstream, client: 191.96.249.80, server: talk.sufei.cc, request: "POST /xmlrpc.php HTTP/1.0", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "210.140.82.30"
2016/10/13 19:13:54 [crit] 1814#0: *1 connect() to unix:/tmp/php-cgi.sock failed (2: No such file or directory) while connecting to upstream, client: 191.96.249.80, server: talk.sufei.cc, request: "POST /xmlrpc.php HTTP/1.0", upstream: "fastcgi://unix:/tmp/php-cgi.sock:", host: "210.140.82.30"

现在站点已经不能访问，请大佬支持

**Comment by glzjin** [comment]
@zh6223820 请检查站点是否在被攻击

**Comment by zh6223820** [comment]
如何检查网站是否在被攻击

**Comment by zh6223820** [comment]
宽带使用量正常，php-fpm占用Cpu过多
webhost.cs24b7idcfcloud.i  => 43.255.179.180             4.34Mb  5.46Mb  5.46Mb
                           <=                             138kb   127kb   127kb
webhost.cs24b7idcfcloud.i  => 74.125.106.136                0b   20.7kb  20.7kb
                           <=                               0b   1.89Mb  1.89Mb
webhost.cs24b7idcfcloud.i  => edge-video-shv-01-lga3.fb  5.94kb  9.12kb  9.12kb
                           <=                             204kb   253kb   253kb
webhost.cs24b7idcfcloud.i  => 191.96.249.80              1.14kb  1.86kb  1.86kb
                           <=                            5.09kb  7.88kb  7.88kb
webhost.cs24b7idcfcloud.i  => 10.15.0.1                   572b   2.20kb  2.20kb
                           <=                             572b   3.22kb  3.22kb
webhost.cs24b7idcfcloud.i  => 138.68.85.230              2.11kb  1.16kb  1.16kb
                           <=                            2.06kb  1.15kb  1.15kb
webhost.cs24b7idcfcloud.i  => 43.249.72.24                  0b    224b    224b
                           <=                               0b   1.49kb  1.49kb
webhost.cs24b7idcfcloud.i  => 151.101.72.249              208b   1.26kb  1.26kb
                           <=                             208b    432b    432b
webhost.cs24b7idcfcloud.i  => 91.108.56.149              1.51kb   772b    772b
                           <=                            1.72kb   882b    882b
qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
TX:             cum:   2.75MB   peak:   6.65Mb  rates:   4.35Mb  5.50Mb  5.50Mb
RX:                    1.14MB           4.20Mb            352kb  2.27Mb  2.27Mb
TOTAL:                 3.89MB           10.9Mb           4.69Mb  7.77Mb  7.77Mb

**Comment by zh6223820** [comment]
占掉了所有的cpu,之前也出现过一次这样的问题 重新安装之后问题解决了

**Comment by glzjin** [comment]
@zh6223820 你可能被cc了 还有php优化不是我应该回答你的问题 请你自己上网搜索

**Comment by zh6223820** [comment]
我把nginx 和php停止后，服务上的shadowsocks响应正常！cpu恢复正常，这会不会是由于更新引起的错误呢

**Comment by glzjin** [comment]
@zh6223820 不会
