### ISSUE TITLE
流量使用记录无法正常记录

### ISSUE THREAD

**Issue by syaseigen** [glzjin/ss-panel-v3-mod#324]
按照教程一步步搭建下来可以正常浏览外墙(在此感谢作者)
但后端用的是shadowsocks-rm的版本,不是作者推荐的ssr

现在有个小问题, 就是预设每个用户有100gb流量
但早上8点搭建好到现在, 流量纪录里并无任何东西
是必须使用作者推荐的ssr才能记录个别用户使用的流量纪录吗?

谢谢

**Comment by YancyLeeQAQ** [comment]
@syaseigen 没错，前后端本来就是配套的

**Comment by ctrlbbj** [comment]
@syaseigen 不是所有后端都支持流量记录功能的

**Comment by syaseigen** [comment]
@YancyLeeQAQ  
谢谢,原来是得配套使用才能记录

@ctrlbbj 谢谢说明, 等等我再重新搞一次后端看看

**Comment by syaseigen** [comment]
下午历经重新搭建之后,除了汇总里的"节点在线情况"之外都能正常显示
例如用户登录信息, 流量.....等等都没问题
但怎么节点在线不显示呢?

**Comment by syaseigen** [comment]
![111](https://cloud.githubusercontent.com/assets/22812339/19389070/0deadcce-9255-11e6-9d9e-9d1392cda842.jpg)
下午历经重新搭建之后,除了汇总里的"节点在线情况"之外都能正常显示
例如用户登录信息, 流量.....等等都没问题
但怎么节点在线不显示呢?

**Comment by ctrlbbj** [comment]
@syaseigen 节点node id是否配置正确

**Comment by syaseigen** [comment]
@ctrlbbj 节点列表中目前只有一个节点, 其id为#3
您说的node id配置是指?
![111](https://cloud.githubusercontent.com/assets/22812339/19389268/ec893db8-9255-11e6-9d44-963d2aaa64a4.jpg)

**Comment by ctrlbbj** [comment]
@syaseigen 后端程序的配置中的node id

**Comment by syaseigen** [comment]
@ctrlbbj 啊谢谢, 想起来了, 忘了更改userapiconfig.py
修改后已经正常显示,谢谢
