### ISSUE TITLE
BUG:Radius认证,用户流量剩余判断。

### ISSUE THREAD

**Issue by TShuiping** [glzjin/ss-panel-v3-mod#325]
在用户账户下无剩余流量(没流量)的情况下 可以通过认证链接  统一结算流量后 扣除的流量在账户上显示负数流量 并且依旧可以再次通过认证。

**Comment by glzjin** [comment]
@TShuiping 请检查你的计划任务是否在正常运行

**Comment by TShuiping** [comment]
@glzjin 计划任务正常

**Comment by glzjin** [comment]
@TShuiping 你确定所有计划任务都正确设置并且运行了吗

**Comment by TShuiping** [comment]
@glzjin 计划任务两个管理VPN的 都可以正常认证 以及 结算流量 所以我确定所以我确定。

**Comment by glzjin** [comment]
@TShuiping 好的，在有空的时候我会排查一下。

**Comment by TShuiping** [comment]
@glzjin 好的 麻烦你了

**Comment by glzjin** [comment]
经过我测试并没有问题，请检查你自己的计划任务是否在正常运行，特别是 checkjob 这个。

**Comment by TShuiping** [comment]
@glzjin 大部分账户确实可以正常认证 但确实有部分账户可以重现这个问题

**Comment by glzjin** [comment]
@TShuiping 能正常操作就行了，反正是符合规则的才会被删除。就这样。

**Comment by TShuiping** [comment]
@glzjin ( ´∵｀)有点懵 是不是回复错了 ，
