### ISSUE TITLE
可以发送每日流量提醒邮件，但无法发送注册时的验证码邮件(mailgun)

### ISSUE THREAD

**Issue by 512557852** [glzjin/ss-panel-v3-mod#328]
点击发送验证码的时候只弹出空白确认框，查看数据库已经有验证码生成，mailgun后台看到没有新的邮件发送

**Comment by 512557852** [comment]
在发送流量提醒邮件的时候也出现了一些问题。
能够发送第一个用户的提醒邮件，但发送第二个用户时出现错误：
`PHP Fatal error:  Uncaught Mailgun\Connection\Exceptions\MissingRequiredParameters: The parameters passed to the API were invalid. Check your inputs! in /var/www/mss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:128
Stack trace:
#0 /var/www/mss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /var/www/mss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\Connection\RestClient->post('sandbox6f67a4a2...', Array, Array)
#2 /var/www/mss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\Mailgun->post('sandbox6f67a4a2...', Array, Array)
#3 /var/www/mss-panel/app/Services/Mail/Mailgun.php(39): Mailgun\Mailgun->sendMessage('sandbox6f67a4a2...', Array, Array)
#4 /var/www/mss-panel/app/Services/Mail.php(66): App\Services\Mail\Mailgun->send('810216626@qq.co...', '-\xE6\xAF\x8F\xE6\x97\xA5\xE6\xB5\x81\xE9\x87\x8F\xE6\x8A...', '<!DOCTYPE html ...', Array)
#5 /var in /var/www/mss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 128`

**Comment by glzjin** [comment]
@512557852 请检查你mailgun账号的状态

**Comment by 512557852** [comment]
谢谢，的确是mailgun账号的问题。用的测试账号有发送限制。
