### ISSUE TITLE
请问新节点连接问题

### ISSUE THREAD

**Issue by syaseigen** [glzjin/ss-panel-v3-mod#329]
现有两台vps, vpsA用来搭建前后台, 其ip: 1.1.1.1另一台vpsB只当后台, ip:2.2.2.2
vpsA的数据库设置了主机%, 权限ALL, 后台的配置中manege_bind_ip设置了1.1.1.1
然后vpsB的后台mysql配置输入了1.1.1.1和数据库名称用户名及密码

这样的步骤应该是对的吧.但好像还是出现错误
貌似无法存取vpsA的数据库....但权限应该是没错啊
![qq20161015-0 2x](https://cloud.githubusercontent.com/assets/22812339/19409718/d0b0b96a-930c-11e6-94e7-a31cf6f39799.jpg)

**Comment by glzjin** [comment]
@syaseigen 请检查3306是否开启

**Comment by syaseigen** [comment]
@glzjin 您好, 谢谢回复, 是下图这样吗?
![qq20161015-1 2x](https://cloud.githubusercontent.com/assets/22812339/19409753/cd10bb7e-930d-11e6-82bf-7d6a96d06376.jpg)

**Comment by glzjin** [comment]
@syaseigen 防火墙上

**Comment by syaseigen** [comment]
@glzjin 不好意思, 不太明白您意思...小弟还只是个新手

**Comment by glzjin** [comment]
@syaseigen iptables

**Comment by syaseigen** [comment]
@glzjin qing请再帮忙看下
![qq20161015-0 2x](https://cloud.githubusercontent.com/assets/22812339/19409867/6df8cdea-9310-11e6-85da-652b62969987.jpg)

**Comment by ctrlbbj** [comment]
防火墙并没有允许外部连接数据库

**Comment by syaseigen** [comment]
@ctrlbbj 请教下该怎么解决呢?谢谢

**Comment by ctrlbbj** [comment]
清除并保存防火墙规则，自行搜索具体如何处理

**Comment by syaseigen** [comment]
@ctrlbbj  谢谢, 按照您的建议目前解决问题了, 感谢
