### ISSUE TITLE
radius配置文件中找不到sql.conf注释，也找不到counter.conf

### ISSUE THREAD

**Issue by rqd1995** [glzjin/ss-panel-v3-mod#33]
按照wiki教程安装radius后，在/etc/raddb/radiusd.conf 中没有sql.conf和counter.conf的相关设置

**Comment by 619096932** [comment]
centos7.0貌似没有 用centos6x

**Comment by rqd1995** [comment]
这样啊，谢谢

**Comment by glzjin** [comment]
需要安装一个额外的radius MySQL包
glzjin
2016年5月9日 下午1:45，619096932 <notifications@github.com>写道：centos7.0貌似没有 用centos6x

**Comment by rqd1995** [comment]
那个freeradius-mysql也安装了，但是还是没有

**Comment by glzjin** [comment]
我不知道了= = 不过我传了一些我配置好的Centos6 的radius的文件上来。
