### ISSUE TITLE
重置邮件的链接无法打开

### ISSUE THREAD

**Issue by zhaoyan1245** [glzjin/ss-panel-v3-mod#330]
赵老师你好，用的是您最新版，其他功能都正常，但是当我使用重置密码的时候，邮件里的链接显示打不开，求指教

**Comment by glzjin** [comment]
@zhaoyan1245 请检查发件邮箱和收件邮箱。

**Comment by zhaoyan1245** [comment]
SMTP设置都是正常的，您可以去注册一个试试，mzvpn.com 这是密码重置连接，打不开https://mzvpn.com/password/token/XJUxkBpatoZuqo8aDDhUZPccFFNOPrqYANEy8JPghAd5XmSRVXVbn0J4Ic1mAabu

**Comment by glzjin** [comment]
@zhaoyan1245 mzvpn.com 意外终止了连接。

还有请确认你的邮箱不是QQ邮箱。
