### ISSUE TITLE
节点一直都显示 橘色

### ISSUE THREAD

**Issue by weiyu99** [glzjin/ss-panel-v3-mod#331]
<img width="286" alt="screen shot 2016-10-16 at 7 27 07 am" src="https://cloud.githubusercontent.com/assets/21979732/19414006/a067f564-9372-11e6-8333-4654289c25d2.png">

节点是可以用的，但是显示却是橘色。是哪里的设置没弄好吗？

**Comment by glzjin** [comment]
@weiyu99 检查后端node id的填写。。

**Comment by weiyu99** [comment]
@glzjin 感谢，原来是 node id 的问题。
