### ISSUE TITLE
赵大神，能否帮忙看下自己改的node.tpl代码按钮无法正常跳转到nodeinfo（单击按钮无反应）

### ISSUE THREAD

**Issue by wang259797** [glzjin/ss-panel-v3-mod#333]
赵大神，小弟最近在研究前端，遇到一个关于node.tpl文件代码的问题，小弟写的node.tpl采用与原版一样的`<a href="javascript:void(0);" onClick="urlChange('{$node->id}',0)" class="btn btn-primary btn-xs pull-right">查看配置</a>`连接，且底部也加入了js代码，但点击后运行没有任何反应，而用浏览器直接访问user/node/1?ismu=0可顺利打开节点信息页面，求大神帮忙看看是什么问题。附件为node.tpl和nodeinfo.tpl的压缩包。

万分感谢。
[Node.zip](https://github.com/glzjin/ss-panel-v3-mod/files/531673/Node.zip)

**Comment by glzjin** [comment]
@wang259797 浏览器，f12，打开控制台，看哪里错了。

**Comment by wang259797** [comment]
F12显示：
node:404 Uncaught TypeError: Cannot set property 'src' of nullurlChange 
@ node:404行： urlChange ，页面代码：`document.getElementById('infoifram').src = site;`
@ node:283行：onclick，页面代码：`<a href="javascript:void(0);" onClick="urlChange('3',0)" class="btn btn-primary btn-xs pull-right">查看配置</a>`

onClick="urlChange('3',0)"已经对应到相应节点ID。

求解

**Comment by glzjin** [comment]
@wang259797 你把info frame 干掉了？

**Comment by wang259797** [comment]
@glzjin 没有吧 难道node.tpl还要有info frame？原版中没发现有这玩意。。。

**Comment by glzjin** [comment]
@wang259797 不好意思 我指的是魔改版 有的 那个弹出窗口

**Comment by wang259797** [comment]
@glzjin 
你指的是nodeinfo.tpl？这个文件有的。。。

**Comment by wang259797** [comment]
@glzjin 我看懂了 我再试试 看来是忘了这段DIV了 3Q
