### ISSUE TITLE
后台商品下架失败

### ISSUE THREAD

**Issue by lkddi** [glzjin/ss-panel-v3-mod#337]
后台商品下架  点击确定后   提示空白信息   知道了  就没了。

在有节点列表 修改ip后，实际地址修改成功。但是列表ip 处 还是显示原有ip

**Comment by glzjin** [comment]
@lkddi 1.请开启debug 然后f12抓取返回结果。
2.请确保你填的域名正确无误能解析。

**Comment by lkddi** [comment]
第2个问题已经解决

**Comment by lkddi** [comment]
jquery.min.js:4 DELETE https://ay.lc/admin/shop 403 ()send @ jquery.min.js:4ajax @ jquery.min.js:4delete_id @ shop:492(anonymous function) @ shop:516dispatch @ jquery.min.js:3r.handle @ jquery.min.js:3
shop:511 Uncaught ReferenceError: data is not definederror @ shop:511i @ jquery.min.js:2fireWith @ jquery.min.js:2z @ jquery.min.js:4(anonymous function) @ jquery.min.js:4

**Comment by glzjin** [comment]
@lkddi 请抓包

**Comment by lkddi** [comment]
![qq 20161018171640](https://cloud.githubusercontent.com/assets/1597780/19471623/aa46d51a-9556-11e6-8635-6bb387a81b7e.jpg)
是这个吗?

**Comment by glzjin** [comment]
请发包返回信息
