### ISSUE TITLE
后端这个错误是什么原因

### ISSUE THREAD

**Issue by requestdeny** [glzjin/ss-panel-v3-mod#339]
root@root:~/shadowsocks# python server.py
loaded collections.OrderedDict
IPv6 support
Traceback (most recent call last):
  File "server.py", line 29, in <module>
    import speedtest_thread
  File "/root/shadowsocks/speedtest_thread.py", line 11, in <module>
    import cymysql
ImportError: No module named cymysql
root@root:~/shadowsocks# pip install cymysql
Requirement already satisfied (use --upgrade to upgrade): cymysql in /usr/local/lib/python3.4/dist-packages
看了一下speedtest-cli 也是正常的啊

**Comment by glzjin** [comment]
那就不知道咯 反正告诉你模块没装好 还有后端问题请发到后端那边的issue
