### ISSUE TITLE
ss-panel v3改为魔改版的问题

### ISSUE THREAD

**Issue by Tomzuo** [glzjin/ss-panel-v3-mod#34]
请问如何将现有的ss-panel v3 改用魔改版？特别是数据库的导入，导入魔改版的sql到现有数据库数据会不会丢失？应该怎么导入？还有魔改版支持rss吧？

**Comment by glzjin** [comment]
不会丢失，不过导入那个sql之后需要一步步升级上去，因为那个转换SQL比较老了。支持是支持，但是能用到的功能就没那么多了，可以考虑换ssshell。
glzjin
2016年5月9日 下午1:28，Tomzuo <notifications@github.com>写道：请问如何将现有的ss-panel v3 改用魔改版？特别是数据库的导入，导入魔改版的sql到现有数据库数据会不会丢失？应该怎么导入？还有魔改版支持rss吧？

**Comment by Tomzuo** [comment]
通过phpMyAdmin导入 glzjin_all.sql ？然后配置下魔改版前端就行了？ssshell支持rss的协议和混淆吗？

**Comment by glzjin** [comment]
不是 all ，是 upgrade 那个，不过那个比较老了，需要你一步步升级上来。ssshell 不支持混淆。

**Comment by Tomzuo** [comment]
upgrade_from_offical.sql这个？  不太明白一步步升级是什么意思

**Comment by glzjin** [comment]
看之前的升级步骤

**Comment by Tomzuo** [comment]
给个地址行吗
