### ISSUE TITLE
添加节点单端口多用户不显示

### ISSUE THREAD

**Issue by biu1biu** [glzjin/ss-panel-v3-mod#341]
在管理面板添加节点设置成Shadowsocks - 单端口多用户,在用户中心的节点列表里没有显示,设置成Shadowsocks就出来了,请问是怎么回事...

**Comment by Tiktoking** [comment]
在每个原有的节点下方有单端口的信息，不会多出一个节点列表出来，另外请确保你设置正确

**Comment by sephilex** [comment]
请问单端口多用户怎么配置，我搜了好久都没有，我看到之前的issue也有人问，也是没有回答

**Comment by glzjin** [comment]
@sephilex 看telegram频道 测试功能=、=不作任何推荐
