### ISSUE TITLE
后台用户管理里改不了用户资料信息

### ISSUE THREAD

**Issue by 512557852** [glzjin/ss-panel-v3-mod#342]
密码啊、流量、到期日期等等所有内容，改了之后按修改只弹出一个空白确认对话框，刷新页面后却没什么变化。这会是什么原因？

**Comment by glzjin** [comment]
@512557852 请开启debug f12打开抓包查看返回

**Comment by 512557852** [comment]
@glzjin F12显示500代理错误，禁用系统代理可以修改成功，谢谢！

**Comment by glzjin** [comment]
@512557852 。。。。。

**Comment by 512557852** [comment]
@glzjin 代理其他网页是没用问题的，不知道为什么开了代理修改的时候会出现500

**Comment by glzjin** [comment]
@512557852 请你在开启代理时刷新编辑界面

**Comment by 512557852** [comment]
@glzjin 还是一样的错误。之前我是一直开着代理的，不是进了编辑界面后再开启的代理。

**Comment by glzjin** [comment]
@512557852 那就不要关闭系统代理，开着debug，在编辑时候开f12抓包看看
