### ISSUE TITLE
手动修改用户等级过期时间后，会导致登录密码错误？

### ISSUE THREAD

**Issue by YueYueYue** [glzjin/ss-panel-v3-mod#344]
遇到几次这样的情况了，请问是为什么呢？登录密码加密应该不需要等级过期时间这部份数据吧

**Comment by glzjin** [comment]
@YueYueYue Zhao Jin | 个人频道 @glzjin_talk | 更好的自己 | 微笑 | 过膝袜狂热爱好者 | 短发控:
。。。你是不是自动保存了密码。。。

**Comment by YueYueYue** [comment]
好像是的。我懂了，密码栏要留空
