### ISSUE TITLE
后端搭建完成无法正常链接服务器防火墙已开启连续端口调试无错误信息

### ISSUE THREAD

**Issue by wxhnizy** [glzjin/ss-panel-v3-mod#349]
前端搭建完成正常访问以及注册http://www.72tenant.xyz/  后端搭建很多次 但依然无法正常链接服务器
运行调试service.py后网页节点显示正常 
![qq 20161022112425](https://cloud.githubusercontent.com/assets/21986327/19616608/3e3dad20-984a-11e6-92d2-6d39619de514.png)
调试信息：
![qq 20161022114805](https://cloud.githubusercontent.com/assets/21986327/19616730/6a277530-984d-11e6-84e6-0e33f751076b.png)

使用注册用户端口以及密码进行链接，网页不显示在线用户，客户端无法正常访问各种翻墙页面，客户端错误信息：
![qq 20161022112740](https://cloud.githubusercontent.com/assets/21986327/19616618/901c07cc-984a-11e6-8f32-8fd27fb1a00f.png)
检查fang'huo防火墙开启连续端口：
![o g x1xpbpcbvuo7p9 mimu](https://cloud.githubusercontent.com/assets/21986327/19616631/e0d20676-984a-11e6-9f4e-84e698d5db35.png)

![qq 20161022113347](https://cloud.githubusercontent.com/assets/21986327/19616649/6fee693a-984b-11e6-8791-f69f271e1acb.png)

保存生效防火墙并重启防火墙

完成以上步骤，但是客户端依然无法正常连接
![qq 20161022112740](https://cloud.githubusercontent.com/assets/21986327/19616657/86200a24-984b-11e6-88db-97f7220fdab6.png)
.config.php 文件只修改了 网站基本信息 以及 数据库信息，确认数据库信息无误。
![qq 20161022113721](https://cloud.githubusercontent.com/assets/21986327/19616669/eb772b64-984b-11e6-8ad6-8a3b32acac3b.png)
userapiconfig.py配置完整信息 这里也只做了 数据库信息修改，其他没有动 节点ID为3（网站以及SS是在同一个网站上做的测试数据库也在本站）
![qq 20161022113856](https://cloud.githubusercontent.com/assets/21986327/19616684/6eae2e38-984c-11e6-9082-00a6a6ce4d19.png)

以上就是我搭建SSV3的全部过程，我反复反复重新安装了很多遍 ，但是问题依然无法解决，我不知道我哪里做错了 ~防火墙也反复开启并关闭也不行，完全关闭防火墙也不行。如果你需要其他的信息我可以随时补充，万分感谢。

**Comment by syaseigen** [comment]
mysql用户权限给了吗?

**Comment by wxhnizy** [comment]
@syaseigen 
![qq 20161022120252](https://cloud.githubusercontent.com/assets/21986327/19616800/7dae1c88-984f-11e6-8584-722ca2669bb0.png)
如果我没设置错误的话 数据库应该是最高权限了 ~
![qq 20161022120340](https://cloud.githubusercontent.com/assets/21986327/19616805/97d114a8-984f-11e6-9f5a-110d9e162f9d.png)

**Comment by wxhnizy** [comment]
@glzjin 你好~请问可以在帮我看下我的配置信息吗？这次我附上了较为完整的配置文件信息 ~万分感谢

**Comment by glzjin** [comment]
@wxhnizy 你后端的日志呢

**Comment by wxhnizy** [comment]
@glzjin 限制了字符　只能附上一部分

by digitalocean (8.14.4/8.14.4/Submit) id u9LM11I6001809;
	Sat, 22 Oct 2016 06:01:01 +0800
Date: Sat, 22 Oct 2016 06:01:01 +0800
Message-Id: <201610212201.u9LM11I6001809@digitalocean>
From: root@digitalocean (Cron Daemon)
To: root@digitalocean
Subject: Cron <root@digitalocean> php /home/wwwroot/www.72tenant.xyz/xcat checkjob    
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>

PHP Fatal error:  Uncaught Mailgun\Connection\Exceptions\MissingEndpoint: The endpoint you've tried to access does not exist. Check your URL. in /home/wwwroot/www.72tenant.xyz/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:134
Stack trace:
#0 /home/wwwroot/www.72tenant.xyz/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /home/wwwroot/www.72tenant.xyz/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\Connection\RestClient->post('/messages', Array, Array)
#2 /home/wwwroot/www.72tenant.xyz/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\Mailgun->post('/messages', Array, Array)
#3 /home/wwwroot/www.72tenant.xyz/app/Services/Mail/Mailgun.php(39): Mailgun\Mailgun->sendMessage('', Array, Array)
#4 /home/wwwroot/www.72tenant.xyz/app/Services/Mail.php(66): App\Services\Mail\Mailgun->send('wxhnizy@qq.com', '72tenant-\xE6\x82\xA8\xE7\x9A\x84...', '<!DOCTYPE html ...', Array)
#5 /hom in /home/wwwroot/www.72tenant.xyz/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 134

From root@digitalocean  Sat Oct 22 06:02:02 2016
Return-Path: <root@digitalocean>
Received: from digitalocean (localhost [127.0.0.1])
	by digitalocean (8.14.4/8.14.4) with ESMTP id u9LM22Ns001822
	for <root@digitalocean>; Sat, 22 Oct 2016 06:02:02 +0800
Received: (from root@localhost)
	by digitalocean (8.14.4/8.14.4/Submit) id u9LM224a001821;
	Sat, 22 Oct 2016 06:02:02 +0800
Date: Sat, 22 Oct 2016 06:02:02 +0800
Message-Id: <201610212202.u9LM224a001821@digitalocean>
From: root@digitalocean (Cron Daemon)
To: root@digitalocean
Subject: Cron <root@digitalocean> php /home/wwwroot/www.72tenant.xyz/xcat checkjob    
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>

**Comment by glzjin** [comment]
@wxhnizy 后端的日志

**Comment by wxhnizy** [comment]
@glzjin 这个确实就是我运行./logrun.sh后得到的日志文件。文件路径在 /var/spool/mail/root　难道不是这个吗？

**Comment by glzjin** [comment]
@wxhnizy 不是

**Comment by wxhnizy** [comment]
@glzjin 那可以否麻烦你明示下后端的日志目录？除了这个以外我确实不知道其他的　日志路径～

**Comment by wxhnizy** [comment]
@glzjin 
![qq 20161022151641](https://cloud.githubusercontent.com/assets/21986327/19617729/b2bfa296-986a-11e6-811b-31943fb908e5.png)
你要这个？

**Comment by glzjin** [comment]
@wxhnizy 你并没有成功地读入用户

**Comment by wxhnizy** [comment]
@glzjin 问题出在数据库上吗？

**Comment by wxhnizy** [comment]
@glzjin 我只导入了　一个数据库文件glzjin_all.sql　后端数据库设置也是链接这里的　数据库名　为ＳＳＰＡＮＥＬ　
用户名相同密码自定义的？

**Comment by glzjin** [comment]
@wxhnizy 你自己检查一下完整的日志文件 看看开放了端口没吧 还有前后端nodeid是不是一样的。。。

**Comment by wxhnizy** [comment]
@glzjin 你可否告诉我　完整的日志文件在什么位置吗？我能找到的日志文件　只有这两个　其他的真的找不到。后端的　nodeid　与前端的配置文件里的ＩＤ是相同的　都是　３

**Comment by glzjin** [comment]
@wxhnizy 同一个目录下的 ssserver.log

**Comment by glzjin** [comment]
@wxhnizy Apblack 还有你用户帐户没过期吧

**Comment by wxhnizy** [comment]
@glzjin 
ssserver.log内容
![qq 20161022153244](https://cloud.githubusercontent.com/assets/21986327/19617815/14be3d52-986d-11e6-8ac6-349aa8abc794.png)

用户过期时间的配置信息我没有做过任何修改　
![qq 20161022153416](https://cloud.githubusercontent.com/assets/21986327/19617817/2dc5dc42-986d-11e6-8bc9-49a9ccc87f34.png)
用户信息中过期时间为
![qq 20161022153256](https://cloud.githubusercontent.com/assets/21986327/19617821/4b849a02-986d-11e6-96b2-eab26e702256.png)

**Comment by glzjin** [comment]
@wxhnizy 把账号过期时间设置为为未来的一个时间=、=

**Comment by wxhnizy** [comment]
@glzjin 
![qq 20161022154016](https://cloud.githubusercontent.com/assets/21986327/19617849/df4c644a-986d-11e6-846c-63c98870a5ee.png)

这里设置吗？这里提示不过期不做修改？我就没动过他～

**Comment by glzjin** [comment]
@wxhnizy 然而就是因为你自己的配置文件设置得不恰当 导致这里的值错误了

**Comment by wxhnizy** [comment]
@glzjin 配置文件中我只修改了，网站基本信息以及　数据库链接信息去除了　邮件验证服务　，其他的一点都没修改过，都是按照默认来进行安装的～　我真的不知道我的配置文件中哪里出现了错误～

**Comment by wxhnizy** [comment]
@glzjin 非常感谢你的帮助~问题解决了扫描二维码后可以正常链接，但是我还是一头雾水，可否明示下这种错误是怎么发生的吗？我对配置文件确实没有动过其他地方 ~

**Comment by glzjin** [comment]
@wxhnizy 预设用户帐户过期时间

**Comment by wxhnizy** [comment]
@glzjin 预设用户过期时间为 $System_Config['user_expire_in_default']='99999'; 难道是我系统的服务时间出现错误吗？

**Comment by wxhnizy** [comment]
@glzjin 虽然我的问题解决了 但是我还是想询问你一下，这个错误是怎么造成的如果像你说的是我配置的问题 但是 配置文件中 过期时间为99999，用户怎么会出现过期的问题呢？我刚才检查了  服务器的时间，服务器的时间没有问题。

**Comment by glzjin** [comment]
@wxhnizy 32位系统？

**Comment by wxhnizy** [comment]
@glzjin centos 6.8 32 是的

**Comment by glzjin** [comment]
@wxhnizy 溢出了 数字调小些 或者 换 64位

**Comment by wxhnizy** [comment]
@glzjin 好的 我尝试下 ~

**Comment by wxhnizy** [comment]
@glzjin 确实把数值调整小了以后 注册时候过期时间就正常了~ 感谢你的帮助 ~
