### ISSUE TITLE
新版3.2.7.8的ssr，安卓小米5运行无响应

### ISSUE THREAD

**Issue by a489651605** [glzjin/ss-panel-v3-mod#351]
一打开软件就卡白屏，已试多次，3.1.5.2-s这个版本往后的版本都白屏

**Comment by glzjin** [comment]
@a489651605 您能正常使用的版本是哪个版本呢 可以提供一下logcat日志吗

**Comment by a489651605** [comment]
能正常使用的版本是3.1.5.2-s，比此版本更高的都白屏
