### ISSUE TITLE
有一个节点流量显示突然异常，用一点就记录几百g流量

### ISSUE THREAD

**Issue by chenlinchet** [glzjin/ss-panel-v3-mod#355]
阿里云的后端节点，流量比例设置为2.5，开始流量记录正常，前几天突然发现开始异常记录流量了，一天记录几千g流量。重装了一次后端，今天发现还是记录异常。请问可能是什么原因呢？

**Comment by tsongneil** [comment]
顶一下
我也碰到这个问题

**Comment by glzjin** [comment]
请在后端那边的issue发并附上后端日志。
