### ISSUE TITLE
编辑用户信息时确定返回空白提示框.开启debug报数据库错

### ISSUE THREAD

**Issue by lion1991** [glzjin/ss-panel-v3-mod#36]
{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'radius.userinfo' doesn't exist (SQL: select * from `userinfo` where `username` = xxxxxxxqqcom limit 1)","file":"\/home\/wwwroot\/xxx\/vendor\/illuminate\/database\/Connection.php","line":673}}

**Comment by glzjin** [comment]
你没导入完全数据库或者数据库不存在

**Comment by glzjin** [comment]
这样吧 我把那个删了吧= =用处也不大

**Comment by lion1991** [comment]
好的,辛苦.

**Comment by lion1991** [comment]
提示radius.userinfo' doesn't exist 怀疑是radius出了什么问题...

**Comment by lion1991** [comment]
同时进行 php xcat dailyjob 的时候报错  PHP Notice:  Trying to get property of non-object in /home/wwwroot/xxxxx/app/Command/Job.php on line 798
之前是好的,莫不是修改了什么东西导致的.

  796   foreach($rbusers as $sinuser){
  797			$user=User::find($sinuser->userid);
  798			if($user->enable==1&&(strtotime($user->expire_in)>time()||strtotime($user->expire_in)<644447105)&&$user->transfer_enable>$user->u+$user->d)
  799			{
  800				$sinuser->delete();
  801				Radius::Add($user,$user->passwd);

**Comment by lion1991** [comment]
我还有一个一样的数据库网站.做备份用的.但是另外一个版本是6号的,那个进行操作没有问题的.新版本会出现此错误...

按照这个报错的命令.两个网站的执行select * from `userinfo` where `username` = 用户名 limit 1  均提示#1146 - Table 'radius.userinfo' doesn't exist  ...

**Comment by lion1991** [comment]
userinfo问题已修复!
