### ISSUE TITLE
python service.py 一直提示 server_pool.py:176 IPV4（ipv6） [Errno 98] Address already in use

### ISSUE THREAD

**Issue by wxhnizy** [glzjin/ss-panel-v3-mod#362]
@glzjin 我这里出现了整体宕机，麻烦你帮我看下错误出现在哪里？
前几天一直好好的，昨晚开始网站注册量猛增不少，今天中午就发现链接不上节点，查看客户端日志显示正常，但是访问google.com等网站出现 500 Internal Privoxy Error 更新PAC 显示错误。

重新安装服务器系统，重新部署前后端 导入网站数据库后，尝试重新链接客户端 依然显示正常，然而服务器端日志依然显示 
server_pool.py:176 IPV4 [Errno 98] Address already in use
server_pool.py:176  ipv6 [Errno 98] Address already in use

完整日志：
2016-10-26 17:02:32 INFO     db_transfer.py:495 db start server at port [] pass [] protocol [origin] obfs [plain]
2016-10-26 17:02:32 INFO     server_pool.py:138 starting server at [::]:
2016-10-26 17:02:32 WARNING  server_pool.py:151 IPV6 [Errno 98] Address already in use
2016-10-26 17:02:32 INFO     server_pool.py:164 starting server at 0.0.0.0:43298
2016-10-26 17:02:32 WARNING  server_pool.py:176 IPV4 [Errno 98] Address already in use

ssservice.logo
文件内 显示均与上面错误代码相同：只有PORT（端口） 不同 ~其他错误信息相同

**Comment by wxhnizy** [comment]
我虽然不知道这个错误是怎么发生的，但是我重新新建数据库以后 一切就正常了~ 希望 @glzjin 能看到这个问题，并且告诉我 这个问题为什么会发生 ~ 万分感谢

**Comment by wxhnizy** [comment]
上面的问题通过重建SQL得到临时的解决 但是问题依然存在，现在出现了 一些数据库中不存在的端口链接信息 错误代码依然是98 请问 GOOGLE以后有这样的问题 但是没有答案 ~可否帮忙解答下 谢谢 
只要节点断开 就是全部断开 ~问题比较致命 

![qq 20161027032919](https://cloud.githubusercontent.com/assets/21986327/19742087/10b14eca-9bf6-11e6-9214-1995bc73da26.png)

**Comment by glzjin** [comment]
@wxhnizy 请检查你是否运行了多个后端实例

**Comment by wxhnizy** [comment]
@glzjin 我在其他问题中也看到过这个解决办法，我找不到其他多余的后端所以 我 所有后端服务端都重新部署过~

**Comment by glzjin** [comment]
@wxhnizy netstat -antp

**Comment by wxhnizy** [comment]
@glzjin 好我再重新检查一遍

**Comment by wxhnizy** [comment]
@glzjin 使用netstat -antp 查看端口  我自己看了半天没发现什么不正常的（除了只有我自己在线以外）
下面是 几台后端 的查看情况 ~ 
![qq 20161027120751](https://cloud.githubusercontent.com/assets/21986327/19754249/54a55836-9c3e-11e6-86bc-b810e722ee88.png)
![qq 20161027120811](https://cloud.githubusercontent.com/assets/21986327/19754251/54de898a-9c3e-11e6-919b-7509a15bb565.png)
![qq 20161027120826](https://cloud.githubusercontent.com/assets/21986327/19754252/54e1e080-9c3e-11e6-90f5-694ba34ba94b.png)
![qq 20161027120845](https://cloud.githubusercontent.com/assets/21986327/19754250/54d18da2-9c3e-11e6-95bc-a618c0467564.png)
![qq 20161027120902](https://cloud.githubusercontent.com/assets/21986327/19754253/54e40f5e-9c3e-11e6-8fd8-a75333966ae3.png)

**Comment by wxhnizy** [comment]
@glzjin 难道是这两个python 的问题？有两台服务器 确实运行着 两个 python 但是没发现 SSS运行

**Comment by wxhnizy** [comment]
![qq 20161027122729](https://cloud.githubusercontent.com/assets/21986327/19754531/f291c50a-9c40-11e6-8916-e8f24ca24e0e.png)

**Comment by glzjin** [comment]
@wxhnizy 自己检查咯 反正就是端口被占了

**Comment by wxhnizy** [comment]
@glzjin 难能查出 是哪台服务器 端口被占用吗？

**Comment by wxhnizy** [comment]
@glzjin 能告诉我 一下 查找思路吗 我从昨晚弄到现在 一头雾水

**Comment by wxhnizy** [comment]
@glzjin 能否把 错误信息 列举下放到 WIKI里面 我能在网上的找到的 只有 
[errno 32] 读写错误
[errno 104]链接意外中断 跟32 差不多
[errno 110]不明
[errno 107]不明
[errno 24]系统资源不足
其他的就不知道了 例如 上面我遇到的 字面意思我看到是 地址被占用 我尝试排查端口 但是 排查方向貌似是错误的~

**Comment by glzjin** [comment]
反正 自己检查有没有影响监听这个端口的东西存在  一个是有其他程序占了 其他的 自己上网搜搜吧

**Comment by caiwenjie007** [comment]
我也遇到同样的问题了
