### ISSUE TITLE
 php xcat createAdmin之后报错

### ISSUE THREAD

**Issue by Bigblackbanner** [glzjin/ss-panel-v3-mod#364]
[root@MyCloudServer sss]# php xcat createAdmin

PHP Parse error:  syntax error, unexpected '$value' (T_VARIABLE) in /home/wwwroot/sss/vendor/aws/aws-sdk-php/src/functions.php on line 36

不知道怎么解决。

**Comment by glzjin** [comment]
@Bigblackbanner 升级 php 版本
