### ISSUE TITLE
为什么我安装Radius 目录文件下没有sql.comf？

### ISSUE THREAD

**Issue by Bigblackbanner** [glzjin/ss-panel-v3-mod#371]
为什么我安装Radius 目录文件下没有sql.comf？
![12](https://cloud.githubusercontent.com/assets/21064246/19783773/c41815a0-9cc5-11e6-9a84-1a49784e36c4.png)

**Comment by wxhnizy** [comment]
开始的的时候装过一次 我记得 好像路径变了吧~ 教程中是 /etc/raddb/sql.conf 而实际路径 ubuntu 与 cen 不同 得先确定下你的系统。

**Comment by wxhnizy** [comment]
你找找 /etc/目录下 有一个 *raddb/ 结尾的文件夹？或者 搜索下

**Comment by glzjin** [comment]
@Bigblackbanner 那就自己上网搜搜radius安装方法咯 对接上数据库就行了
