### ISSUE TITLE
莫名其妙全部500错误，打开debug求老大看看是啥回事？

### ISSUE THREAD

**Issue by wang259797** [glzjin/ss-panel-v3-mod#376]
老大我的站昨天好好的，今天就发现无法登录然后替换登录页面文件却全部开始报500错误找不到页面。。。打开debug模式报以下错误 但看了相关文件夹是777的可写权限。。。求老大指点。
![image](https://cloud.githubusercontent.com/assets/20319112/19826940/3e6a4980-9dcb-11e6-8e2a-0849c93fa4e3.png)

**Comment by glzjin** [comment]
@wang259797 自己检查上级文件夹能不能可写咯=、=

**Comment by wang259797** [comment]
@glzjin 已全是可写状态。。。

**Comment by glzjin** [comment]
@wang259797 那我就不知道了 我只能告诉你这样查 其他的 我解决不了 至于你怎么查 怎么解决 我无能为力
