### ISSUE TITLE
打开管理面板->用户列表出错

### ISSUE THREAD

**Issue by chenlinchet** [glzjin/ss-panel-v3-mod#377]
debug截图
![photo830139950966089666](https://cloud.githubusercontent.com/assets/18625758/19828467/e267030c-9df8-11e6-942d-6b82b3563eb2.jpg)
![photo830139950966089665](https://cloud.githubusercontent.com/assets/18625758/19828468/e6eed198-9df8-11e6-8587-745c06e8f067.jpg)

**Comment by glzjin** [comment]
@chenlinchet 自己去找个 qqwry.dat 覆盖到 storage 下

**Comment by chenlinchet** [comment]
@glzjin 前面这个弄好了，谢谢
还有个问题，我添加节点全都用的域名，但是在管理面板->节点列表中，有一个节点显示为域名，其他节点都显示ip

**Comment by glzjin** [comment]
@chenlinchet 自己检查你写的东西
