### ISSUE TITLE
最后添加的那几个定时任务分别代表什么功能啊

### ISSUE THREAD

**Issue by WhoRUa** [glzjin/ss-panel-v3-mod#380]
30 22 \* \* \* php /home/wwwroot/ss.panel/xcat sendDiaryMail
*/1 \* \* \* \* php /home/wwwroot/ss.panel/xcat synclogin
*/1 \* \* \* \* php /home/wwwroot/ss.panel/xcat syncvpn
0 0 \* \* \* php -n /home/wwwroot/ss.panel/xcat dailyjob
*/1 \* \* \* \* php /home/wwwroot/ss.panel/xcat checkjob  
*/1 \* \* \* \* php -n /home/wwwroot/ss.panel/xcat syncnas

这几个定时任务分别代表什么功能呢？我想把验证邮件和会员等级到期提醒之外的邮件功能关闭，该删除那个？

**Comment by Woophp** [comment]
关每日邮件？30 22 * * * php /home/wwwroot/ss.panel/xcat sendDiaryMail  不过不建议这么做。改数据库会好一点。

**Comment by glzjin** [comment]
@Woophp 是的

**Comment by WhoRUa** [comment]
@Woophp 更改那个表的那个字段？
