### ISSUE TITLE
IP地址不显示归属地

### ISSUE THREAD

**Issue by C-rouget** [glzjin/ss-panel-v3-mod#381]
无论是用户面板的“账户信息”面板还是后台的“用户资料”的IP，均不显示IP归属地(我记得以前是显示的,其他使用相同魔改面板的站点也都有)
版本:ss-panel-v3 glzjin mod 201610290900-v2 LTS
站点地址:https://www.miaoss.win
没有删除STAFF

**Comment by glzjin** [comment]
@C-rouget 自己检查下storage 下的 qqwry.dat 网上下载个覆盖

**Comment by C-rouget** [comment]
@glzjin OK解决了，感谢维护者抽出时间为解答我的问题
