### ISSUE TITLE
数据库的链接问题

### ISSUE THREAD

**Issue by zackvv** [glzjin/ss-panel-v3-mod#386]
主服务已经加了skip-name-resolve
主服务器。节点已经添加，nodeid对应好了
第二台服务器。MYSQL_HOST：已经添加好了主服务器信息。
主服务防火墙：*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
-A INPUT -s 127.0.0.1/32 -p tcp -m tcp --dport 3306 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 3306 -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
# Completed on Mon Oct 31 17:03:14 2016

第二台同意出现这种问题    raise_mysql_exception(self.__data)
  File "/usr/lib/python2.6/site-packages/cymysql/err.py", line 142, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/lib/python2.6/site-packages/cymysql/err.py", line 135, in _check_mysql_exception
    raise errorclass(errno,errorvalue)
OperationalError: (1045, u"Access denied for user 'root'@'47.88.节点ip.34' (using password: YES)")

请问这种情况是哪里配置错了么？

**Comment by glzjin** [comment]
@zackvv 数据库账户信息出错

**Comment by zackvv** [comment]
第二台服务器userapiconfig.py里面的配置，我检查了n遍，大神请看
# Mysql
MYSQL_HOST = '172.106.xx.44'     这个填写的是主服务器的ip
MYSQL_PORT = 3306
MYSQL_USER = 'xxxx'                  这个是填的主服务器ip/phpmyadmin登录名root
MYSQL_PASS = 'xxx'                    这个是填的主服务器ip/phpmyadmin登录密码
MYSQL_DB = 'sspanel'                这个是填的主服务器ip/phpmyadmin登陆进去的sspanel的数据库名
这样的配置应该不是数据库账户信息会出错啊

**Comment by glzjin** [comment]
@zackvv 请你自己上网搜索如何在数据库里添加远程访问用户

**Comment by zackvv** [comment]
非常感谢，已经找到方法，真心自己基础不够，谢谢！
