### ISSUE TITLE
php xcat dailyjob 报错

### ISSUE THREAD

**Issue by lion1991** [glzjin/ss-panel-v3-mod#39]
php xcat dailyjob 的时候报错 PHP Notice: Trying to get property of non-object in /home/wwwroot/xxxxx/app/Command/Job.php on line 798

795 $rbusers = RadiusBan::all();
796 foreach($rbusers as $sinuser){
797 $user=User::find($sinuser->userid);
798 if($user->enable==1&&(strtotime($user->expire_in)>time()||strtotime($user->expire_in)<644447105)&&$user->transfer_enable>$user->u+$user->d)
799 {
800 $sinuser->delete();
801 Radius::Add($user,$user->passwd);

		}
}
删除此段后运行没问题...

**Comment by glzjin** [comment]
并不是报错，你是把那个用户给禁用之后就删了吧。或者就是超流量之后就删了，没事了 
glzjin
2016年5月9日 下午5:56，lion1991 <notifications@github.com>写道：php xcat dailyjob 的时候报错 PHP Notice: Trying to get property of non-object in /home/wwwroot/xxxxx/app/Command/Job.php on line 798

795 $rbusers = RadiusBan::all();
796 foreach($rbusers as $sinuser){
797 $user=User::find($sinuser->userid);
798 if($user->enable==1&&(strtotime($user->expire_in)>time()||strtotime($user->expire_in)<644447105)&&$user->transfer_enable>$user->u+$user->d)
799 {
800 $sinuser->delete();
801 Radius::Add($user,$user->passwd);

    }


}
删除此段后运行没问题...
