### ISSUE TITLE
没有VPN统一流量结算

### ISSUE THREAD

**Issue by jimorsm** [glzjin/ss-panel-v3-mod#390]
anyconnect节点是按照下面教程做的：https://www.zhaoj.in/read-2904.html
https://mengyang.wang/anyconnect-node-mb/
radius server 因为安装的是新版本，自己参照着网上配置的
启用了sql和sqlcounter模块，也都配置了。导入的是你wiki里的sql，唯独dialup.conf找不到对应的修改
计划任务也都添加了，查看cron.log也没有报错。流量记录只有统一验证，没有VPN统一流量结算

另外看了wiki还是不明白怎么添加anyconnect节点，看wiki的意思是要先添加一个vpn节点？
需要实际部署vpn还是只要添加一个vpn类节点，填上radius服务的地址就好了？
但是这么做也是离线，显示黄色

**Comment by glzjin** [comment]
@jimorsm 1.默认是有结算的，没有的话自己想办法补齐。
2.在线状态只有ss节点能上报，其他类型的都是黄色。

**Comment by jimorsm** [comment]
dalao
找不到是哪儿方面有问题啊，能否告知dialup.conf的作用呢？
radius server那边，按照资料改了/etc/raddb/mods-available/sql
/etc/raddb/sites-enabled/inner-tunnel 和 /etc/raddb/sites-enabled/default 里也启用了sql
/etc/raddb/mods-enabled/sqlcounter 里面也添加了monthlytrafficcounter
/etc/raddb/dictionary 里那两行也添加了

有别的什么会影响这个功能么？

**Comment by glzjin** [comment]
@jimorsm 我也不知道 反正你自己配置好radius能和MySQL对接就好 radius安装请自行研究

**Comment by jimorsm** [comment]
和mysql对接没问题，认证也没问题，就是不统计流量
VPN/Radius基础 这个类型的节点没建好是否有影响？
若要设置radius节点，类型选了这个，加密方式也是填：VPN/Radius基础 ？

**Comment by glzjin** [comment]
@jimorsm 那你就自己找找anyconnect怎么上报流量咯 我这里没义务教你

**Comment by jimorsm** [comment]
哦，好的我再找找。那么说和VPN/Radius基础 这个类型的节点设置没设置好没关系对吧？我看wiki还以为添加一个anyconnect的节点就要添加一个VPN节点

**Comment by glzjin** [comment]
@jimorsm 这个也需要添加 radius验证方式 反正自己慢慢弄吧

**Comment by jimorsm** [comment]
dalao，不好意思我又来了，我能保证radius配置是对的，  搭建ASN RADIUS Admin能看到流量统计，查看数据库radacct表也是有记录的，但是面板里就是没有vpn流量统计
![image](https://cloud.githubusercontent.com/assets/3843791/20027227/e5c3ab5e-a316-11e6-86ec-13041541fefc.png)

**Comment by glzjin** [comment]
@jimorsm 你自己检查anyconnect有没有正确的上报流量咯 其他我管不着

**Comment by jimorsm** [comment]
@glzjin 有上报的

**Comment by glzjin** [comment]
@jimorsm 有上报 这里就会有同步 还有这种对接问题自己想办法吧 我没义务解决这种问题

**Comment by glzjin** [comment]
@jimorsm 不过看你那么热情，一句话不说也不好，检查 */1 * * * * php /home/wwwroot/ss.panel/xcat syncvpn
