### ISSUE TITLE
无法自定义协议、混淆

### ISSUE THREAD

**Issue by yhyy135** [glzjin/ss-panel-v3-mod#392]
按照教程在后端  user-config.json 中指定了协议、混淆，但注册用户只能使用与后端相同的协议、混淆配置才能正常使用 ssr，否则客户端空连 / 错误，后端报错如图所示。请问如何实现用户自定义协议，混淆？
![qq 20161102131044](https://cloud.githubusercontent.com/assets/9324793/19930103/d9065f78-a141-11e6-874e-4bad34e46949.png)

**Comment by yhyy135** [comment]
@glzjin

**Comment by dxhebei** [comment]
节点配置那里打开开关就可以了，这个我实验过了。
我现在还遇到节点的状态都是黄色的，节点也不显示在线人数，不显示流量，不知道问题出在哪里。
