### ISSUE TITLE
修改config后无法创建管理员

### ISSUE THREAD

**Issue by bcao1225** [glzjin/ss-panel-v3-mod#393]
提示：PHP Parse error:  syntax error, unexpected '$value' (T_VARIABLE) in /home/wwwroot/www.axed.ml/vendor/aws/aws-sdk-php/src/functions.php on line 36

**Comment by fred1653** [comment]
安装composer

**Comment by bcao1225** [comment]
感谢～～

**Comment by lithromantic** [comment]
问题解决了吗？

**Comment by bcao1225** [comment]
问题已解决，安装composer
