### ISSUE TITLE
自动任务无法执行，日志如下

### ISSUE THREAD

**Issue by thomas0612** [glzjin/ss-panel-v3-mod#394]
日志如下  解压更新安装的

root@vps88629:~# php -n /home/wwwroot/xxx.com/xcat dailyjob

Warning: fopen(/home/wwwroot/xxx.com/storage/qqwry.dat): failed to open stream: No such file or directory in /home/wwwroot/xxx.com/app/Utils/QQWry.php on line 26

Warning: unlink(/home/wwwroot/xxx.com/storage/qqwry.dat): No such file or directory in /home/wwwroot/xxx.com/app/Command/Job.php on line 214

Warning: rename(/home/wwwroot/xxx.com/storage/qqwry.dat.bak,/home/wwwroot/xxx.com/storage/qqwry.dat): No such file or directory in /home/wwwroot/xxx.com/app/Command/Job.php on line 215

**Comment by glzjin** [comment]
@thomas0612 自己下个qqwry.dat 到storage目录下

**Comment by thomas0612** [comment]
目录下有该文件...

**Comment by glzjin** [comment]
@thomas0612 文件损坏

**Comment by thomas0612** [comment]
2333我去下一个试试

**Comment by thomas0612** [comment]
奥  对了有些用户出现偷跑流量的情况
和在数据库直接改了节点等级有关系么= =
