### ISSUE TITLE
zfbjk 5ebe88b版本 商品自动续费问题

### ISSUE THREAD

**Issue by Cnievana** [glzjin/ss-panel-v3-mod#395]
此版本下的商品自动续费时仅更新bought表中的renew字段而没有生成一个新的数据行
这将会导致查账困难，面板用户可能通过此漏洞谎称自己的付款未到账

解决方法
在自动续费时在bought表生成一个新的renew=0的购买记录以方便查账

**Comment by glzjin** [comment]
已修复
