### ISSUE TITLE
无法修改自定义加密和混淆参数

### ISSUE THREAD

**Issue by sephrioth** [glzjin/ss-panel-v3-mod#399]
站点是 renle.click
更新过后, 发现用户无法修改加密方式和混淆, 提交后报错, 弹出一个空弹层或者显示failed.. 抓包后错误如图.
已经尝试过把 edit.tpl和 usercontroller.tpl 修改为官方原版, 还是一样的报错...

![untitled-1](https://cloud.githubusercontent.com/assets/4231328/20027245/accd6596-a349-11e6-9a73-b68e32ae6d2d.png)

**Comment by glzjin** [comment]
@sephrioth network那里 自己上网搜搜chrome怎么抓包吧

**Comment by sephrioth** [comment]
其余的属性都可以正常提交, 就是ss相关3项不行.

![screenshot 2016-11-05 11 51 21](https://cloud.githubusercontent.com/assets/4231328/20027389/3354d3d4-a34e-11e6-8781-b3a891e83787.jpg)

**Comment by glzjin** [comment]
@sephrioth 那你看返回内容呀

**Comment by sephrioth** [comment]
找到原因了, 改动的时候不小心把 Tools.php 改错了...谢谢!
