### ISSUE TITLE
好像缺少js 退出帐号以后无法正常登录 应该补一下js

### ISSUE THREAD

**Issue by pcskys** [glzjin/ss-panel-v3-mod#4]
好像缺少js 退出帐号以后无法正常登录 应该补一下js

**Comment by glzjin** [comment]
如果你能修复 请提交pr 并没有发现你说的问题
glzjin
2016年5月1日 下午10:03，pcskys <notifications@github.com>写道：好像缺少js 退出帐号以后无法正常登录 应该补一下js

**Comment by pcskys** [comment]
好吧，那我去换个浏览器试试，也许是本地问题
我用的是作者你在7小时前更新的这个版本 5d6080e

**Comment by glzjin** [comment]
请提供具体的哪一部分不正常 能提供截图最好

**Comment by 619096932** [comment]
目前使用过2次更新都有使用 存在同几个问题！
1  登陆后不刷新页面不会主动跳转到后台，也不会显示登陆成功，
2  后台生成邀请码！权限0的验证码数据库有记录，但是前台能看到10个左右
3  点击邀请码！ 填写完信息，同意tos后，页面也不会发生变化！但是实际上注册成功！后台数据库有记录
4注册失败也不会提示任何信息！

**Comment by 619096932** [comment]
应该和楼上的反应的问题是一样的

**Comment by glzjin** [comment]
你单独开个issue好吗？
glzjin
2016年5月2日 上午1:07，619096932 <notifications@github.com>写道：应该和楼上的反应的问题是一样的

**Comment by glzjin** [comment]
都没有发现你说的问题=、=你用的是IE吧
glzjin
2016年5月2日 上午7:16，glzjin <glzjin@zhaojin97.cn>写道：你单独开个issue好吗？
glzjin
2016年5月2日 上午1:07，619096932 <notifications@github.com>写道：应该和楼上的反应的问题是一样的

**Comment by glzjin** [comment]
哦对了，十个邀请码是刻意的，反正用了之后后面的会补齐。
glzjin
2016年5月2日 上午7:17，glzjin <glzjin@zhaojin97.cn>写道：都没有发现你说的问题=、=你用的是IE吧
glzjin
2016年5月2日 上午7:16，glzjin <glzjin@zhaojin97.cn>写道：你单独开个issue好吗？
glzjin
2016年5月2日 上午1:07，619096932 <notifications@github.com>写道：应该和楼上的反应的问题是一样的
