### ISSUE TITLE
请教一下telegram bot的问题。

### ISSUE THREAD

**Issue by nik0chen** [glzjin/ss-panel-v3-mod#400]
你好，请问一下，我执行php xcat setTelegram 的时候报错。
我的网站已经用 Let's Encrypt 启用https连接了。
PHP Fatal error:  Uncaught exception 'TelegramBot\Api\HttpException' with message 'Bad Request' in /home/wwwroot/www.XXX.com/vendor/telegram-bot/api/src/BotApi.php:253
Stack trace:
#0 /home/wwwroot/www.XXX.com/vendor/telegram-bot/api/src/BotApi.php(236): TelegramBot\Api\BotApi::curlValidate(Resource id #65)
#1 /home/wwwroot/www.XXX.com/vendor/telegram-bot/api/src/BotApi.php(205): TelegramBot\Api\BotApi->executeCurl(Array)
#2 /home/wwwroot/www.XXX.com/vendor/telegram-bot/api/src/BotApi.php(370): TelegramBot\Api\BotApi->call('setWebhook', Array)
#3 /home/wwwroot/www.XXX.com/app/Command/XCat.php(156): TelegramBot\Api\BotApi->setWebhook('http://www.XXX...')
#4 /home/wwwroot/www.XXX.com/app/Command/XCat.php(34): App\Command\XCat->setTelegram()
#5 /home/wwwroot/www.XXX.com/xcat(11): App\Command\XCat->boot()
#6 {main}
  thrown in /home/wwwroot/www.XXX.com/vendor/telegram-bot/api/src/BotApi.php on line 253

**Comment by nik0chen** [comment]
解决。。

**Comment by klmmlk** [comment]
我的哥 我也遇见这个问题，求解决方法
