### ISSUE TITLE
貌似魔改版不支持UDP转发啊 测试几遍。还是说必须要安装ssshell-jar

### ISSUE THREAD

**Issue by ss6916** [glzjin/ss-panel-v3-mod#401]
貌似不支持UDP转发 测试几遍。还是说必须要安装ssshell-jar

**Comment by glzjin** [comment]
@ss6916 什么类型的端口？

**Comment by ss6916** [comment]
@glzjin 后来把前端后端放一起没有安装ssshell，就可以了，应该是网络的原因。但是后来又分开 tcp也连不上了 后端到前端的3306连接是wait状态，防火墙关了，mysql也设置了远程访问，你说的端口我还没明白你说的什么诶

**Comment by glzjin** [comment]
@ss6916 什么年代了你还用ssshell？

**Comment by ss6916** [comment]
@glzjin 我没用ssshell啊 我的哥

**Comment by glzjin** [comment]
@ss6916 你问的是普通端口还是单端口多用户？

**Comment by ss6916** [comment]
@glzjin 普通端口

**Comment by glzjin** [comment]
@ss6916 那就得了 你那片udp抽了

**Comment by ss6916** [comment]
@glzjin 赵大大，MANAGE_BIND_IP = '127.0.0.1'后端和前端不在一起这个位子是要写前端吗

**Comment by 85204** [comment]
@ss6916 一定要保证防火墙开放了udp端口，我今天也试了很久，才发现是防火墙的原因
可以先关闭防火墙，然后看看走了哪些端口，再把防火墙的这些端口开放出来
@glzjin udp使用的端口也是跟tcp端口池一样的吗，开放10000号以上的udp端口就保证能用了吧
我尝试使用udp over tcp 失败了，是服务器端没有这个功能吗
