### ISSUE TITLE
主页打开http500呢 

### ISSUE THREAD

**Issue by Dalybeal** [glzjin/ss-panel-v3-mod#407]
按照赵大的public文件夹里没有生成网页文件夹，不知道是不是漏了某些步骤呢  对着安装说明装的呢，debug也开了图片发到你邮箱了  麻烦赵大解决一下哦谢谢

**Comment by Dalybeal** [comment]
wx852.cn

**Comment by glzjin** [comment]
@Dalybeal 你编辑文件的时候加错了东西

**Comment by Dalybeal** [comment]
可以问一下具体是什么加错了吗

**Comment by glzjin** [comment]
@Dalybeal 自个儿找
