### ISSUE TITLE
修改商品属性后购买记录页无法访问

### ISSUE THREAD

**Issue by sephrioth** [glzjin/ss-panel-v3-mod#414]
如图。。。 地址也在图中。

之前也发生过删除某节点后， 访问speedtest和 /admin/detect/log 报错， 把节点重新添加回去错误就消失了， 不知道是否有联系。

![image](https://cloud.githubusercontent.com/assets/4231328/20167651/bca5bb5a-a757-11e6-8c44-dc3248e70c77.png)

**Comment by glzjin** [comment]
@sephrioth 别自己瞎删商品 商品只能下架

**Comment by sephrioth** [comment]
节点也是么？  之前是加了几个商品测试了下， 测试好了就删掉了。。。。
那还有办法补救么。。
