### ISSUE TITLE
单端口问题

### ISSUE THREAD

**Issue by jeffreys125** [glzjin/ss-panel-v3-mod#415]
用户只要修改分配的混淆参数后还可以连上，而且扣的流量算到了开端口的那个用户上。

**Comment by glzjin** [comment]
@jeffreys125 发下具体的举例？

**Comment by jeffreys125** [comment]
@glzjin  我创建了用户a用来开8080端口来承载多用户。。。然后节点什么的都是按照步骤来的。。用户b，会分配到个混淆参数4c88ffd1.baidu.com  然后如果用户b把分配的混淆参数随便填都可以连上ssr。。并且流量都算到了我的自己创建的用户a的头上

**Comment by glzjin** [comment]
@jeffreys125 你的各项配置都截图下 还有你的后端版本是？

**Comment by glzjin** [comment]
@jeffreys125 还有发个例子ssr://我来连上试试

**Comment by jeffreys125** [comment]
@glzjin ss://aHR0cF9zaW1wbGU6YXV0aF9zaGExOmNoYWNoYTIwOmw3c3hhcEAxMjMuMjA3LjI4LjExODoxMzcvTjJKbE9HWXpMbk56Y20xc0xtZGg=

**Comment by glzjin** [comment]
@jeffreys125 无法导入

**Comment by jeffreys125** [comment]
@glzjin
我创建的用户a设置：
链接端口 137
自定义加密  chacha20
自定义协议 auth_sha1
自定义协议参数 
自定义混淆方式 http_simple

节点设置 

节点名称 test
节点地址 137
加密方式 chacha20
流量比例 1

**Comment by jeffreys125** [comment]
@glzjin ssr://MTIzLjIwNy4yOC4xMTg6MTM3OmF1dGhfc2hhMTpjaGFjaGEyMDpodHRwX3NpbXBsZTpiRGR6ZUdGdy8_b2Jmc3BhcmFtPU5HTTRPR1ptWkRFdWMzTnliV3d1WjJFPSZyZW1hcmtzPWRHVnVZMlZ1ZENBdElERXpOeURucTZfbGo2UGxqWlhucTZfbGo2UGxwSnJubEtqbWlMYz0=
