### ISSUE TITLE
用户中心的流量记录无法打开

### ISSUE THREAD

**Issue by lion1991** [glzjin/ss-panel-v3-mod#42]
![image](https://cloud.githubusercontent.com/assets/18396082/15116840/833574e8-1637-11e6-8026-5cba0b92b8f8.png)

...节点我没有变动...

**Comment by glzjin** [comment]
要么就是你后端的节点ID填错了，这里把debug关掉就行了。

**Comment by lion1991** [comment]
刚尝试了一下把数据库导出又重新导入后竟然打开了,只不过个人流量记录没有了.这真是个神奇的问题...
