### ISSUE TITLE
用户有效期过期流量不重置

### ISSUE THREAD

**Issue by Woophp** [glzjin/ss-panel-v3-mod#421]
计划任务正常运行，只是部分用户不重置，其余用户是正常重置的…然后我对比两种用户发现，差别在于没有重置的用户是“从未签到”状态…
经过开新账号改过期时间测试，发现没有签到过的确实不会被重置！登录那个帐户并签到后，下一分钟计划任务运行就被重置了！

**Comment by glzjin** [comment]
@Woophp 你那个用户的流量都等于要重置成的流量了那还重置个啥？

**Comment by Woophp** [comment]
@glzjin 并没有，我设置的重置流量为0G，注册初始流量为1G…

**Comment by Woophp** [comment]
@glzjin 根据你的提醒，看了Job.php 658行貌似另外还判断了：等级到期是否重置、“当前流量”不等于“等级到期时重置为的流量值”！
774行貌似也还判断“账户到期时是否重置”，流量是否等于“账户到期时重置为的流量值”，这两个功能不是应该不冲突的嘛？
