### ISSUE TITLE
安装的时候找不到user.ini 文件

### ISSUE THREAD

**Issue by aliseree** [glzjin/ss-panel-v3-mod#423]
![image](https://cloud.githubusercontent.com/assets/17938730/20247265/099bd086-aa03-11e6-8d3f-e7aa170fd380.png)
我在安装的时候用tmp git 的时候这个文件夹已经存在并且有文件占用，所以我就用tmps了，然后在执行下一步修改一些权限的时候
[root@vultr vhost]# cd /home/wwwroot/ss.panel/
[root@vultr ss.panel]# chattr -i .user.ini

这个user.ini找不到，找不到问题的解决方法，请指教，谢谢！

**Comment by wxliuxh** [comment]
没有的话这一步就忽视啊...无语.又不是所有环境都会生成.user.ini
