### ISSUE TITLE
单端口多用户问题

### ISSUE THREAD

**Issue by 82604716** [glzjin/ss-panel-v3-mod#424]
作者您好，按照您的方式  设置单端口多用户  
第一个用户可以正常 使用 
教程好像说的不大清楚我是看源码才能看到 
$System_Config[‘mu_regex’]=‘%5m%id.%suffix’;
实际生成的值是： multi_user_host_table: {'d1ccb1.zhaoj.in': 1L}    d1ccb1.zhaoj.in
这一段的值 是需要 写到混淆参数值里面 才能顺利的通过验证 
不知道我理解的对不对。

如果这个是这样的话 接下来我添加第二个用户 同样是8080端口 这时候
就会告诉我more than one user use the same port [8080]
然后上面的验证值 就不生成了 一直就只有{'d1ccb1.zhaoj.in': 1L}

但是我把第二个用户的  单端口多用户承载端口 开关关掉就 这时候他又生成了 {'d1ccb1.zhaoj.in': 1L, '2447d5.zhaoj.in': 5L}

感觉很奇怪。
麻烦赐教谢谢

**Comment by glzjin** [comment]
自己看wiki
