### ISSUE TITLE
ios点击SSR链接Shadowrocket提示无效url

### ISSUE THREAD

**Issue by WayChan** [glzjin/ss-panel-v3-mod#425]
ios端点击SSR链接，Shadowrocket提示无效url，同时扫描SSR 3.8.3之后的版本会提示无效URL，目前桌面端用的是SSR 3.9.4，扫描正常。同时扫描3.8.3之前的二维码正常。同时建议生成的SSR链接里面包含备注的信息。

**Comment by glzjin** [comment]
@WayChan 1.ssr 3.8.3+的链接是ssr所定义的的链接格式生成的。
2.shadowrocket扫描问题请向shadowrocket作者反馈。
3.备注信息只有在ssr混淆和协议时才会被启用，其余使用原版协议和不启用混淆的时候只会生成最普通的ss打头的链接。

**Comment by WayChan** [comment]
经过确认是其app更新后导致的，不好意思。
