### ISSUE TITLE
重置密码链接打不开是什么原因

### ISSUE THREAD

**Issue by lbb666** [glzjin/ss-panel-v3-mod#429]
邮件能收到，点击链接不能打开网站,用的是smtp

**Comment by e8732** [comment]
首先检查链接地址，例如重置密码邮件内的地址是否为https

**Comment by lbb666** [comment]
确实是https的问题，是要开启证书吗

**Comment by lbb666** [comment]
已经解决了谢谢

**Comment by oliutiano** [comment]
怎么解决的？

**Comment by lbb666** [comment]
账号发我帮你重置吧 发自网易邮箱手机版 在2017年03月15日 11:21 ，oliutiano写道： 怎么解决的？ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.
