### ISSUE TITLE
面板的IP记录

### ISSUE THREAD

**Issue by leosejin** [glzjin/ss-panel-v3-mod#430]
赵辅导员好，
用了CDN导致面板的登录IP不对，在对nginx升级并且加了上了real IP模块后启用了CDN面板记录还是CDN的IP地址，下面是新的nginx编译参数
nginx version: nginx/1.4.7
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) 
TLS SNI support enabled
configure arguments: --user=www --group=www --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module --with-http_gzip_static_module --with-ipv6 --with-http_realip_module
![qq 20161115224927](https://cloud.githubusercontent.com/assets/20087548/20310159/d38344dc-ab85-11e6-87b4-3cfb36acef82.png)
谢谢赵老师！

**Comment by glzjin** [comment]
@leosejin 你需要自己参考real ip设置让程序获得正确的IP

**Comment by leosejin** [comment]
谢谢赵老师，我去找方法。
