### ISSUE TITLE
无限重定向，报错500。

### ISSUE THREAD

**Issue by WayChan** [glzjin/ss-panel-v3-mod#435]
看了config.php里面推荐使用redis，但是开启这个功能之后无限重定向500。但是cookies方式的话，假设设置的时间为十分钟，在这十分钟内即使你继续操作，到点也会清除，根据网上资料把时间改成0直接点击登陆就被清除，无限登陆。改成session方式有点复杂，还在研究。所以是否推荐redis？

**Comment by glzjin** [comment]
@WayChan 不

**Comment by WayChan** [comment]
@glzjin OK，了解。谢谢

**Comment by mingsire** [comment]
http://blog.free-gfw.club/  兄弟帮我看看这个站点办

**Comment by WayChan** [comment]
已经解决，魔改版前端默认需要密码连接redis，所以密码设置为空的时候，会导致无限重定向。只需要开启redis密码连接功能即可正常使用。
