### ISSUE TITLE
赵大，前端问题，所有配置都弄好了，可以网页依旧显示nginx，是怎么回事啊？

### ISSUE THREAD

**Issue by masonyeung** [glzjin/ss-panel-v3-mod#440]
按照教程完成了所有配置，也没有报错，然后装完打开主页，还是nginx页面。。。

**Comment by masonyeung** [comment]
server
    {
        listen 80;
        #listen [::]:80;
        server_name www.sabia.top;
        index index.html index.htm index.php default.html default.htm default.php;
        root  /home/wwwroot/www.sabia.top/public;

        include none.conf;
        #error_page   404   /404.html;
        location ~ [^/]\.php(/|$)
        {
            # comment try_files $uri =404; to enable pathinfo
            try_files $uri =404;
            fastcgi_pass  unix:/tmp/php-cgi.sock;
            fastcgi_index index.php;
            include fastcgi.conf;
            #include pathinfo.conf;
        }

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
        {
            expires      30d;
        }

        location / {
                try_files $uri $uri/ /index.php$is_args$args;
        }

        location ~ .*\.(js|css)?$
        {
            expires      12h;
        }

        access_log off;
    }

**Comment by masonyeung** [comment]
另外，防火墙3306端口也检查过，没有问题。

**Comment by masonyeung** [comment]
赵大，我改nginx.conf搞定了，不知道这方法是否可行？

**Comment by Mainvooid** [comment]
同样的问题，求解?
