### ISSUE TITLE
中科大cdn挂了，导致网页打开很慢

### ISSUE THREAD

**Issue by 85204** [glzjin/ss-panel-v3-mod#441]
国内好像没有什么好用的了，发现fonts.googleapis.com本来就在国内，就把它换回来了

打开以下文件，搜索fonts.lug.ustc.edu.cn并替换fonts.googleapis.com

public/theme/material/css 文件夹下.css文件
resources/views/material/header.tpl 
resources/views/material/user/main.tpl 
resources/views/material/admin/main.tpl 

赵大看一下有没有遗漏，我测试的好像没什么问题了

**Comment by glzjin** [comment]
你网络问题
