### ISSUE TITLE
怎么清理已用流量为零的用户呢？

### ISSUE THREAD

**Issue by WhoRUa** [glzjin/ss-panel-v3-mod#443]
面板->用户列表 里的 已用流量 的数据 所对应的 数据库字段是那个表的那个字段呢？
我想写个定时清理用户的脚本，定时删除 已用流量=0 的用户的数据，该怎么做才好？我的办法是定时清理数据库

**Comment by a86913179** [comment]
仔细看config.php，每一行看一分钟

**Comment by Mainvooid** [comment]
配置文件自己设置。
