### ISSUE TITLE
等级到期时间到期后，用户等级不会重置。

### ISSUE THREAD

**Issue by WayChan** [glzjin/ss-panel-v3-mod#444]
此条可删除

**Comment by glzjin** [comment]
@WayChan 你自己计划任务不正常运行瞎改个啥？

**Comment by WayChan** [comment]
@glzjin 计划任务没问题，不过等级不重置为真。只是考虑到目前即使重置了等级，但是由于连接上过了隐藏节点，哪怕重置了等级也无用。所依采取了您原mod的删除机制。
