### ISSUE TITLE
修改节点弹出空白框

### ISSUE THREAD

**Issue by leosejin** [glzjin/ss-panel-v3-mod#446]
赵辅导员，

在给面板配置了云盾的CDN之后，重新编译了nginx，加了REAL IP模块和根据cf网站中的形式配置了nginx中的conf参数 

nginx version: nginx/1.4.7
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) 
TLS SNI support enabled
configure arguments: --user=www --group=www --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module --with-http_gzip_static_module --with-ipv6 --with-http_realip_module
################################################################################
        set_real_ip_from 59.56.79.0/24;
        set_real_ip_from 23.252.163.0/24;

        real_ip_header X-Forwarded-For;
        real_ip_recursive on;
###############################################################################
这个时候的用户登录显示的是真实的IP地址，但是admin在管理修改节点信息的时候点击修改 弹出的是白框，而且并没有修改完成。
开启debug之后点击用户的信息和列表会报错
![qq 20161119203921](https://cloud.githubusercontent.com/assets/20087548/20455668/418299ba-ae9c-11e6-855a-5d611ea32951.png)
config的信息为
#是否将登陆线程和IP绑定
$System_Config['enable_login_bind_ip']='false';
#异地登陆提示
$System_Config['login_warn']='false';

谢谢赵辅导员！

**Comment by a86913179** [comment]
为什么要这么麻烦？直接php开头添加把[REMOTE_ADDR]转为[HTTP_X_FORWARDED_FOR]，如果是CF的话专门有头[HTTP_CF_CONNECTING_IP]

**Comment by leosejin** [comment]
问题是现在可以获取IP了，但是修改节点的时候不会显示修改成功，而是弹出一个白框来，请问这个是哪儿有了问题呢？
