### ISSUE TITLE
添加新节点时弹出空白框

### ISSUE THREAD

**Issue by mxihan** [glzjin/ss-panel-v3-mod#448]
添加新节点时弹出空白框，新加节点也用不了，debug不报错
后端没有问题
站点mxihan.xyz

**Comment by mxihan** [comment]
只有这个用浏览器抓到的
jquery.min.js:4 PUT http://mxihan.xyz/admin/node/19 500 (Internal Server Error)send @ jquery.min.js:4ajax @ jquery.min.js:4submitHandler @ edit:506d @ jquery.validate.min.js:4(anonymous function) @ jquery.validate.min.js:4dispatch @ jquery.min.js:3r.handle @ jquery.min.js:3
edit:543 Uncaught ReferenceError: data is not defined(…)error @ edit:543i @ jquery.min.js:2fireWith @ jquery.min.js:2z @ jquery.min.js:4(anonymous function) @ jquery.min.js:4
debug不报错

**Comment by glzjin** [comment]
@mxihan networking那一块 不是console的的

**Comment by mxihan** [comment]
{error: {type: "TelegramBot\Api\HttpException", message: "Bad Request",…}}
error
:
{type: "TelegramBot\Api\HttpException", message: "Bad Request",…}
Name

{error: {type: "TelegramBot\Api\HttpException", message: "Bad Request",…}}
error
:
{type: "TelegramBot\Api\HttpException", message: "Bad Request",…}
Name
就是这些

**Comment by glzjin** [comment]
@mxihan 你没配置好 telegram bot

**Comment by mxihan** [comment]
解决了，谢啦
对于私聊我表示很抱歉(๑o̴̶̷̥᷅﹏o̴̶̷̥᷅๑)
