### ISSUE TITLE
智能线路怎么情况下会是在线图标

### ISSUE THREAD

**Issue by xiadena** [glzjin/ss-panel-v3-mod#45]
之前偶尔会是绿色的在线图标，但现在是红色三角图标，虽不影响使用但是略强迫症

**Comment by glzjin** [comment]
check job 每分钟的任务 不需要的话可以按照说明关掉这个功能
glzjin
2016年5月10日 上午4:11，xiadena <notifications@github.com>写道：之前偶尔会是绿色的在线图标，但现在是红色三角图标，虽不影响使用但是略强迫症
