### ISSUE TITLE
按照您的说明设置单端口多用户出问题

### ISSUE THREAD

**Issue by ljk4160** [glzjin/ss-panel-v3-mod#452]
所有都能用,就是设置了单端口多用户后
连接上无法联网.

后端前端都设置了混淆.
用户和节点也设置了一样的端口.
正常连接可以使用,但是使用单端口多用户的配置就是连不上.求助

**Comment by glzjin** [comment]
请发日志。

**Comment by ljk4160** [comment]
感谢回复,已经解决了,是因为前端版本太低导致的.更新一下就好了
