### ISSUE TITLE
请教大佬 ssr连接无网

### ISSUE THREAD

**Issue by 1mkzh** [glzjin/ss-panel-v3-mod#455]
防火墙已经关闭
python server.py
![python serverpy](https://cloud.githubusercontent.com/assets/21083195/20554573/dfc3cfd8-b197-11e6-98c9-87f551612b91.png)
ssserver.log
![ssserverlog](https://cloud.githubusercontent.com/assets/21083195/20554672/71974d04-b198-11e6-9d84-ca2a9c9056fc.png)

**Comment by Bigblackbanner** [comment]
8080端口被占用了，自己Kill一下咯~ 是不是Nginx或者Apache占用了8080 自己检查一下呗。

**Comment by 1mkzh** [comment]
@Bigblackbanner  多谢大佬 已解决
