### ISSUE TITLE
站库分离时数据库连接不上

### ISSUE THREAD

**Issue by leosejin** [glzjin/ss-panel-v3-mod#460]
赵辅导员好，
想把面板和数据库分开来放，另一台机器（2号）装好数据库之后把原数据导入进去，设置了用户和数据库，给了用户全局权限，主机连接为%所有；2号防火墙规则修该/关闭。结果主页打开都是错误。面板机器上的config信息已经修改。
config
# database 数据库配置
$System_Config['db_driver'] = 'mysql';
$System_Config['db_host'] = '172.111.11.111';
$System_Config['db_database'] = 'abcdefg';
$System_Config['db_username'] = 'sspanel';
$System_Config['db_password'] = 'J5tLwaJ7gSau';
$System_Config['db_charset'] = 'utf8';
$System_Config['db_collation'] = 'utf8_general_ci';
$System_Config['db_prefix'] = '';

前端 登陆页面的Debug
![qq 20161126202211](https://cloud.githubusercontent.com/assets/20087548/20640396/c427ef3e-b417-11e6-8c47-d5b630a7d187.png)
![qq 2016114](https://cloud.githubusercontent.com/assets/20087548/20640402/e04a2470-b417-11e6-8175-70fe0bd55466.png)
![161126203131](https://cloud.githubusercontent.com/assets/20087548/20640404/e5ec81e8-b417-11e6-88dd-21b995b8535a.png)

2号防火墙配置
-A INPUT -i lo -j ACCEPT 
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT 
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT 
-A INPUT -p tcp -m tcp --dport 3306 -j ACCEPT 
#-A INPUT -p tcp -m tcp --dport 3306 -j DROP 
-A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT 
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT 
-A INPUT -p icmp -j ACCEPT 
-A INPUT -i lo -j ACCEPT 
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT 
-A INPUT -j REJECT --reject-with icmp-host-prohibited 
-A FORWARD -j REJECT --reject-with icmp-host-prohibited 

一直困扰好多天了，小白一个 希望辅导员给予指点。不胜感谢！

**Comment by glzjin** [comment]
你自己编辑配置文件时候姿势不当 前面加了东西

**Comment by leosejin** [comment]
解决了，是面板机器的防火墙出现了问题，给赵大添麻烦了，抱歉。再次感谢！
