### ISSUE TITLE
数据库部分表编码 latin1，中文变成半角问号

### ISSUE THREAD

**Issue by 70599** [glzjin/ss-panel-v3-mod#466]
不是utf8的几个表都有中文乱码的问题。

截图：
http://ww3.sinaimg.cn/large/731801edjw1fa9c5y5bhdj20nf0q914u.jpg
请指教解决的办法，谢谢。

https://fredchan.ml

没有移除、修改过staff

**Comment by glzjin** [comment]
vi /etc/my.cnf

在[client]下添加
default-character-set=utf8

在[mysqld]下添加
default-character-set=utf8

**Comment by 70599** [comment]
@glzjin 
感谢回复。确认您的回复后，我已经删除了网站链接。

/etc/my.cnf 里没有 [client] 和 [mysqld] 字段。
/etc/my.cnf 文件内容：
```
#
# This group is read both both by the client and the server
# use it for options that affect everything
#
[client-server]

#
# include all files from the config directory
#
!includedir /etc/my.cnf.d
```

分别在 /etc/my.cnf.d/client.cnf 和 /etc/my.cnf.d/server.cnf 中找到了同名字段，修改重启数据库时出现以下错误，数据库没能启动：
```
mysqld[1429]: 2016-11-29 22:40:00 139876078229696 [ERROR] /usr/sbin/mysqld: unknown variable 'default-character-set=utf8'
```

**Comment by 70599** [comment]
参考[这里](http://qiita.com/pugiemonn/items/812eb7fadd5a55692755)，把 [mysqld] 下的 default-character-set=utf8 换成了 character-set-server=utf8 ，数据库成功启动。

但是之前的问号还是问号，工单中插入新的中文回复，新插入的部分也还是问号。

**Comment by 70599** [comment]
虽然没有报错，尝试把 [client] 下的 default-character-set=utf8 也换成了 character-set-server=utf8，但是问题照旧。

**Comment by glzjin** [comment]
@70599 你已经导入的数据库需要自己手动改编码
