### ISSUE TITLE
请教 单端口多用户错误:md5 is mismatch

### ISSUE THREAD

**Issue by 1mkzh** [glzjin/ss-panel-v3-mod#467]
已经检查过后缀设置 试过重新部署后端 无效 普通端口连接正常
各位大佬帮忙看看是什么地方出错了

ssserver.log 后面是重复的
![_3ey gn e02 w qo 5 aoq](https://cloud.githubusercontent.com/assets/21083195/20715212/6608776a-b689-11e6-83bf-cf77b6f8b686.png)

**Comment by feileb** [comment]
检查你前端config/.config.php里面的MU_SUFFIX，MU_REGEX和后端userapiconfig.py里面的MU_SUFFIX，MU_REGEX是不是一样的
