### ISSUE TITLE
无法登陆PC

### ISSUE THREAD

**Issue by wulikui** [glzjin/ss-panel-v3-mod#468]
登陆返回500错误

**Comment by glzjin** [comment]
请打开debug,f12抓返回包。

**Comment by wulikui** [comment]
![qq 20161130150342](https://cloud.githubusercontent.com/assets/4831344/20742917/4416b9b6-b70e-11e6-8717-ee9c76fc7776.png)

**Comment by glzjin** [comment]
开 debug

**Comment by wulikui** [comment]
这次用的火狐
![qq 20161130150859](https://cloud.githubusercontent.com/assets/4831344/20743051/006240cc-b70f-11e6-88ab-0cf8312bfea9.png)

**Comment by glzjin** [comment]
你开debug啊

**Comment by wulikui** [comment]
我这就是F12 开的 firebug啊。

**Comment by glzjin** [comment]
面板的debug啊 config里开
