### ISSUE TITLE
新加节点弹出空白框，只显示OK。节点并没有添加成功。

### ISSUE THREAD

**Issue by huya1121** [glzjin/ss-panel-v3-mod#469]
赵大大，
![qq 20161130140600](https://cloud.githubusercontent.com/assets/13938600/20741579/2f7bda7a-b706-11e6-8fbf-a879851ccad6.png)
debug没有错误。。crontab任务正常不报错。

**Comment by glzjin** [comment]
请打开debug,f12抓返回包。

**Comment by huya1121** [comment]
ReferenceError: data is not defined
.submitHandler/<.error()
create:539
n.Callbacks/i()
n.Callbacks/j.fireWith()
z()
.send/c/<()

**Comment by glzjin** [comment]
什么鬼 抓包 看返回

**Comment by huya1121** [comment]
![qq 20161130150842](https://cloud.githubusercontent.com/assets/13938600/20743041/f39046be-b70e-11e6-9e0d-35d1c3e9cac9.png)

**Comment by glzjin** [comment]
network

**Comment by glzjin** [comment]
http://www.cnblogs.com/fatfatdachao/p/4014221.html

**Comment by huya1121** [comment]
![qq 20161130151414](https://cloud.githubusercontent.com/assets/13938600/20743174/b0f99f5c-b70f-11e6-9d1e-b1b95c973767.png)
这样的。。。

**Comment by huya1121** [comment]
Request URL:https://ssr.huyal.com/500
Request Method:GET
Status Code:500 Internal Server Error
Remote Address:142.4.211.48:443
Response Headers
view source
Connection:keep-alive
Content-Length:4239
Content-Type:text/html; charset=UTF-8
Date:Wed, 30 Nov 2016 07:27:52 GMT
Server:nginx
X-Powered-By:PHP/7.0.7
Request Headers
view source
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4,ru;q=0.2
Connection:keep-alive
Cookie:__cfduid=d781b3cbbbe8895dc218b7821f13d3bc41477626860; uid=1; email=huya1121%40gmail.com; key=5f0cc071e90a57dea9cd55b15f08c57b0a75e8a885daa; ip=2cc09ca9be31bc5f969ab7c75f15d818; expire_in=1480566191
Host:ssr.huyal.com
Referer:https://ssr.huyal.com/admin/node/create
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
X-Requested-With:XMLHttpRequest

**Comment by huya1121** [comment]
Request URL:https://ssr.huyal.com/admin/node
Request Method:POST
Status Code:302 Found
Remote Address:142.4.211.48:443
Response Headers
view source
Connection:keep-alive
Content-Length:0
Content-Type:text/html; charset=UTF-8
Date:Wed, 30 Nov 2016 07:27:52 GMT
Location:/500
Server:nginx
X-Powered-By:PHP/7.0.7
Request Headers
view source
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4,ru;q=0.2
Connection:keep-alive
Content-Length:330
Content-Type:application/x-www-form-urlencoded; charset=UTF-8
Cookie:__cfduid=d781b3cbbbe8895dc218b7821f13d3bc41477626860; uid=1; email=huya1121%40gmail.com; key=5f0cc071e90a57dea9cd55b15f08c57b0a75e8a885daa; ip=2cc09ca9be31bc5f969ab7c75f15d818; expire_in=1480566191
Host:ssr.huyal.com
Origin:https://ssr.huyal.com
Referer:https://ssr.huyal.com/admin/node/create
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
X-Requested-With:XMLHttpRequest
Form Data
view source
view URL encoded
name:sg - 01
server:103.208.85.180
method:aes-256-cfb
custom_method:1
rate:1:2
info:新加坡高速节点（移动直连）
type:1
group:0
status:online
node_speedlimit:0
sort:0
class:1
node_bandwidth_limit:2040
bandwidthlimit_resetday:1
custom_rss:1

**Comment by glzjin** [comment]
你开了debug吗，看回应啊，你这个都没开面板的debug

**Comment by huya1121** [comment]
{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[01000]: Warning: 1265 Data truncated for column 'traffic_rate' at row 1 (SQL: insert into `ss_node` (`name`, `server`, `method`, `custom_method`, `custom_rss`, `traffic_rate`, `info`, `type`, `node_group`, `node_speedlimit`, `status`, `sort`, `node_ip`, `node_class`, `node_bandwidth_limit`, `bandwidthlimit_resetday`) values (SG - \u65b0\u52a0\u576101, 142.4.211.49, aes-256-cfb, 1, 1, 1:2, \u65b0\u52a0\u5761\u9ad8\u901f\u8282\u70b9\uff08\u79fb\u52a8\u76f4\u8fde\uff09, 1, 0, 0, \u5728\u7ebf, 0, 142.4.211.49, 1, 2190433320960, 1))","file":"\/home\/wwwroot\/ssr.huyal.com\/vendor\/illuminate\/database\/Connection.php","line":713}}

**Comment by glzjin** [comment]
@huya1121 节点倍率是小数你填个这玩意儿干啥

**Comment by huya1121** [comment]
我都没有看到节点倍率这个选项..

**Comment by glzjin** [comment]
@huya1121 流量倍率

**Comment by huya1121** [comment]
知道了。。。谢谢。。我写了一个比例  1：2。。这里应该直接写数字  谢谢赵大大耐心回答。。
