### ISSUE TITLE
有没有安装到部署多用户同端口的完整说明？

### ISSUE THREAD

**Issue by wangchunming** [glzjin/ss-panel-v3-mod#470]
如题，现在作者写的说明几乎看不懂，我想用shadowsocksR做ss pannel的后端，并且怎么样才能让ss pannel能跟不同服务器的后端对接让其自动开端口和密码？
另外，同端口多用户的说明也不完整，像是作者给自己记得笔记。

**Comment by zdingyu** [comment]
多看几遍说明就明白了

**Comment by a86913179** [comment]
这么清晰的教程你都看不懂，你还是别当站长了
