### ISSUE TITLE
怎样将 guzzle/guzzle 换成 guzzlehttp/guzzle？

### ISSUE THREAD

**Issue by 70599** [glzjin/ss-panel-v3-mod#471]
运行`php composer.phar update`或`php composer.phar install`后，输出`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`错误（？）警告信息。

运行`php composer.phar why guzzle/guzzle`调查后，输出`mailgun/mailgun-php  v1.7.2  requires  guzzle/guzzle (<4.0,>=3.8) `，发现是 mailgun 需求 guzzle/guzzle。

接着把`vendor/mailgun/mailgun-php/composer.json`中的`guzzle/guzzle`替换成`guzzlehttp/guzzle`，再运行`php composer.phar update`后，依然输出`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`，`vendor/mailgun/mailgun-php/composer.json`中的`guzzlehttp/guzzle`也变回了`guzzle/guzzle`。

我有什么搞错的地方吗？

**Comment by glzjin** [comment]
别瞎折腾

**Comment by 70599** [comment]
意思是我应该无视`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`吗？

我问问题不做尝试解决的努力，不合适，尝试了贴出过程，您说“瞎折腾”。
是要闹哪般（希望没有冒犯到您）？
