### ISSUE TITLE
用户流量负 并且帐号禁用 radius依旧认证

### ISSUE THREAD

**Issue by TShuiping** [glzjin/ss-panel-v3-mod#472]

**Comment by glzjin** [comment]
@TShuiping 检查你的计划任务

**Comment by TShuiping** [comment]
@glzjin 计划任务没问题

**Comment by glzjin** [comment]
@TShuiping 提供你的证明

**Comment by TShuiping** [comment]
@glzjin 😂如何提供

**Comment by glzjin** [comment]
提供你计划任务正常运行的证据

**Comment by TShuiping** [comment]
Dec  4 04:01:01 iZuf6gd3xwhccmtsb4xhf9Z run-parts(/etc/cron.hourly)[28438]: startin
g 0anacron
Dec  4 04:01:01 iZuf6gd3xwhccmtsb4xhf9Z run-parts(/etc/cron.hourly)[28447]: finishe
d 0anacron
Dec  4 04:02:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28510]: (root) CMD (php /home/wwwroot
/ss/xcat syncvpn)
Dec  4 04:02:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28511]: (root) CMD (php /home/wwwroot
/ss/xcat checkjob    )
Dec  4 04:02:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28512]: (root) CMD (php /home/wwwroot
/ss/xcat synclogin)
Dec  4 04:02:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28513]: (root) CMD (php -n /home/wwwr
oot/ss/xcat syncnas)
Dec  4 04:03:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28578]: (root) CMD (php /home/wwwroot
/ss/xcat syncvpn)
Dec  4 04:03:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28579]: (root) CMD (php /home/wwwroot
/ss/xcat checkjob    )
Dec  4 04:03:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28580]: (root) CMD (php /home/wwwroot
/ss/xcat synclogin)
Dec  4 04:03:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28581]: (root) CMD (php -n /home/wwwr
oot/ss/xcat syncnas)
Dec  4 04:04:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28652]: (root) CMD (php /home/wwwroot
/ss/xcat syncvpn)
Dec  4 04:04:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28653]: (root) CMD (php /home/wwwroot
/ss/xcat checkjob    )
Dec  4 04:04:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28654]: (root) CMD (php /home/wwwroot
/ss/xcat synclogin)
Dec  4 04:04:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28655]: (root) CMD (php -n /home/wwwr
oot/ss/xcat syncnas)
Dec  4 04:05:01 iZuf6gd3xwhccmtsb4xhf9Z CROND[28718]: (root) CMD (php /home/wwwroot
/ss/xcat syncvpn)

**Comment by TShuiping** [comment]
计划任务都是正常的

**Comment by glzjin** [comment]
@TShuiping 你手动运行 有输出不=、=？

**Comment by TShuiping** [comment]
邮件有 vpn木有

**Comment by glzjin** [comment]
@TShuiping 哦对了 把你这个用户的具体信息发出来

**Comment by TShuiping** [comment]
十来个用户都是 之前也都删不少了

**Comment by glzjin** [comment]
@TShuiping 我叫你发出来

**Comment by TShuiping** [comment]
咋发。。。

**Comment by glzjin** [comment]
把这个用户的具体信息发出来
