### ISSUE TITLE
能不能问下页面内的All-in-One在哪儿修改呢？

### ISSUE THREAD

**Issue by fox19971102** [glzjin/ss-panel-v3-mod#473]
解决

**Comment by fox19971102** [comment]
![Uploading 1.png…]()
附上图片

**Comment by fox19971102** [comment]
All-in-One

这里为您提供了自动化地配置文件生成，包含了所有 Shadowsocks 服务器的信息，方便您在诸多的服务器中快速添加，快速切换。

desktop_windows Windows 下载 C# 版，解压，然后下载这个，放到程序目录下，运行程序，选择一个合适的服务器，更新一下PAC为绕过国内IP，然后开启系统代理即可上网。

laptop_mac Mac OS X下载这个，安装，然后下载这个，运行程序，小飞机上右键 服务器列表 子菜单 的 “导入服务器配置文件...” 导入这个文件，然后选择一个合适的服务器，更新一下PAC，然后开启系统代理即可上网。

laptop_mac iOS 强烈推荐下载Shadowrocket，然后在 Safari 中点击这个，然后点击确定，就可以批量添加节点。

laptop_mac iOS 下载这个，导入到 Surge 中，然后就可以随意切换服务器上网了。

android Android下载 Android 版，安装，然后在手机上默认浏览器中点击这个，然后点击确定，批量添加完节点，然后路由选择绕过大陆，右上角开启就可以上网了。
就是这段文字

**Comment by glzjin** [comment]
？
