### ISSUE TITLE
关于备份邮件收不到附件的补充

### ISSUE THREAD

**Issue by moqiaoduo** [glzjin/ss-panel-v3-mod#476]
请检查系统是否安装了zip，若未安装也是无法收到附件的

**Comment by chaoqun14** [comment]
已经安装了，但是备份的时候仍然出现
[root@centos web]# php xcat dailyjob
cp: target `/tmp/ssmodbackup/configbak.php' is not a directory
1  adding: tmp/ssmodbackup/mod.sql (deflated 70%)
  adding: tmp/ssmodbackup/radius.sql (deflated 78%)
附件里只有两个数据库文件，缺少.config.php配置文件

**Comment by moqiaoduo** [comment]
@chaoqun14 检查一下文件权限和用户组

**Comment by chaoqun14** [comment]
已经检查过了，权限无问题

**Comment by moqiaoduo** [comment]
@chaoqun14 理论上是php没办法访问.config.php这个文件，你可以开一个新的issue问问g大

**Comment by glzjin** [comment]
@moqiaoduo 那个是cp过去的
