### ISSUE TITLE
关于stmp邮箱的一些问题

### ISSUE THREAD

**Issue by wengkangshun** [glzjin/ss-panel-v3-mod#481]
站点是按照教程搭建的

- [ 1] 问 账号创建时默认 不接受每日邮件 如何设置(.conf.php里设置?)? 

- [ 2] 如何把每日邮件 变成每周模式? (应该要修改app里的代码吧) 
 或者 (验证码 重置密码) (每日邮件推送) 分账号设置
 或者 每日邮件 加入取消订阅 的代码?

**Comment by wengkangshun** [comment]
关于问题1 看了下glzjin_all.sql 

创建表格 `user`  的代码里 有句代码
sendDailyMail` int(11) NOT NULL DEFAULT '1',

视乎是  发生日常邮件 ,默认值为 发送

是否更新下 默认值 就能解决我的问题1??

**Comment by wxliuxh** [comment]
第一个问题你说对了.改成0即可
php xcat sendDiaryMail 这个就是发送流量消耗的邮件.你把改成每周执行一次就行了
