### ISSUE TITLE
商品设置自动续费，自动续费一次后，订单状态变为不自动续费。

### ISSUE THREAD

**Issue by huya1121** [glzjin/ss-panel-v3-mod#486]
我看过代码里有重写自动续费时间，但是没有生效。请问赵大大有测试过这个吗？

**Comment by glzjin** [comment]
@huya1121 自动生成新的订单

**Comment by huya1121** [comment]
购买记录里并没有显示新订单~

**Comment by huya1121** [comment]
![qq 20161208120442](https://cloud.githubusercontent.com/assets/13938600/20997232/975b784c-bd3e-11e6-97d2-5cfad2c1e0e2.png)
![qq 20161208120504](https://cloud.githubusercontent.com/assets/13938600/20997231/97539a50-bd3e-11e6-807d-689ed2dbd48e.png)
数据库好像也没有生产一个新订单。

**Comment by glzjin** [comment]
你这个用户账户里还有多少钱？

**Comment by huya1121** [comment]
![qq 20161209174823](https://cloud.githubusercontent.com/assets/13938600/21044594/b60bb0f0-be37-11e6-9e87-7290a1a1f7cd.png)
刚才是460  现在变成459

**Comment by glzjin** [comment]
@huya1121 哦？你自己改过了？那我不知道咯 反正我用你的过程并没有问题 对了 你邮件发送正常吗

**Comment by huya1121** [comment]
邮件发送不正常，没有激活邮件发送。改过一些小地方， 但是这段代码没有任何修改。

**Comment by glzjin** [comment]
@huya1121 那就自己把邮件发送配置好就行了

**Comment by huya1121** [comment]
邮件发送用的是mailgun.  其它掉线、每日流量提醒 都没有问题。。

**Comment by glzjin** [comment]
@huya1121 你自己执行一下checkjob看看输出

**Comment by huya1121** [comment]
![qq 20161209175529](https://cloud.githubusercontent.com/assets/13938600/21044823/b2a37ca8-be38-11e6-8d85-c68ffed02131.png)
没有错误报告的。。

**Comment by glzjin** [comment]
@huya1121 先把自动的crontab停掉 再弄一次购买测试 反正你自己看输出咯

**Comment by huya1121** [comment]
![qq 20161209175529](https://cloud.githubusercontent.com/assets/13938600/21045232/7b005ae4-be3a-11e6-8869-3446dd527640.png)
提示 优惠码没有默认值。。。写入数据库失败。
![2016-12-09_180958](https://cloud.githubusercontent.com/assets/13938600/21045383/114e5e2e-be3b-11e6-9dff-f26733936035.png)

**Comment by glzjin** [comment]
@huya1121 OK 之后我加个东西
