### ISSUE TITLE
注册的时候，点发送邮件，然后邮箱也没收到邮件

### ISSUE THREAD

**Issue by chenmin1992** [glzjin/ss-panel-v3-mod#488]
弹出的对话框也是空白的，帮忙看下咯

**Comment by moqiaoduo** [comment]
https://github.com/glzjin/ss-panel-v3-mod/issues/156

**Comment by chenmin1992** [comment]
mailgun已经设置好了，执行php xcat syncusers可以收到邮件，只是注册的时候收不到邮件

**Comment by chenmin1992** [comment]
email_verify里也有记录，莫非是因为我改了网站目录？wiki里是ss.panel，我改成了ssr

**Comment by glzjin** [comment]
@chenmin1992 开debug 然后f12抓包

**Comment by chenmin1992** [comment]
{"error":{"type":"Mailgun\\Connection\\Exceptions\\MissingRequiredParameters","message":"The parameters passed to the API were invalid. Check your inputs!","file":"\/home\/wwwroot\/ssr\/vendor\/mailgun\/mailgun-php\/src\/Mailgun\/Connection\/RestClient.php","line":128}}


send的response

@glzjin

**Comment by glzjin** [comment]
@chenmin1992 确认你的mailgun账户和域名是否是enable状态

**Comment by chenmin1992** [comment]
![image](https://cloud.githubusercontent.com/assets/20168118/21070874/987b8252-beca-11e6-9ec0-776bfe9bb664.png)
可用的哦 @glzjin

**Comment by chenmin1992** [comment]
@glzjin 大哥，帮看下呗~

我对smarty不熟，post是向/auth/send  post的，但是我在auth目录下找不到send，能告诉我send的源码位置吗？告诉我我自己调试下
