### ISSUE TITLE
sspanel的节点限速疑问

### ISSUE THREAD

**Issue by lion1991** [glzjin/ss-panel-v3-mod#49]
远程radius vpn的方式接入.
最小只能是1Mbps吗？如果换算成B就是说最大下载速度是130KB/s左右？

**Comment by glzjin** [comment]
vpn无法进行限速 限速是某个神秘力量造成的
glzjin
2016年5月10日 上午10:34，lion1991 <notifications@github.com>写道：远程radius vpn的方式接入.
最小只能是1Mbps吗？如果换算成B就是说最大下载速度是130KB/s左右？

**Comment by lion1991** [comment]
莫非是ssshell... ...只针对ss的

**Comment by glzjin** [comment]
是的
