### ISSUE TITLE
面板里面显示节点一切正常但就是不能连接

### ISSUE THREAD

**Issue by ymefg** [glzjin/ss-panel-v3-mod#491]
我按照tg群里的教程几乎是直接复制粘贴搞好了前端和后端。添加节点，运行后端后也一切正常，面板显示在线，可以显示延迟、网速等信息。
但是当我按照面板显示的信息链接ss时，连不上。
并且注册新账号时显示的还是同一个端口和密码，讲道理应该是不同的端口不同的密码吧？
唯一前端安装出错的地方就是修改防火墙设置。教程是这样说的：

>  最后，以防万一，修改一下防火墙设置以免数据库不通
> 执行：vi /etc/sysconfig/iptables
> 检查3306端口的设置，请修改为和下方的参数一致
> -A INPUT -s 127.0.0.1/32 -p tcp -m tcp --dport 3306 -j ACCEPT 
> -A INPUT -p tcp -m tcp --dport 3306 -j ACCEPT

我输入vi /etc/sysconfig/iptables时发现是新建一个文件，所以就直接:q!了。其他步骤均没出现问题。

**Comment by glzjin** [comment]
@ymefg ？截图看看

**Comment by ymefg** [comment]
@glzjin 抱歉刚才手机没电截完图就关机并且上课了。好像手机是不能发图片的，所以我上传到网站了。
地址是[https://ymefg.win/q/Screenshot_20161211-084321.png](url)
[https://ymefg.win/Screenshot_20161211-084213.png](url)
[https://ymefg.win/Screenshot_20161211-084041.png](url)
[https://ymefg.win/Screenshot_20161211-084024.png](url)
