### ISSUE TITLE
单端口多用户只要混淆不同就不计算流量

### ISSUE THREAD

**Issue by nik0chen** [glzjin/ss-panel-v3-mod#492]
普通节点：加密 chacha20 协议 auth_aes128_md5 混淆http_simple
单端口多用户节点 ：加密chacha20 协议 auth_aes128_md5 混淆tls1.2_ticket_auth
情况是只要混淆不同，就不会计算流量，在线IP里也不会显示。但是只要混淆改成一致的就能计算，请问这个可以修复吗？
因为要使用80端口，测试过，80端口可以突破我当地电信的qos。

**Comment by glzjin** [comment]
@nik0chen 没有发现这个问题 请提供更为具体的例子

**Comment by nik0chen** [comment]
好吧，那我再多测试测试，谢谢

**Comment by nik0chen** [comment]
还有一个是，如果用户用ss原版协议，单端口多用户是 auth_aes128_md5 和tls1.2_ticket_auth，会无法连接

**Comment by glzjin** [comment]
@nik0chen 当然

**Comment by nik0chen** [comment]
我的锅，单端口多用户的那个账号等级没设置，导致连不上。关闭了
