### ISSUE TITLE
读取api错误

### ISSUE THREAD

**Issue by 619096932** [glzjin/ss-panel-v3-mod#5]
如果用webapi 出现以下报错
![l j kf s np ui wpgr 6a](https://cloud.githubusercontent.com/assets/15718535/14949191/73f5c3c4-107a-11e6-895c-c66db2e0ee77.png)
用mysql提示以下
![6 k1b t8l t4534 2a r](https://cloud.githubusercontent.com/assets/15718535/14949220/a1038a7c-107a-11e6-87b0-fa5391205161.png)

**Comment by 619096932** [comment]
用mysql 可以正常使用，但是不会统计数据
![7_2b m xt2ait9s omnvym](https://cloud.githubusercontent.com/assets/15718535/14949339/b743d6d8-107b-11e6-9572-d32ce19b161c.png)

**Comment by glzjin** [comment]
上面的报错都写得很清楚了=、=这个请你找 go mu 的原作者

**Comment by lion1991** [comment]
之前有端口已经被占用了吧,看看有没有原GO的后台进程占用
