### ISSUE TITLE
检测速度一直显示的是null···这个是哪里配置出了问题

### ISSUE THREAD

**Issue by serm12** [glzjin/ss-panel-v3-mod#50]
节点	电信延迟	电信下载速度	电信上传速度	联通延迟	联通下载速度	联通上传速度	移动延迟	移动下载速度	移动上传速度
A新加坡sssg1.xxxx.com  	null	null	null	null	null	null	null	null	null

**Comment by glzjin** [comment]
看ssshell的安装说明 装speedtest-cli
