### ISSUE TITLE
请教信

### ISSUE THREAD

**Issue by z970928928** [glzjin/ss-panel-v3-mod#500]
赵老师，请教一下为什么我执行这一句
service radiusd start && chkconfig radiusd on

返回是失败的

还请教一下，请问配置的config.php在哪呢？我想传回本地进行配置，但是我在网站根目录没有看见。

谢谢赵老师

**Comment by glzjin** [comment]
@z970928928 radiusd -X 查错

.config.php 在 config 目录下 需要用 ls -a 才能看到= =

**Comment by z970928928** [comment]
@ glzjin 按照您的方法前面的问题已经解决了，但是我出现了两新问题
第一个，我不能添加节点，返回一个空白对话框。
第二个我搭建的链接后没网络。
请问是什么原因

**Comment by glzjin** [comment]
@z970928928 你是升级？你导入了数据库了吗？

**Comment by z970928928** [comment]
@ gizjin 谢谢赵老师，我已经解决了添加服务器问题，但是我还是没网，扫描了一下端口发现用户远程端口竟然没开，请问系统可以直接开启吗，还是每一个新用户都需要手动添加端口？
