### ISSUE TITLE
最近的一次更新之后修改code.tpl文件并不能更改邀请码页面

### ISSUE THREAD

**Issue by anwar666** [glzjin/ss-panel-v3-mod#501]
/resources/views/material/,这里的tpl文件修改之后有的能生效有的并不能生效，请教一下？

**Comment by glzjin** [comment]
@anwar666 清空下 storage 下的缓存目录 并且看看 opcache 是不是开了。

**Comment by anwar666** [comment]
Opcache没有开，是要把storage目录里的全部文件都删除吗

**Comment by glzjin** [comment]
@anwar666 里面有个子目录，进去把里面那堆文件删了，具体我也忘了。

**Comment by anwar666** [comment]
好，我再看一下，麻烦你了

**Comment by anwar666** [comment]
问题已解决
