### ISSUE TITLE
某个节点只启用单端口…

### ISSUE THREAD

**Issue by Woophp** [glzjin/ss-panel-v3-mod#504]
嗯哼这很清真，没有人需求某个节点不开单端口么😂…配置文件把每个节点都生成一份单端口…有点多……

**Comment by glzjin** [comment]
@Woophp 没有 都是节点上开放哪些端口 就显示哪些

**Comment by Woophp** [comment]
@glzjin 现在我自己改了改…节点列表显示那里可以实现了，All in one 那里还是全部出来，赵老师可否告知linkController.php里面的$mu_nodes = Node::where('sort',9)->where('node_class','<=',$user->class)->where("type","1")->…………这句，其中的'sort'、'node_class'、"type"函数是在哪个文件做的定义？
