### ISSUE TITLE
公告中的编辑器功能无法使用

### ISSUE THREAD

**Issue by moqiaoduo** [glzjin/ss-panel-v3-mod#508]
除了 编辑文字正常外，加粗、设置超链接等功能无法使用。

网站环境：apache 和 kangle （分别两台vps）
PHP版本：5.6

**Comment by glzjin** [comment]
@moqiaoduo F12 看看页面资源加载全了没

**Comment by moqiaoduo** [comment]
![qq 20161224161840](https://cloud.githubusercontent.com/assets/20296531/21466031/b032a0f8-c9f4-11e6-969f-64554f36e7f0.png)
是这样看吗

**Comment by glzjin** [comment]
@moqiaoduo 看网络那边

**Comment by moqiaoduo** [comment]
![qq 20161224162109](https://cloud.githubusercontent.com/assets/20296531/21466043/0b344f88-c9f5-11e6-88c9-4ba8cd80e5be.png)
![qq 20161224162121](https://cloud.githubusercontent.com/assets/20296531/21466047/14cd7a06-c9f5-11e6-9f4a-79e06ab3484b.png)

**Comment by glzjin** [comment]
@moqiaoduo 看看 Console 里 有啥输出没

**Comment by moqiaoduo** [comment]
![qq 20161224162436](https://cloud.githubusercontent.com/assets/20296531/21466054/7c488be4-c9f5-11e6-9444-14081a631f88.png)
跟统计代码有关，不知道有没有影响

**Comment by glzjin** [comment]
@moqiaoduo 对了 你是怎么无法用 截个图

**Comment by moqiaoduo** [comment]
![qq 20161224163120](https://cloud.githubusercontent.com/assets/20296531/21466077/6daf797a-c9f6-11e6-84ab-3c59fb875a87.png)
这上面的按钮怎么点击都是无效的

**Comment by glzjin** [comment]
@moqiaoduo 什么浏览器？

**Comment by moqiaoduo** [comment]
chrome

**Comment by moqiaoduo** [comment]
额。。。好像IE可以耶，应该是浏览器问题了
