### ISSUE TITLE
升级面板，运行 php -n xcat initdownload 得到 Fatal error: Interface 'jsonserializable' not found in /srv/fredchan.ml/www/ss-panel-mod/vendor/illuminate/support/Fluent.php on line 10

### ISSUE THREAD

**Issue by 70599** [glzjin/ss-panel-v3-mod#516]
php版本7.0。

`php -r "phpinfo();" | grep json`输出：
```
/etc/php.d/20-json.ini,
json
json support => enabled
json version => 1.4.0
proto_binary_fetched_json => 0
```
php json 应该是正常启用了的，有什么办法吗？

已参考下列链接，未能找到什么线索：
http://stackoverflow.com/questions/37906644/php-fatal-error-interface-jsonserializable
http://stackoverflow.com/questions/41022852/php-fatal-error-interface-jsonserializable-not-found

**Comment by 70599** [comment]
去掉 -n 参数运行成功。
话说 -n 在这里是干什么的？

**Comment by glzjin** [comment]
-n 是不启用PHP配置文件，当然你爸 disable_function 里 system 给去掉也行。2016年12月27日 上午4:15，70599 <notifications@github.com>写道：php版本7.0。
php -r "phpinfo();" | grep json输出：
/etc/php.d/20-json.ini,
json
json support => enabled
json version => 1.4.0
proto_binary_fetched_json => 0

php json 应该是正常启用了的，有什么办法吗？
已参考下列链接，未能找到什么线索：
http://stackoverflow.com/questions/37906644/php-fatal-error-interface-jsonserializable
http://stackoverflow.com/questions/41022852/php-fatal-error-interface-jsonserializable-not-found

**Comment by 70599** [comment]
感谢你特意在已经 close 的 issue 上说明。:-)
