### ISSUE TITLE
计划任务没有执行

### ISSUE THREAD

**Issue by kncxstudio** [glzjin/ss-panel-v3-mod#518]
计划任务没有执行，用的流量全部显示为今日流量，已用流量为0

**Comment by glzjin** [comment]
检查crontab运行情况2016年12月28日 下午1:48，Junqin Wang <notifications@github.com>写道：计划任务没有执行，用的流量全部显示为今日流量，已用流量为0

**Comment by kncxstudio** [comment]
crontab里面为空白，请问如何手动添加计划任务

**Comment by kncxstudio** [comment]
已解决
