### ISSUE TITLE
窝能说安装教程十分坑爹么

### ISSUE THREAD

**Issue by fiepi** [glzjin/ss-panel-v3-mod#53]
简直神坑。

**Comment by lion1991** [comment]
不会吧,我使用的之前的教程,安装没问题啊..新教程没试过,貌似跟更简单了 直接导入修改好的文件就行啦

**Comment by fiepi** [comment]
@lion1991 ，这就是坑爹之处，直接放出某个发行版中某个版本的配置文件，这能叫教程？非常局限，正常情况下，首先应列出需要的依赖，说明大概的作用。到现在窝都不造freeradius在这里有什么用，似乎停止freeradius也不影响使用。发行版不同，配置文件的路径和组织结构往往大相径庭，教程里直接扔出几个conf，却不告诉你conf里做了什么修改，起到什么作用，其结果就是这些配置文件只能在这一特定版本的系统能够使用。当然，如果比较熟悉linux，虽然这教程比较坑，也能猜出个大概

**Comment by glzjin** [comment]
之前做了修改了，结果一大堆人说不会修改，就改成目前这样了。你明不明白这个是什么作用的我帮不到你，需要你自己去看我写的其他东西自己了解作用，我也标明了这个教程的原始引用，你想看怎么修改的可以自己点进去看。
glzjin
2016年5月10日 下午5:02，妹妹你好胸 <notifications@github.com>写道：@lion1991 ，这就是坑爹之处，直接放出某个发行版中某个版本的配置文件，这能叫教程？非常局限，正常情况下，首先应列出需要的依赖，说明大概的作用。到现在窝都不造freeradius在这里有什么用，似乎停止freeradius也不影响使用。发行版不同，配置文件的路径和组织结构往往大相径庭，教程里直接扔出几个conf，却不告诉你conf里做了什么修改，起到什么作用，其结果就是这些配置文件只能在这一特定版本的系统能够使用。当然，如果比较熟悉linux，虽然这教程比较坑，也能猜出个大概

**Comment by glzjin** [comment]
当然，您要是能写一份您所使用的发行版系统的您所谓的“教程”的话也非常欢迎您来写，我会积极的将其引用至wiki中，谢谢。受精力和时间所限，我不可能写的多详细，也不可能照顾到所有人，所以才需要你们的帮助，谢谢。

**Comment by 619096932** [comment]
赵大666  教程很详细的 感谢赵大对sspanel做的二次开发！真的很棒！

**Comment by lion1991** [comment]
哈哈.是啊 欢迎补充详细的教程...Sent from Mail Master
            On 05/10/2016 17:43, glzjin wrote:当然，您要是能写一份您所使用的发行版系统的您所谓的“教程”的话也非常欢迎您来写，我会积极的将其引用至wiki中，谢谢。受精力和时间所限，我不可能写的多详细，也不可能照顾到所有人，所以才需要你们的帮助，谢谢。
