### ISSUE TITLE
赵老师帮忙看看，登陆不跳转，要手动刷新。

### ISSUE THREAD

**Issue by Woophp** [glzjin/ss-panel-v3-mod#532]
F12如下提示

POST https://****/auth/login 500 ()   jquery.min.js:4 
send @ jquery.min.js:4
ajax @ jquery.min.js:4
login @ login:170
(anonymous) @ login:205
dispatch @ jquery.min.js:3
![qq 20161107160535](https://cloud.githubusercontent.com/assets/22631937/21564477/fe5581a0-cec8-11e6-9773-cdbbbe00dfb9.png)

r.handle @ jquery.min.js:3

**Comment by glzjin** [comment]
@Woophp 看网络那部分。。。

**Comment by Woophp** [comment]
![qq 20161107160535](https://cloud.githubusercontent.com/assets/22631937/21564528/8cb63692-cec9-11e6-9877-60a68bfa14fb.png)
@glzjin

**Comment by glzjin** [comment]
@Woophp 点开红色请求

**Comment by Woophp** [comment]
![qq 20161107160535](https://cloud.githubusercontent.com/assets/22631937/21564570/0193c3f8-ceca-11e6-9f40-86be4d1f8c20.png)

标记从send(b.hasContent&&b.data||null)}cat到结束

**Comment by glzjin** [comment]
@Woophp 算了 站点发出来

**Comment by Woophp** [comment]
@glzjin godon.biz

**Comment by glzjin** [comment]
@Woophp 给个测试帐号来

**Comment by Woophp** [comment]
@glzjin    test@test.com      123456789

**Comment by Woophp** [comment]
刚刚密码多了一位

**Comment by Woophp** [comment]
test@test.com  12345678

**Comment by glzjin** [comment]
@Woophp 数据库链接超时

**Comment by Woophp** [comment]
@glzjin 多谢，已找到原因
