### ISSUE TITLE
php /home/wwwroot/ss.panel/xcat dailyjob checkjob提示warning

### ISSUE THREAD

**Issue by tsingfeng** [glzjin/ss-panel-v3-mod#57]
php /home/wwwroot/ss.panel/xcat dailyjob 提示：
PHP Warning:  Missing argument 1 for App\Utils\QQWry::getlocation(), called in /home/wwwroot/ss.panel/app/Command/Job.php on line 123 and defined in /home/wwwroot/ss.panel/app/Utils/QQWry.php on line 129
PHP Notice:  Undefined variable: ip in /home/wwwroot/ss.panel/app/Utils/QQWry.php on line 133
php /home/wwwroot/ss.panel/xcat checkjob 提示
PHP Notice:  Undefined variable: Group in /home/wwwroot/ss.panel/app/Command/Job.php on line 260
PHP Notice:  Undefined variable: Group in /home/wwwroot/ss.panel/app/Command/Job.php on line 461
是我的安装有问题还是不用管这些提示？

**Comment by glzjin** [comment]
QQwry数据库更新失败，系统会在第二天自动修复。

**Comment by thomas0612** [comment]
如何更新QQwry  我是解压安装  目前文件显示创建时间还是10月31日  还没有更新
