### ISSUE TITLE
请问下这个能不能加上

### ISSUE THREAD

**Issue by 38921159** [glzjin/ss-panel-v3-mod#58]
1、后台显示在线人数增加在线会员的ID，并且统计会员的今日用量。现在的需要go mu才能实现。希望其他服务器后端的也能实现。
2、会员管理里增加可以以邮箱或者ID或者端口进行搜索，或者输入页数跳转

不知道能不能实现这两个功能，我的小小建议。谢谢

**Comment by lion1991** [comment]
使用ssshell何以实现第一个,第二个最新版本已经支持模糊搜索了!

**Comment by glzjin** [comment]
1.ssshell 可以做到你说的第一个功能，你直接打开用户列表就可以看到 IP 了。
2.会员管理本来就有分页，最新版本可以对用户名，联系方式，邮箱进行模糊搜索。

**Comment by 38921159** [comment]
因为我现在后端用的是Python的R版。所以在后台在线人数那里无法显示在线人数的会员id ，只显示了多少人。

今日用量这个应该是一个以时间统计t表的数据，应该是不需要安装ssshell吧？

**Comment by glzjin** [comment]
看看源码就知道了的。
glzjin
2016年5月11日 下午2:03，haloubeibi <notifications@github.com>写道：因为我现在后端用的是Python的R版。所以在后台在线人数那里无法显示在线人数的会员id ，只显示了多少人。

今日用量这个应该是一个以时间统计t表的数据，应该是不需要安装ssshell吧？

**Comment by glzjin** [comment]
是的。
glzjin
2016年5月11日 下午2:03，haloubeibi <notifications@github.com>写道：因为我现在后端用的是Python的R版。所以在后台在线人数那里无法显示在线人数的会员id ，只显示了多少人。

今日用量这个应该是一个以时间统计t表的数据，应该是不需要安装ssshell吧？
