### ISSUE TITLE
关于三合一VPN节点搭建的问题

### ISSUE THREAD

**Issue by tsingfeng** [glzjin/ss-panel-v3-mod#59]
在安装教程中推荐的vpn三合一后遇到了一些问题   搜索研究了好久也没解决  可能是我目前能力不足 不知道您能不能帮我看下
问题：在安装vpn三合一后连接不上vpn（应该是连接上就断）
radiusd -X显示

![111](https://cloud.githubusercontent.com/assets/19178724/15165965/c44f30e8-174c-11e6-8ac5-86ba6c6af549.png)
![222](https://cloud.githubusercontent.com/assets/19178724/15165991/f120bd94-174c-11e6-81aa-d563fd72ebc8.jpg)

流量记录显示：

1	admin	统一验证登陆	1	9.77KB	9.77KB	
1	admin	统一验证登陆   1	9.77KB	9.77KB

我尝试根据网上搜索的结果 修改过节点服务器的防火墙配置  但是问题没有解决 
认证服务器 1812 1813端口应该也开了 
目前不知道问题出在哪里  
非常希望您能够指点下。

**Comment by glzjin** [comment]
这个是验证成功了的，至于闪断，就是因为某种神秘的力量了。这个，我们解决不了的。
