### ISSUE TITLE
页面不自动刷新的问题 

### ISSUE THREAD

**Issue by 619096932** [glzjin/ss-panel-v3-mod#6]
![gif2](https://cloud.githubusercontent.com/assets/15718535/14949247/05bb5bca-107b-11e6-95c2-1a1b342e770d.gif) 具体mimifq.com 你可以看一下

**Comment by glzjin** [comment]
﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿{"ret":1,"msg":"\u6ce8\u518c\u6210\u529

你所接收到的数据不完整，这个我解决不了=、=请检查web服务器和网络的原因

**Comment by 619096932** [comment]
好的谢谢

**Comment by pcskys** [comment]
我碰到的也是这个问题注册和登录不刷新

**Comment by glzjin** [comment]
自己检查下吧=、=主要就是返回的数据不完全
glzjin
2016年5月2日 下午6:03，pcskys <notifications@github.com>写道：我碰到的也是这个问题注册和登录不刷新
