### ISSUE TITLE
节点不记录流量是什么问题，有时候更新服务的后就会出现这种问题

### ISSUE THREAD

**Issue by serm12** [glzjin/ss-panel-v3-mod#60]
节点不记录流量是什么问题，有时候更新服务的后就会出现这种问题

**Comment by glzjin** [comment]
后端问题，什么后端？

**Comment by serm12** [comment]
是ssshell-jar版本的，linode的可以记录，vultr的不能记录，以前vultr的节点也是可以记录的

**Comment by glzjin** [comment]
检查一下信息是否填写正确，手动运行是否正常 
glzjin
2016年5月11日 下午11:41，serm12 <notifications@github.com>写道：是ssshell-jar版本的，linode的可以记录，vultr的不能记录，以前vultr的节点也是可以记录的
