### ISSUE TITLE
Anyconnect运行失败

### ISSUE THREAD

**Issue by tsingfeng** [glzjin/ss-panel-v3-mod#61]
Skipping unknown option ‘cookie-validity’
Setting ‘radius’ as primary authentication method
Enabling ‘certificate’ as authentication method
Setting ‘radius’ as accounting method
listening (TCP) on 0.0.0.0:5444…
listening (TCP) on [::]:5444…
listening (UDP) on 0.0.0.0:5444…
listening (UDP) on [::]:5444…
Segmentation fault
请问 运行之后 显示这个  我该怎样找出哪里出错了？

**Comment by glzjin** [comment]
-d 9999 看错误信息然后上网搜

**Comment by tsingfeng** [comment]
谢谢，我去试试
