### ISSUE TITLE
不配置wecenter执行php xcat sendDiaryMail会报错

### ISSUE THREAD

**Issue by SkyWalker3432** [glzjin/ss-panel-v3-mod#65]
.config.php里删除了$System_Config['wecenter_url']='http://help.';

如果不配置wecenter的话执行php xcat sendDiaryMail会提示
Undefined index: wecenter_url in /home/wwwroot/sspanel/app/Services/Config.php on line 11

**Comment by glzjin** [comment]
不要删除，而是清空这个配置项的值。

**Comment by SkyWalker3432** [comment]
好吧是我理解错了
