### ISSUE TITLE
之前的端口扫描关小黑屋的教程还有吗

### ISSUE THREAD

**Issue by xiadena** [glzjin/ss-panel-v3-mod#66]
求一份教程，感谢

**Comment by glzjin** [comment]
请提供你的站点地址，提问需要验证底部版权。
glzjin
2016年5月11日 下午11:21，xiadena <notifications@github.com>写道：求一份教程，感谢

**Comment by xiadena** [comment]
https://vip.9kss.net/staff

**Comment by glzjin** [comment]
https://www.zhaoj.in/read-2142.html
glzjin
2016年5月11日 下午11:49，xiadena <notifications@github.com>写道：https://vip.9kss.net/staff

**Comment by xiadena** [comment]
应该可以删除我的地址了吧。。随时可以检查

**Comment by glzjin** [comment]
可以
glzjin
2016年5月11日 下午11:55，xiadena <notifications@github.com>写道：应该可以删除我的地址了吧。。随时可以检查
