### ISSUE TITLE
升级了最新版本，发现居然有返利系统，这就是招到攻击的原因啊

### ISSUE THREAD

**Issue by ChromiumX** [glzjin/ss-panel-v3-mod#67]
我是博客里留言里的Miku，Q群合资非营利性小站长，本人从来没改过版权申明，原来用原版也是一样。
看到作者博客这么惨，特发网站公告，邀请注册，当Ta充值时您就会获得Ta充值金额的10 %的提成，10%捐赠给作者。希望能支持作者一直更新下去，加油。希望能优化下ssshell的数据库连接，RDS总连接数一直在封顶数量64，活跃连接数只有3,4。

**Comment by glzjin** [comment]
你可以拿源代码自己改，改成1即可，目前是3。
glzjin
2016年5月12日 下午3:39，ChromiumX <notifications@github.com>写道：我是博客里留言里的Miku，Q群合资非营利性小站长，本人从来没改过版权申明，原来用原版也是一样。
看到作者博客这么惨，特发网站公告，邀请注册，当Ta充值时您就会获得Ta充值金额的10 %的提成，10%捐赠给作者。希望能支持作者一直更新下去，加油。希望能优化下ssshell的数据库连接，RDS总连接数一直在封顶数量64，活跃连接数只有3,4。

**Comment by glzjin** [comment]
谢谢您，这个可以发在那个项目的issue，源代码可以自己修改，用eclipse即可打开。
glzjin
2016年5月12日 下午3:39，ChromiumX <notifications@github.com>写道：我是博客里留言里的Miku，Q群合资非营利性小站长，本人从来没改过版权申明，原来用原版也是一样。
看到作者博客这么惨，特发网站公告，邀请注册，当Ta充值时您就会获得Ta充值金额的10 %的提成，10%捐赠给作者。希望能支持作者一直更新下去，加油。希望能优化下ssshell的数据库连接，RDS总连接数一直在封顶数量64，活跃连接数只有3,4。

**Comment by glzjin** [comment]
还有并不是这个招来了攻击。
glzjin
2016年5月12日 下午3:39，ChromiumX <notifications@github.com>写道：我是博客里留言里的Miku，Q群合资非营利性小站长，本人从来没改过版权申明，原来用原版也是一样。
看到作者博客这么惨，特发网站公告，邀请注册，当Ta充值时您就会获得Ta充值金额的10 %的提成，10%捐赠给作者。希望能支持作者一直更新下去，加油。希望能优化下ssshell的数据库连接，RDS总连接数一直在封顶数量64，活跃连接数只有3,4。
