### ISSUE TITLE
按教程安装后，shadowsocks无法正常启动，出现一个莫名进程

### ISSUE THREAD

**Issue by j0hnnie** [glzjin/ss-panel-v3-mod#68]
root      6662  0.0  0.1  17408  1536 ?        Ss   14:00   0:00 ss-server -c /tmp/ssshell/2.conf -f /tmp/ssshell/2.pid -u -d 208.67.222.222

出现一个这个。。。。208.67.222.222这是什么鬼

**Comment by glzjin** [comment]
opendns
glzjin
2016年5月12日 下午4:28，j0hnnie <notifications@github.com>写道：root      6662  0.0  0.1  17408  1536 ?        Ss   14:00   0:00 ss-server -c /tmp/ssshell/2.conf -f /tmp/ssshell/2.pid -u -d 208.67.222.222

出现一个这个。。。。208.67.222.222这是什么鬼

**Comment by glzjin** [comment]
还有发到对应项目的issue
