### ISSUE TITLE
最新版管理面板Bug了吗

### ISSUE THREAD

**Issue by xiadena** [glzjin/ss-panel-v3-mod#71]
点管理面板是跳转到用户中心然后无限循环

**Comment by fiepi** [comment]
可能是主题的bug,左侧的菜单没切换成功。比如你手动输入链接打开./admin/node还是可以对节点进行管理

**Comment by glzjin** [comment]
并没有发现你说的问题，请提供站点地址和管理员用户名还有密码发送到 i#zhaoj.in 以便详细检查。

**Comment by hemla** [comment]
xiadena commented 14 hours ago
点管理面板是跳转到用户中心然后无限循环

同样遇到这个问题

**Comment by glzjin** [comment]
@hemla 并没有发现你说的问题，请提供站点地址和管理员用户名还有密码发送到 i#zhaoj.in 以便详细检查。

**Comment by hemla** [comment]
已发送

**Comment by glzjin** [comment]
谢谢各位的反馈，已经修复 https://github.com/glzjin/ss-panel-v3-mod/issues/72 请按照最新的步骤来进行更新。
