### ISSUE TITLE
服务器出现，网站重定向太多，求解

### ISSUE THREAD

**Issue by david7207** [glzjin/ss-panel-v3-mod#73]
![bug](https://cloud.githubusercontent.com/assets/9106366/15247291/de4c8e82-1945-11e6-89f2-1ebd0b7cbfb0.JPG)
网址地址栏里有！但是网站无法打开，debug已经打开！

**Comment by david7207** [comment]
![bug2](https://cloud.githubusercontent.com/assets/9106366/15247396/82d2e532-1946-11e6-889d-80a290ddda25.JPG)
具体的http头部

**Comment by glzjin** [comment]
你没事开什么Redis。。。

**Comment by glzjin** [comment]
把Redis的设置清空，上面的token什么的设置不要用到Redis，该换回来就换回来。
glzjin
2016年5月13日 下午8:09，david <notifications@github.com>写道：
具体的http头部

**Comment by fiepi** [comment]
窝也遇到过，不过没有关redis，慢慢对nginx和php-fpm的配置调教了很久才搞定

**Comment by david7207** [comment]
![bug](https://cloud.githubusercontent.com/assets/9106366/15250304/bd4c6cdc-1956-11e6-92e3-1f9b9fc4280e.JPG)
然而现在出现了这个了，我已经不用redis了

**Comment by david7207** [comment]
@fiepi 你怎么设置nginx的？

**Comment by yueker** [comment]
楼主这个问题是怎么解决的
