### ISSUE TITLE
可否增加用户管理界面自定义跳转页码功能

### ISSUE THREAD

**Issue by lion1991** [glzjin/ss-panel-v3-mod#75]
当用户的数量多的时候,如果要批量查看指定页码的用户信息需要点多次才能到达,如果作者有时间希望抽空增加此功能~~
website:https://ssbow.win

**Comment by glzjin** [comment]
可以是可以，不过也不是回帖那么码得准谁是谁谁在哪一页。
glzjin
2016年5月14日 上午8:58，lion1991 <notifications@github.com>写道：当用户的数量多的时候,如果要批量查看指定页码的用户信息需要点多次才能到达,如果作者有时间希望抽空增加此功能~~
website:https://ssbow.win

**Comment by lion1991** [comment]
其实我就是遍历查看超过几天不使用的然后进行处理.因为每次编辑完状态,都会自动返回到/user页面的第一页...还得回到处理过的页面进行再查询.或者换种方法编辑好用户后,跳转到当前编辑的用户所在页码中.这样就可以继续下一页了.

**Comment by glzjin** [comment]
目前是改为你后面说的那一种了
