### ISSUE TITLE
智能线路节点地址显示疑问

### ISSUE THREAD

**Issue by tsingfeng** [glzjin/ss-panel-v3-mod#76]
管理员账号和用户账号智能节点地址显示不一样
管理员：
![qq 20160514101029](https://cloud.githubusercontent.com/assets/19178724/15265643/9cdf7064-19bc-11e6-92a9-9dd6c226ca46.png)
 
用户：
![qq 20160514100732](https://cloud.githubusercontent.com/assets/19178724/15265648/b79f0342-19bc-11e6-914d-36e2342b47b6.png)
网址：**e.red(之前发过一次)

**Comment by glzjin** [comment]
请问等级和群组是一样的吗 不同的等级和群组所显示的地址是不一样的
glzjin
2016年5月14日 上午10:16，tsingfeng <notifications@github.com>写道：管理员账号和用户账号智能节点地址显示不一样
管理员：


用户：

网址：**e.red(之前发过一次)

**Comment by tsingfeng** [comment]
看了下，的确是忽略了这点
之前用户等级不一样（节点类别都为0），改成相同等级后地址相同。
但是我在创建用户账户之前手动删过一次cloudxns上面的解析记录（因为当时我以为那些解析记录没有用，不知道是因为不同等级而建立的新的解析），导致现在新建用户的智能节点地址在cloudxns上并没有记录。
该怎么办？

**Comment by glzjin** [comment]
清空smartline表 会自动重新生成
glzjin
2016年5月14日 上午10:58，tsingfeng <notifications@github.com>写道：看了下，的确是忽略了这点
之前用户等级不一样（节点类别都为0），改成相同等级后地址相同。
但是我在创建用户账户之前手动删过一次cloudxns上面的解析记录（因为当时我以为那些解析记录没有用，不知道是因为不同等级而建立的新的解析），导致现在新建用户的智能节点地址在cloudxns上并没有记录。
该怎么办？

**Comment by tsingfeng** [comment]
谢了
