### ISSUE TITLE
搭建失败 一直出现500错误 而且文件不存在  wget指令缺失

### ISSUE THREAD

**Issue by onesez** [glzjin/ss-panel-v3-mod#77]
glzjin 发表于 2016-5-15 15:20
提交issue就行了，这样方便回答。

。。不行啊  能帮忙搭建下看看么  而且
wget https://github.com/glzjin/Radius-install/raw/master/radiusd.conf -O /etc/raddb/radiusd.conf

wget https://github.com/glzjin/Radius-install/raw/master/default -O /etc/raddb/sites-enabled/default

wget https://github.com/glzjin/Radius-install/raw/master/dialup.conf -O /etc/raddb/sql/mysql/dialup.conf

wget https://github.com/glzjin/Radius-install/raw/master/dictionary -O /etc/raddb/dictionary

wget https://github.com/glzjin/Radius-install/raw/master/counter.conf -O /etc/raddb/sql/mysql/counter.conf
这些指令都不能用，还得修改，有的文件还不存在，重启radius又是错误提示缺少proxy.conf。。。

**Comment by glzjin** [comment]
我刚刚测试这些命令都是可用的。
glzjin
2016年5月15日 下午3:56，onesez <notifications@github.com>写道：glzjin 发表于 2016-5-15 15:20
提交issue就行了，这样方便回答。

。。不行啊  能帮忙搭建下看看么  而且
wget https://github.com/glzjin/Radius-install/raw/master/radiusd.conf -O /etc/raddb/radiusd.conf

wget https://github.com/glzjin/Radius-install/raw/master/default -O /etc/raddb/sites-enabled/default

wget https://github.com/glzjin/Radius-install/raw/master/dialup.conf -O /etc/raddb/sql/mysql/dialup.conf

wget https://github.com/glzjin/Radius-install/raw/master/dictionary -O /etc/raddb/dictionary

wget https://github.com/glzjin/Radius-install/raw/master/counter.conf -O /etc/raddb/sql/mysql/counter.conf
这些指令都不能用，还得修改，有的文件还不存在，重启radius又是错误提示缺少proxy.conf。。。

**Comment by glzjin** [comment]
请提供这些命令的返回结果。
glzjin
2016年5月15日 下午3:56，onesez <notifications@github.com>写道：glzjin 发表于 2016-5-15 15:20
提交issue就行了，这样方便回答。

。。不行啊  能帮忙搭建下看看么  而且
wget https://github.com/glzjin/Radius-install/raw/master/radiusd.conf -O /etc/raddb/radiusd.conf

wget https://github.com/glzjin/Radius-install/raw/master/default -O /etc/raddb/sites-enabled/default

wget https://github.com/glzjin/Radius-install/raw/master/dialup.conf -O /etc/raddb/sql/mysql/dialup.conf

wget https://github.com/glzjin/Radius-install/raw/master/dictionary -O /etc/raddb/dictionary

wget https://github.com/glzjin/Radius-install/raw/master/counter.conf -O /etc/raddb/sql/mysql/counter.conf
这些指令都不能用，还得修改，有的文件还不存在，重启radius又是错误提示缺少proxy.conf。。。

**Comment by my971208** [comment]
yum install wget -y

**Comment by onesez** [comment]
wget可以 只不过https还需要添加wget参数

**Comment by tsingfeng** [comment]
yum update wget

**Comment by onesez** [comment]
不对

**Comment by fiepi** [comment]
git clone https://github.com/glzjin/Radius-install.git
cd Radius-install
再 cp 对 conf 文件到对应目录。

不需要 vpn，可以不装 freeradius。
系统版本、freedius的版本稍有不同，它的配置就不能用了，，省事不装也罢

**Comment by glzjin** [comment]
yum update 请更新wget
glzjin
2016年5月15日 下午7:17，onesez <notifications@github.com>写道：wget可以 只不过https还需要添加wget参数
