### ISSUE TITLE
修改用户信息提交出了问题，debug打开出现Undefined index: codes

### ISSUE THREAD

**Issue by david7207** [glzjin/ss-panel-v3-mod#78]
网址：lastss.com，原finalss.com
![bug4](https://cloud.githubusercontent.com/assets/9106366/15274572/d6321ff2-1ae7-11e6-8791-220d589661fa.JPG)

**Comment by david7207** [comment]
网站debug已经打开！

**Comment by glzjin** [comment]
这是邀请码的页面吧。。你怎么跳到这来的。。

**Comment by glzjin** [comment]
哦，看起来是你自己修改了页面了，那就不关我的事了，这个错误是你引用了一个并不存在的变量。
