### ISSUE TITLE
用户修改失败更进，和自写的模板无关

### ISSUE THREAD

**Issue by david7207** [glzjin/ss-panel-v3-mod#79]
debug已经打开，但是没有显示任何错误！也修复了ajax了！
![bug5](https://cloud.githubusercontent.com/assets/9106366/15274709/0464bc78-1aec-11e6-9863-825bad7eb5e0.JPG)

**Comment by david7207** [comment]
![bug6](https://cloud.githubusercontent.com/assets/9106366/15274710/114ff574-1aec-11e6-866c-c54ca5b1ddf4.JPG)
chrome抓到的错误，求解！

**Comment by glzjin** [comment]
请点开最后一个请求，将返回结果发出来。

**Comment by david7207** [comment]
![bug1](https://cloud.githubusercontent.com/assets/9106366/15274763/43e17232-1aed-11e6-99d2-a879e95a0a8e.JPG)
127.0.0.1:1080是我用的代理，不用代理上传图片容易出问题。。。

**Comment by david7207** [comment]
我知道问题了，redius如果不用的话，必须清空数据，不然就这样！
