### ISSUE TITLE
新版购买商品问题，以及充值

### ISSUE THREAD

**Issue by david7207** [glzjin/ss-panel-v3-mod#80]
![bug7](https://cloud.githubusercontent.com/assets/9106366/15274917/fbea2b64-1af0-11e6-9791-70d2f725915b.JPG)
购买商品出现无法购买，但是钱仍然扣除，返回白框
同时建议充值的时候弹窗后自动刷新页面，目前版本貌似没有

**Comment by glzjin** [comment]
充值码充值之后会有提示。
glzjin
2016年5月15日 下午11:03，david <notifications@github.com>写道：
购买商品出现无法购买，但是钱仍然扣除，返回白框
同时建议充值的时候有个充值成功的弹窗，目前版本貌似没有

**Comment by david7207** [comment]
但是目前我购买也出了问题，返回结果貌似usercontroller出现问题

**Comment by glzjin** [comment]
而934行为 if($coupon->onetime==1) 请将详细的错误信息发出来，并且确认你的coupon表里有这个结构。
glzjin
2016年5月15日 下午11:14，glzjin <glzjin@zhaojin97.cn>写道：充值码充值之后会有提示。
glzjin
2016年5月15日 下午11:03，david <notifications@github.com>写道：
购买商品出现无法购买，但是钱仍然扣除，返回白框
同时建议充值的时候有个充值成功的弹窗，目前版本貌似没有

**Comment by david7207** [comment]
我看了下，有这个表，但是我用邀请码就能成功购买，不用邀请码就出现这样

**Comment by glzjin** [comment]
那个叫优惠码，请将出错的详细信息复制上来。
glzjin
2016年5月15日 下午11:44，david <notifications@github.com>写道：我看了下，有这个表，但是我用邀请码就能成功购买，不用邀请码就出现这样

**Comment by david7207** [comment]
debug已经开了，但是没有错误信息呀

**Comment by glzjin** [comment]
就是你截图那个没展示完的返回信息
glzjin
2016年5月16日 上午12:02，david <notifications@github.com>写道：debug已经开了，但是没有错误信息呀

**Comment by david7207** [comment]
@glzjin 
{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Trying to get property of non-object","file":"\/home\/wwwroot\/lastss.com\/app\/Controllers\/UserController.php","line":934}}

**Comment by david7207** [comment]
数据库也检查了下，没有我自定义的成分，.config.php也检查了

**Comment by david7207** [comment]
怎么样？这个是个例嘛？

**Comment by glzjin** [comment]
把php的error reporing关掉

**Comment by glzjin** [comment]
并没有发现你说的问题，还需要观察

**Comment by david7207** [comment]
需要关闭error reporting嘛？还有需要我给你开个账户吗？

**Comment by glzjin** [comment]
if($coupon==null)
		{
			if($coupon->onetime==1)
			{
				$price=$shop->price;
			}
		}

**Comment by david7207** [comment]
嗯，可以了，但是这个文件我没有修改过呀！

**Comment by glzjin** [comment]
public function buy($request, $response, $args)
    {
        $coupon = $request->getParam('coupon');
		$code = $coupon;
        $shop = $request->getParam('shop');
		
		$autorenew = $request->getParam('autorenew');
		
		$shop=Shop::where("id",$shop)->where("status",1)->first();
		
		if($shop==null)
		{
			$res['ret'] = 0;
            $res['msg'] = "非法请求";
            return $response->getBody()->write(json_encode($res));
		}
		
		if($coupon=="")
		{
			$credit=0;
		}
		else
		{
		
			$coupon=Coupon::where("code",$coupon)->first();
			
			if($coupon==null)
			{
				$credit=0;
			}
			else
			{
				if($coupon->onetime==1)
				{
					$onetime=true;
				}
				
				$credit=$coupon->credit;
			}
			
			if($coupon->order($shop->id)==FALSE)
			{
				$res['ret'] = 0;
				$res['msg'] = "此优惠码不可用于此商品";
				return $response->getBody()->write(json_encode($res));
			}
			
			if($coupon->expire<time())
			{
				$res['ret'] = 0;
				$res['msg'] = "此优惠码已过期";
				return $response->getBody()->write(json_encode($res));
			}
		}
		
		$price=$shop->price*((100-$credit)/100);
		$user=$this->user;
		if($user->money<$price)
		{
			$res['ret'] = 0;
			$res['msg'] = "余额不足";
			return $response->getBody()->write(json_encode($res));
		}
		
		$user->money=$user->money-$price;
		$user->save();
		
		$bought=new Bought();
		$bought->userid=$user->id;
		$bought->shopid=$shop->id;
		$bought->datetime=time();
		if($autorenew==0||$shop->auto_renew==0)
		{
			$bought->renew=0;
		}
		else
		{
			$bought->renew=time()+$shop->auto_renew*86400;
		}
		
		$bought->coupon=$code;
		
		
		if(isset($onetime))
		{
			$price=$shop->price;
		}
		$bought->price=$price;
		$bought->save();
		
		$shop->buy($user);
		
		$res['ret'] = 1;
        $res['msg'] = "购买成功";
		
		return $response->getBody()->write(json_encode($res));
    }

**Comment by glzjin** [comment]
你估计打开了某个设置，所以我在我这里没有任何问题=、=先改成这样吧 把这个函数 这样更恰当些。
