### ISSUE TITLE
Ubuntu 14用yum安装不了freeradius等软件,用sudo apt-get install安装后找不到相应文件夹

### ISSUE THREAD

**Issue by genics** [glzjin/ss-panel-v3-mod#81]
/etc/raddb/sql.conf  没有找到这个文件和文件夹,怎么办?

**Comment by fiepi** [comment]
看标题差点没笑粗声。。
debian/ubuntu下，freeradius 的配置文件应该在 /etc/freeradius

**Comment by glzjin** [comment]
哦，我注明了是CentOS的 Debian的自己改吧
glzjin
2016年5月16日 下午4:48，妹妹你好胸 <notifications@github.com>写道：看标题差点没笑粗声。。
debian/ubuntu下，freeradius 的配置文件应该在 /etc/freeradius
