### ISSUE TITLE
观察窗的网速测试结果为空值

### ISSUE THREAD

**Issue by fiepi** [glzjin/ss-panel-v3-mod#83]
发行版： archlinux
后端：ssshell-jar
![photo_2016-05-17_13-07-41](https://cloud.githubusercontent.com/assets/15153999/15311761/90c8dd1c-1c30-11e6-9425-cc6eabd5277f.jpg)

**Comment by glzjin** [comment]
请安装 speedtest-cli

**Comment by fiepi** [comment]
@glzjin 装有了，开新vps第一件事就是测速

**Comment by glzjin** [comment]
能正常调用吗，which speedtest-cli 看看

**Comment by fiepi** [comment]
/usr/bin/speedtest-cli

**Comment by glzjin** [comment]
可以手动用国内节点进行一次测速 并且将整个过程发出来吗？

**Comment by fiepi** [comment]
![speedtest](https://cloud.githubusercontent.com/assets/15153999/15400111/f4c14aaa-1e1c-11e6-941b-d824b0422b82.jpg)

**Comment by glzjin** [comment]
speedtest-cli --version

**Comment by glzjin** [comment]
试试看 --simple 能返回结果没。

**Comment by fiepi** [comment]
![screenshot_20160523-123534 01](https://cloud.githubusercontent.com/assets/15153999/15460400/44776402-2076-11e6-9740-26c1b24698c3.png)

**Comment by glzjin** [comment]
试试给JAVA的PATH加上/usr/bin
