### ISSUE TITLE
登录时“无”返回

### ISSUE THREAD

**Issue by xiadena** [glzjin/ss-panel-v3-mod#84]
php fix_bom.php后也无效，其他弹窗跳转均无问题

**Comment by glzjin** [comment]
请把debug打开，然后把网站地址发到这里

**Comment by xiadena** [comment]
vip.9kss.net

**Comment by glzjin** [comment]
给组测试账号和密码
glzjin
2016年5月17日 下午7:27，xiadena <notifications@github.com>写道：vip.9kss.net

**Comment by glzjin** [comment]
"SQLSTATE[HY000] [1045] Access denied for user 'bbs'@'localhost' (using password: YES)"
数据库信息填错
glzjin
2016年5月17日 下午7:38，glzjin <glzjin@zhaojin97.cn>写道：给组测试账号和密码
glzjin
2016年5月17日 下午7:27，xiadena <notifications@github.com>写道：vip.9kss.net

**Comment by xiadena** [comment]
谢谢，已解决，关闭吧
