### ISSUE TITLE
主要注册新帐号并登陆网页就会这样，管理员帐号没事

### ISSUE THREAD

**Issue by nyancat1** [glzjin/ss-panel-v3-mod#85]
http://img.nga.cn/attachments/mon_201605/17/-7_573b05fc74b95.png

截图如上

主要注册新帐号并登陆网页就会这样，管理员帐号登录没事  数据库进入后好像有报错

**Comment by glzjin** [comment]
图片打不开。。。=、=

**Comment by nyancat1** [comment]
你再试试  应该可以打开了 刚传错了=.=

另外我在数据库里USER字段删掉对应新注册的帐号  报错消失   继续注册帐号依然网站报错  求破T_T

**Comment by nyancat1** [comment]
截图就是  此网页包含重定向循环

**Comment by glzjin** [comment]
你用后台删呀。。。话说重定向的过程可以发个f12之后的网络截图出来吗 我看看重定向到哪个地址 对了 发个站点地址和邀请码出来

**Comment by nyancat1** [comment]
只要开始重定向  就无法进入后台   也无法登出   只能从数据库删除

地址  http://www.ngassjsq.ml/auth/login

邀请码 mEsL0zKakY83b4PXwjP875LEdCgSEkTe

大大我帮我看看呗

**Comment by glzjin** [comment]
glzjin
2016年5月17日 下午8:06，glzjin <glzjin@zhaojin97.cn>写道：我用chrome测试登录正常，请问你的浏览器是不是禁止了cookie保存呢
glzjin
2016年5月17日 下午7:56，nyancat1 <notifications@github.com>写道：截图就是  此网页包含重定向循环

**Comment by glzjin** [comment]
我用chrome测试登录正常，请问你的浏览器是不是禁止了cookie保存呢
glzjin
2016年5月17日 下午7:56，nyancat1 <notifications@github.com>写道：截图就是  此网页包含重定向循环

**Comment by nyancat1** [comment]
清除COOKIE后正常了。。

好像是登录过管理员帐号后再登录普通帐号就会这样- -  我的浏览器也是chrome内核的  有点蒙

总之还是谢谢大大了  耐心给我解答 ^^
