### ISSUE TITLE
大佬我又来了=.= 刚让几个朋友测试了下，大部分浏览器还是有重定向循环问题。

### ISSUE THREAD

**Issue by nyancat1** [glzjin/ss-panel-v3-mod#86]
好像就IE 和CHROME不会     CHROME内核的浏览器也会

其他浏览器注册完登录跳转依然会有重定向循环问题- -  到底是为啥呢  心好累T_T

**Comment by glzjin** [comment]
你是不是改了程序部分了了。。。我这里复现不了这个问题。。你把重定向的抓包图发下吧。。。我看看看重定向到什么地方。

**Comment by nyancat1** [comment]
好像OK了  我看了下PHP的LOG  

/usr/local/nginx/conf/vhost/ss.panel.conf

下我指向的域名太多了   捆了6个域名- - 。。然后DNS混乱   

现在改成一个就好了   sorry  打扰了

**Comment by nyancat1** [comment]
http://img.nga.cn/attachments/mon_201605/18/-7_573bcd56668c4.png

这是重定向抓包图    今天还是出现了  经过多人测试   IE不会出现  部分CHROME内核的浏览器会

求破- - 我已经蒙圈了QAQ

**Comment by nyancat1** [comment]
http://img.nga.cn/attachments/mon_201605/18/-7_573bcf44e8e5d.png

看了下抓包  难道是我自定义主页的问题吗  我主页就设了一个定向指向USER   然后login和user互相定向  是不是要加入if语句？  但是我主页用的html  用if是不是没用。。

**Comment by nyancat1** [comment]
http://img.nga.cn/attachments/mon_201605/18/-7_573bcfc4b94f4.png

就算我不从自定义主页进入用户中心   从这里进入  一样会重定向报错- - 我好迷QAQ

**Comment by glzjin** [comment]
这个是源码
glzjin
2016年5月18日 上午10:12，nyancat1 <notifications@github.com>写道：http://img.nga.cn/attachments/mon_201605/18/-7_573bcf44e8e5d.png

看了下抓包  难道是我自定义主页的问题吗  我主页就设了一个定向指向USER   然后login和user互相定向  是不是要加入if语句？  但是我主页用的html  用if是不是没用。。

**Comment by nyancat1** [comment]
http://img.nga.cn/attachments/mon_201605/18/-7_573bcd56668c4.png

上面这个是抓包- -

**Comment by nyancat1** [comment]
也许是DNS解析的问题吗- - 

我刚换了个域名   在测试下看看   之前那个域名可能解析出问题 连到之前老的V2user后台了- - ？

**Comment by nyancat1** [comment]
我在测试下换域名后的情况把- - 不好意思劳烦大佬了   目前好像又不会了

**Comment by glzjin** [comment]
一个站点只能使用一个唯一的域名
