### ISSUE TITLE
登录后不跳转

### ISSUE THREAD

**Issue by hemla** [glzjin/ss-panel-v3-mod#87]
登陆后不跳转，也没有错误提示，需要刷新才显示进入。

![1](https://cloud.githubusercontent.com/assets/18051159/15381572/4a86b55c-1db3-11e6-83ee-68c9fdf209a9.jpg)

**Comment by glzjin** [comment]
开 debug ，然后把返回的东西发过来。

**Comment by hemla** [comment]
{"error":{"type":"Illuminate\\Database\\QueryException","message":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: update `aws_users` set `password` = bf2fac69b5466874d0c3bcb3b00a6ec, `salt` = dajkcjks82hkjhck where `id` is null)","file":"\/home\/wwwroot\/ss.hemla.me\/vendor\/illuminate\/database\/Connection.php","line":673}}

这个吗？

**Comment by glzjin** [comment]
是的 你这是设置了wecenter?安装好了吗？数据库信息填对了嘛？

**Comment by hemla** [comment]
不好意思，刚看到。
问答设置了，也安装好了，能正常使用。

**Comment by hemla** [comment]
@glzjin 我看到在更新说明里：“可直接同步用户信息到 wecenter ,并且用户在登录sspanel时就会自动登录到这个论坛系统。”
我现在的情况应该是用户能同步到wecenter，但是进了面板后点开问答并没有自动登录论坛系统。

**Comment by hemla** [comment]
通过管理员后台修改了普通用户密码后，用户就能登录了，从数据库里看salt也变为了随机四位数

**Comment by xiadena** [comment]
wecenter没配置好吧，配置好了自动会改salt，正确的salt应和ss-panel的用户salt相同

**Comment by hemla** [comment]
#Wecenter 数据库信息
$System_Config['wecenter_db_host']=' ';
$System_Config['wecenter_db_database']=' ';
$System_Config['wecenter_db_user']=' ';
$System_Config['wecenter_db_password']=' ';

#系统主域名 ***.com 这样的
$System_Config['wecenter_system_main_domain']='  ';

#访问路径
$System_Config['wecenter_url']=' ';

#可从安装好的 wecenter 目录下的 system/config.inc.php 得到

#G_COOKIE_PREFIX
$System_Config['wecenter_cookie_prefix']=' ';

#G_COOKIE_HASH_KEY
$System_Config['wecenter_cookie_key']=' ';

@xiadena wecenter配置就这几项吧？应该是没错的，很奇怪

**Comment by xiadena** [comment]
自己新建一个用户，点问答，能自动跳转登录不。并且看数据库生成的盐和ss-panel的一不一样，不一样的话就是配置wecenter错了

**Comment by hemla** [comment]
@xiadena 尝试过了，不能自动登录，数据库里看生成的salt与sspanel的一样，但是登录不了

**Comment by hemla** [comment]
@xiadena 新注册用户后，第一次登录可以正常跳转，同时也能登录wecenter，但是退出后再次登录就不会跳转了，也不会自动登录wecenter，手动登录wecenter时提示账号密码错误。

**Comment by hemla** [comment]
debug返回的信息与上边截图相同。

**Comment by xiadena** [comment]
我记得wecenter的salt最多只能15个字符，你

**Comment by hemla** [comment]
应该是跟salt的位数没有关系，更改了salt，debug返回同样的错误。

**Comment by hemla** [comment]
找到问题所在了，应该就是salt位数的问题，更改salt后新注册用户就可以正常跳转斌刚登陆salt了。

**Comment by glzjin** [comment]
你的wecenter数据库信息没填对
glzjin
2016年5月23日 上午10:29，hemla <notifications@github.com>写道：@glzjin 我看到在更新说明里：“可直接同步用户信息到 wecenter ,并且用户在登录sspanel时就会自动登录到这个论坛系统。”
我现在的情况应该是用户能同步到wecenter，但是进了面板后点开问答并没有自动登录论坛系统。

**Comment by hemla** [comment]
@glzjin 现在确实可以跳转了，但是wecenter依旧不自动登录，新注册账号也能同步到数据库中。
![1](https://cloud.githubusercontent.com/assets/18051159/15497075/6a2e2540-21cb-11e6-9322-7e6a0a4159cd.png)
![2](https://cloud.githubusercontent.com/assets/18051159/15497077/6a534fd2-21cb-11e6-8a44-450b3b6c76b2.jpg)

**Comment by xiadena** [comment]
新建的帐号能自动登录吗，是不是只有admin无法自动登录移，你这些问题我好像都遇到了，

首先配置好邮件功能，确保能通过邮件重制密码，
然后手动修改掉数据库中admin的salt与其他用户的salt保持一致，
最后邮件重置密码

**Comment by xiadena** [comment]
其实就是要用wecenter的话ss-panel的salt设置不能超过15位字符（好像是15吧2333），不然两处密码会因salt不同而不一致，导致无法自动登录

**Comment by hemla** [comment]
salt已经设置为8位了，登陆后跳转的问题解决了，然后把wecenter重新安装了。
新建账号无法自动登录，登录面板后，进wecenter的数据库能看到新建账号。

是只有管理员能登录，其他用户比如salt3和salt4都不行，登录也不提示账号密码错误，自动刷新为未登录的样子。但是salt3和salt4用户的salt值确实是sspanel里边设置的。第一行那个用户是安装wecenter设置的管理员账号，salt值就是4个字符。
