### ISSUE TITLE
请教下一些小白的问题

### ISSUE THREAD

**Issue by acix** [glzjin/ss-panel-v3-mod#88]
导入了sql之后，看到那两个智能线路的节点 id ,填到这。不使用的话导入之后也要填

$System_Config['cloudxns_ping_nodeid']='3.4';#导入了sql之后，看到那两个智能线路的节点 id ,填到这。不使用的话导入之后也要填。
 

是这样填写吗

**Comment by glzjin** [comment]
不是 有两个设置 分别填两个节点的ID
glzjin
2016年5月19日 下午1:20，acix <notifications@github.com>写道：导入了sql之后，看到那两个智能线路的节点 id ,填到这。不使用的话导入之后也要填

$System_Config['cloudxns_ping_nodeid']='3.4';#导入了sql之后，看到那两个智能线路的节点 id ,填到这。不使用的话导入之后也要填。

是这样填写吗

**Comment by acix** [comment]
$System_Config['cloudxns_ping_nodeid']='3';#导入了sql之后，看到那两个智能线路的节点 id ,填到这。不使用的话导入之后也要填。
$System_Config['cloudxns_speed_nodeid']='4';#同上
这样填写对吗？
也就是说  节点3和4那个智能线路  是作为测速用的吧    是不能删除的吧？

**Comment by acix** [comment]
是不是 我自己的线路节点ID 填上去    一个测ping  一个测速度？

**Comment by glzjin** [comment]
你导入之后得到的那两个智能节点ID
glzjin
2016年5月19日 下午1:35，acix <notifications@github.com>写道：是不是 我自己的线路节点ID 填上去    一个测ping  一个测速度？

**Comment by acix** [comment]
speedtest=1 #测速时间周期
#测速周期/h
$System_Config['Speedtest_duration']='6';


请教下  一个后端  一个前端       有什么区别吗

**Comment by glzjin** [comment]
保持一样就行 都是小时为单位
glzjin
2016年5月19日 下午2:38，acix <notifications@github.com>写道：speedtest=1 #测速时间周期
#测速周期/h
$System_Config['Speedtest_duration']='6';

请教下  一个后端  一个前端       有什么区别吗

**Comment by acix** [comment]
再请教下， 点了节点信息，先跳到你的博客，然后再转过来？
这个是否正常？
能不能不跳？大大的几个字  攻击者你们不累吗？

**Comment by glzjin** [comment]
很正常，因为在写这个iframe的时候我顺手加上了，在节点信息还没加载出来的时候先有些内容撑着，你不喜欢可以自己改模板改掉。

**Comment by acix** [comment]
....我小白啊    我把地址改成自己SS的地址

为啥跳转的一刹那   出来个长者的图片   不要吓我啊

**Comment by glzjin** [comment]
没出现错误的话不会弹出，这是为了敬祝他万寿无疆
