### ISSUE TITLE
用户分组后，依旧可以使用其他组的节点

### ISSUE THREAD

**Issue by pkwjh** [glzjin/ss-panel-v3-mod#89]
将用户分成A组和B组，分组后，A组看不到B组的节点，但是只要知道IP地址，A组依旧可以使用该节点。
希望修正，不然分组就木有意义啦。

**Comment by glzjin** [comment]
请确认ab两组的ID均不为0 否则会拉取所有的用户 程序里已做了查询限制的 如果是ssshell会立即生效，如果是go mu 会有些延迟 

SelectUserInfoResultSet = SelectUserInfoStatement.executeQuery("SELECT * FROM user WHERE `class`>="+Node_Class+(Node_Group!=0?" AND "+"`node_group`="+Node_Group:"")+" AND`enable`=1 AND `expire_in`>now() AND `transfer_enable`>`u`+`d`");

所有隔离都是前后端一起隔离，理论上并不会出现你所提到的情况。

如果你还有问题，请继续在下面跟帖说出你的情况。
