### ISSUE TITLE
能不能加上这个功能？

### ISSUE THREAD

**Issue by acix** [glzjin/ss-panel-v3-mod#90]
现在流量记录只是记录流量的流水账 
无法查询到某个用户具体哪个节点用了多少流量的统计
大神有闲的话 
能不能做个统计，某某用户A节点用流量XX,B节点用流量XX
感谢万分

**Comment by glzjin** [comment]
你在用户侧是能看到的 不过目前是以时间为轴 靠近的会合到一起

**Comment by acix** [comment]
只能用户自查？ 
我现在有2个SS 合租   一个流量是阿里云 算钱的   另外一个流量不要钱
我现在只能搞2个网站，要不然月底流量算不清

**Comment by fiepi** [comment]
@acix  不计费就把流量比例设为零

**Comment by acix** [comment]
。。。我怎么没想到！
