### ISSUE TITLE
登陆不跳转

### ISSUE THREAD

**Issue by Git-Chen** [glzjin/ss-panel-v3-mod#91]
登陆不跳转 其他页面同样不跳转
![qq 20160520185622](https://cloud.githubusercontent.com/assets/18627743/15425709/c5c1de72-1ebc-11e6-9298-7ee4f1a5967e.png)
站点 moess.tk

**Comment by glzjin** [comment]
执行一下 php fix_bom.php

**Comment by Git-Chen** [comment]
成功 谢谢
