### ISSUE TITLE
大佬你好，请教几个问题。

### ISSUE THREAD

**Issue by nyancat1** [glzjin/ss-panel-v3-mod#92]
第一个是我在节点编辑里   进行限速

如果限制为1-2MBPS    玩游戏就容易掉线  丢包 

但是不限速就不会      1-2MBPS应该是够玩游戏的上下行了     求教这是为啥

另外还有个邮件服务器的问题   我使用了OUTLOOK提供的SMTP信息  CONFIG里也没填错

但是依旧无法发送邮件

**Comment by nyancat1** [comment]
# smtp
$System_Config['smtp_host'] = 'smtp-mail.outlook.com';
$System_Config['smtp_username'] = 'xxx@outlook.com';
$System_Config['smtp_port'] = '587';
$System_Config['smtp_name'] = 'xxx@outlook.com';
$System_Config['smtp_sender'] = 'xxx@outlook.com';
$System_Config['smtp_passsword'] = '1xxx';
$System_Config['smtp_ssl'] = 'true';

SMTP是这样填的   上面的mailgun 和smtp我也填了smtp值  上面的帐号密码我也确认没填错

**Comment by glzjin** [comment]
1.ssshell最新版=、=？
2.smtp换成25端口关掉ssl试试吧

**Comment by nyancat1** [comment]
对  最新版    才刚装上去的 =.=

难道我限制的速度太少了？讲道理1MBPS 也有100K/S了

**Comment by nyancat1** [comment]
按照你说的端口改成25   SSL关掉也无效

OUTLOOK网站上写的配置是这样的  但是按照他这样也无效

SMTP配置
服务器名称: smtp-mail.outlook.com
端口: 587
加密方法: TLS

**Comment by nyancat1** [comment]
好了    我重启了下服务器   端口25  SSL关掉OK了

谢谢大佬！

**Comment by nyancat1** [comment]
另外限速这个是为啥呢

还是要到用户资料去限速 而不是节点编辑限速

**Comment by glzjin** [comment]
是的，估计是trickle的问题了 去找找他们的文档吧 话说你有没有开finalspeed之类的东西
glzjin
2016年5月21日 上午8:17，nyancat1 <notifications@github.com>写道：对  最新版    才刚装上去的 =.=

难道我限制的速度太少了？讲道理1MBPS 也有100K/S了

**Comment by nyancat1** [comment]
开了一个锐速  没其他东西了0.0

**Comment by glzjin** [comment]
限速，取用户限速和节点限速中的较大值。
