### ISSUE TITLE
您好! 请问能进行定向的流量限制吗?

### ISSUE THREAD

**Issue by zfan67** [glzjin/ss-panel-v3-mod#93]
譬如某一用户剩余流量100+G, 能随时切换A B C三个节点,  如果需要限制其A节点的定向流量最多为10G, 使用完毕后其余90G+流量只能使用B C节点, 类似这样的定向流量限制请问有办法实现吗?

**Comment by glzjin** [comment]
很麻烦，自己弄吧。=、=
