### ISSUE TITLE
为方便管理，希望能在管理员菜单增加节点状况列表

### ISSUE THREAD

**Issue by pkwjh** [glzjin/ss-panel-v3-mod#94]
自从使用分组管理之后，管理起来就不那么方便了，现有的管理模式还是优先给不分组的用户使用的。
比如昨晚用户反馈某一个节点出问题，我们就跑去看，结果看不到，因为我们要到用户界面才能看到节点状况，因此我们要找到这个用户是在哪个组别，然后把我们自己的号切换到这个组别，才能进到用户界面查看到节点信息。

为了不改变太多，或者说分不分组管理都可以使用。我建议：

在管理界面的左侧菜单里面，增加一个“节点信息”页面

里面列出所有节点的名字，健康状况，在线人数（当然如果可以看到这个节点有哪些用户在使用那就更好）。排版模式可以按照用户界面的“节点列表”来。

**Comment by glzjin** [comment]
比较的办法 是直接SSH连上那个节点 然后直接检查后端故障。
glzjin
2016年5月21日 下午6:09，pkwjh <notifications@github.com>写道：自从使用分组管理之后，管理起来就不那么方便了，现有的管理模式还是优先给不分组的用户使用的。
比如昨晚用户反馈某一个节点出问题，我们就跑去看，结果看不到，因为我们要到用户界面才能看到节点状况，因此我们要找到这个用户是在哪个组别，然后把我们自己的号切换到这个组别，才能进到用户界面查看到节点信息。

为了不改变太多，或者说分不分组管理都可以使用。我建议：

在管理界面的左侧菜单里面，增加一个“节点信息”页面

里面列出所有节点的名字，健康状况，在线人数（当然如果可以看到这个节点有哪些用户在使用那就更好）。排版模式可以按照用户界面的“节点列表”来。

**Comment by pkwjh** [comment]
你说的方法只能检测节点，但是有时我需要看是不是因为在线人数太多而出现问题。
或者另外一个方法，允许管理员能看到并使用所有节点，方面管理员能连接SS直接测试。

**Comment by pkwjh** [comment]
允许管理员能看到并使用所有节点，不受分组影响，而且方面管理员能连接SS直接测试。
这个看起来改动比较小的样子

**Comment by glzjin** [comment]
很麻烦=、=我也用不到，我不想改了 当然你们做了的话欢迎提交pull request
glzjin
2016年5月21日 下午6:15，pkwjh <notifications@github.com>写道：你说的方法只能检测节点，但是有时我需要看是不是因为在线人数太多而出现问题。
或者另外一个方法，允许管理员能看到并使用所有节点，方面管理员能连接SS直接测试。
