### ISSUE TITLE
最近更新之后用户无法注册

### ISSUE THREAD

**Issue by fiepi** [glzjin/ss-panel-v3-mod#95]
提交注册后无响应。
![tt](https://cloud.githubusercontent.com/assets/15153999/15451998/f49275d6-2010-11e6-97e8-021d6faec7d9.png)

**Comment by fiepi** [comment]
回退版本之后可注册成功

**Comment by david7207** [comment]
@fiepi 你写issuess时候要保留你的网址链接呢，检查你的底部信息

**Comment by fiepi** [comment]
@david7207 https://ss.fiepi.top
生产环境其实用的是原版。
这mod版问题实在太多，主要用于体验

**Comment by glzjin** [comment]
请提交开启debug之后的返回信息
