### ISSUE TITLE
删除帐号问题

### ISSUE THREAD

**Issue by david7207** [glzjin/ss-panel-v3-mod#96]
![bug1](https://cloud.githubusercontent.com/assets/9106366/15453115/f84fa656-203a-11e6-9130-104a8b82504d.JPG)
删除的账户时候出现这个，具体的 response是：
{"error":{"type":"Whoops\\Exception\\ErrorException","message":"Undefined variable: email","file":"\/home\/wwwroot\/lastss.com\/app\/Controllers\/UserController.php","line":1332}}
我关闭php.ini的error reporting还是没法删除，依然这样，我的是php7
关闭error reporting的response是：
{
    "message": "Slim Application Error"
}

**Comment by david7207** [comment]
网址是www.lastss.com

**Comment by glzjin** [comment]
https://github.com/glzjin/ss-panel-v3-mod/commit/ba637a17d502bfcfd350dcae0e5e9331bc810639
