### ISSUE TITLE
配置Radius出错

### ISSUE THREAD

**Issue by Tomzuo** [glzjin/ss-panel-v3-mod#97]
找不到文件  /etc/raddb/sql.conf
还有：
/etc/raddb/sql/mysql/dialup.conf: No such file or directory
/etc/raddb/sql/mysql/counter.conf: No such file or directory

**Comment by glzjin** [comment]
请提供站点地址，否则在一天之后此issue会被关闭。

请问你是CentOS吗？非CentOS请自行研究Radius配置方法。

**Comment by macallen** [comment]
昨天遇到过一次radius安装后没有sql.conf等一票文件，重装后ok

**Comment by Tomzuo** [comment]
@glzjin http://jaffar.ml/

**Comment by glzjin** [comment]
我无法解决，请自行上网搜索。
