### ISSUE TITLE
有几张配置图片失效了 

### ISSUE THREAD

**Issue by xjndfdfe** [glzjin/ss-panel-v3-mod#98]
求修复

分别是
1:
lnmp vhost add
进行接下来的设置

2:
10.然后我们打开 phpmyadmin ,来配置数据库了。

先添加，创建一个数据库，并且添加一个用户。

3:
OK，然后我们再对这个数据库创建一个用户，用于 ss-panel 通讯。

**Comment by glzjin** [comment]
之后再弄了。
